import test from 'node:test';
import assert from 'node:assert/strict';
import {library,categories,searchLibrary,guideType} from '../lib/library.mjs';
import {readiness} from '../lib/readiness.mjs';
import {products,ownedChoices} from '../lib/catalog.mjs';
test('Expanded library has unique complete entries and categories',()=>{assert.equal(library.length,77);assert.equal(categories.length,11);assert.equal(new Set(library.map(p=>p.id)).size,library.length);for(const p of library){assert.ok(categories.some(c=>c.id===p.category));assert.ok(p.title&&p.summary);if(p.kind==='brief')assert.ok(p.observe&&p.next&&p.stop);}});
test('Search finds real user terms and applies intersecting filters',()=>{assert.ok(searchLibrary({query:'pex'}).some(p=>p.id==='pex-line'));assert.ok(searchLibrary({query:'planting beds'}).some(p=>p.id==='raised-bed'));assert.ok(searchLibrary({query:'gfci'}).some(p=>p.id==='gfci-trip'));assert.equal(searchLibrary({category:'pavers'}).length,6);assert.equal(searchLibrary({category:'pavers',mode:'maintain'}).length,2);assert.equal(searchLibrary({category:'pavers',kind:'plan'}).length,0);assert.equal(searchLibrary({query:'XYZZY'}).length,0);});
test('All preparation and project kit references resolve',()=>{for(const p of library){const r=readiness(p,[],p.id==='planter'?'solid':'plywood');for(const x of r.items)assert.ok(products.some(item=>item.id===x.id));}assert.equal(ownedChoices.length,products.length);});
test('Ownership and conditional substitutes remain distinct',()=>{const p=library.find(p=>p.id==='cabinet-doors');const r=readiness(p,['saw','drill','sanding-block']);assert.equal(r.covered,2);const sander=r.items.find(p=>p.id==='sander');assert.equal(sander.owned,false);assert.equal(sander.alternative.owned,true);assert.equal(r.items.find(p=>p.id==='eye').alternative,null);});
test('Urgent and electrical topics do not prompt tool shopping',()=>{for(const p of library.filter(p=>p.mode==='urgent'||p.category==='electrical')){const r=readiness(p);assert.equal(r.blocked,true);assert.deepEqual(r.items,[]);}});
test('Brief checks state their limited coverage',()=>{const p=library.find(p=>p.id==='paver-patio');assert.match(readiness(p).scope,/Preparation tools only/);});
test('Home requests accept ordinary phrasing without a random match',()=>{assert.ok(searchLibrary({query:'my basement is flooded'}).some(p=>p.id==='basement-flood'));assert.ok(searchLibrary({query:'I want to build a raised bed'}).some(p=>p.id==='raised-bed'));assert.equal(searchLibrary({query:'my invisible teleportation unit'}).length,0);});

test('Door inflections and natural descriptions rank the sticking-door guide first',()=>{for(const query of ['stick door','sticking door','door sticks','jammed door','door rubs',"My bathroom door won't close properly, it rubs at the top"]){assert.equal(searchLibrary({query})[0].id,'sticking-door',query);}});
test('Unfiltered library puts step-by-step guides before briefs',()=>{const results=searchLibrary();assert.ok(results.slice(0,12).every(p=>guideType(p)==='procedure'));assert.ok(results.slice(12).every(p=>guideType(p)!=='procedure'));assert.equal(searchLibrary({kind:'procedure'}).length,12);assert.equal(searchLibrary({kind:'system'}).length,16);assert.equal(searchLibrary({kind:'design'}).length,1);});
