import test from 'node:test';
import assert from 'node:assert/strict';
import {createConversation,applyAnswer} from '../lib/conversation.mjs';
import {parseDimensions,millimetres} from '../lib/measurements.mjs';
import {proposeChange,applyChange,undoChange} from '../lib/project-actions.mjs';
import {shoppingRows,shoppingCSV,gardenQuantities,exportProject} from '../lib/project-pack.mjs';
import {makeBackup,validateBackup,mergeBackup} from '../lib/workspace-backup.mjs';
function book(){let r=createConversation('A bookcase','test-book');for(const a of ['Books','70 x 100 x 30 cm','2','Spray paint'])r=applyAnswer(r,a);return r;}
test('Measurements convert units and reject invalid dimensions without mutating a project',()=>{assert.deepEqual(parseDimensions('28 x 40 x 12 in'),{width:711,height:1016,depth:305});assert.equal(millimetres(0.3,'m'),300);assert.equal(parseDimensions('roughly big'),null);let r=book();assert.throws(()=>proposeChange(r,'make it 3 m wide'));assert.equal(r.answers.dimensions,'700 × 1000 × 300 mm');});
test('Natural-language revisions preview, apply and undo without losing the brief',()=>{const original=book(),proposal=proposeChange(original,'make it 75 cm wide and add one shelf');assert.equal(proposal.input.width,750);assert.equal(proposal.input.shelves,3);assert.equal(original.pack,undefined);const changed=applyChange(original,proposal);assert.equal(changed.pack.input.width,750);assert.deepEqual(changed.pack.reviewed,[]);assert.equal(changed.request,original.request);const restored=undoChange(changed);assert.deepEqual(restored.answers,original.answers);assert.equal(restored.pack,null);assert.match(proposeChange(original,'Use MDF instead').unsupported,/plywood only/);});
test('Shopping excludes owned tools and allocates each material piece only once',()=>{const r=book(),items=[{id:'tape',name:'Tape measure'},{id:'drill',name:'Drill'}];const rows=shoppingRows(r,items,['tape'],[{name:'Offcut',length:1000,width:400,thickness:18,qty:1,sound:true}]);assert.equal(rows.find(x=>x.id==='tape').owned,true);assert.equal(rows.find(x=>x.id==='drill').owned,false);assert.equal(rows.find(x=>x.id==='part-A').qty,1);assert.equal(rows.find(x=>x.id==='part-B').qty,2);assert.match(shoppingCSV(rows),/Already owned/);});
test('Raised-bed quantities use entered dimensions and withhold balcony calculation',()=>{const r={guideId:'raised-bed',answers:{location:'On soil',size:'2 x 1 x 0.3 m'}};assert.equal(gardenQuantities(r).litres,600);assert.equal(gardenQuantities(r).bags40,15);assert.deepEqual(gardenQuantities({...r,answers:{...r.answers,location:'On a balcony or roof'}}),{blocked:true});});
test('Printable pack includes current geometry and safely escaped user notes',()=>{const r={...book(),notes:'<script>alert(1)</script>'};const html=exportProject(r,[],[]);assert.match(html,/700 mm wide/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>/);assert.match(html,/Tools & materials/);});
test('Backup roundtrip validates input, preserves projects and merges collisions as copies',()=>{const r=book(),raw=makeBackup([r],['tape','not-a-tool'],[]),backup=validateBackup(raw);assert.deepEqual(backup.owned,['tape']);assert.equal(backup.conversations[0].request,r.request);const merged=mergeBackup([r],backup,()=> 'copy-id');assert.equal(merged.length,2);assert.equal(merged[0].id,'copy-id');assert.equal(merged[1].id,r.id);assert.throws(()=>validateBackup('{"version":1}'));assert.throws(()=>validateBackup(makeBackup([{...r,answers:{bad:{}}}],[],[])));});
