// Business identity is supplied by the operator, not inferred from a login account.
export const legalIdentity={name:'Kitsley',email:''};
export const policyDate='26 September 2026';
export const privacySections=[
 ['What Kitsley stores','You can read the library and use free starting guidance without an account. Guest projects, recent requests, kit items, equipment details and preferences are stored in your browser. Clearing site data can remove them. When you sign in, Kitsley stores your account identity and syncs your projects, conversations, designs, progress, materials, equipment, experience preferences and project completion reviews to its account database. On the first sign-in in a browser, existing guest work is imported into that account.'],
 ['Why we use it','We use your information to provide and save guidance, adapt your project, keep devices in sync, administer plans and usage limits, operate checkout, diagnose failures and prevent abuse. Your experience settings are self-reported; they are not qualifications. Do not enter passwords, government identifiers, payment card details or information you do not have permission to share into project messages.'],
 ['AI help and learning','When you request an AI answer, relevant project details, recent messages, design information, owned equipment, experience preferences and project completion reviews are sent to OpenAI to prepare the response. Requests may use web search for supporting sources. Kitsley asks the search process to exclude private identifying details, but avoid including sensitive information in your request. Ordinary library reading and deterministic starting guidance do not require an AI call. Kitsley currently uses aggregated guide-topic counts to identify improvements. This does not automatically train a separate Kitsley model or publish your private conversations as shared guidance.'],
 ['Sign-in, hosting and payments','Supabase provides authentication and account storage; Heroku hosts the application. Google sign-in supplies basic account/profile information. Kitsley does not receive your Google password or request access to Gmail or Drive. Stripe handles payment details through its checkout interface. Kitsley stores billing identifiers, access grants and usage records, rather than full payment card numbers. These providers may process data outside your country under their own terms and safeguards.'],
 ['Location and retailer searches','Location is optional. You can enter a postal code instead of allowing browser location access. When you submit a retailer search, the product query, country, postal code or coordinates, requested radius and quantity are sent to Kitsley and OpenAI for the search. Server-side coordinates are rounded to three decimal places. Retailer and video sites receive your request when you open them and apply their own policies. Prices and stock shown by those sites can change.'],
 ['Cookies, local storage and activity records','Kitsley uses browser storage for saved work, account caching and preferences, and authentication cookies for sign-in. Payment and sign-in providers may use their own cookies. The application records limited operational and usage data, including allowance consumption, referral clicks, plan selections and error information. Hosting providers may also keep request and security logs. Signing out does not erase browser caches; use a private device, and clear site data on a shared device after exporting anything you need.'],
 ['Your choices and retention','Completion reviews record the work you confirm doing and whether tools were owned, borrowed or rented. They inform your practice history; experience levels change only with your confirmation. You can edit or delete projects in My projects, change kit and experience details, and export a workspace backup. Synced deletions take effect when your device reconnects; downloaded files and other offline copies are separate. Account work is retained so you can resume it, including after paid access ends. Billing, security, recovery and provider backup records may remain where needed for their purpose or a legal obligation. To request access, correction, account deletion, or to raise a privacy concern, contact us below. We may need to verify your identity before acting.'],
 ['Safeguards and changes','Account access controls and authenticated connections help protect stored work. No online service can guarantee complete security. Kitsley is intended for adults managing their own projects, not for children to use without adult supervision. We will update this page when practices change and seek additional consent where required for a materially different use.']
];
export const termsSections=[
 ['What the service provides','Kitsley offers DIY reference information, project planning, supported design tools and AI-assisted guidance. It is software, not a licensed contractor, architect, engineer, inspector or emergency service. A paid plan adds the described capabilities and allowances; it does not turn a draft or unsupported design into professional approval.'],
 ['Use guidance within its limits','Check measurements, material condition, exact product instructions and applicable local requirements before buying, cutting, drilling or assembling. Drawings are available only for supported design operations. AI answers can be incomplete or wrong. A source link, successful calculation or completed checklist is not proof of structural capacity, code compliance or site safety. Stop when conditions differ or important facts are missing. Use qualified trades or designers where the work, law or risk requires them.'],
 ['Your account and projects','Use accurate information and keep your sign-in secure. You are responsible for content you submit and must have permission to use it. You retain your project content and permit Kitsley and its service providers to process it to deliver the features you request. Do not use the service to bypass safety systems, misuse another person’s account, submit malicious content or disrupt the service.'],
 ['Free and paid access','Free library guidance and setup remain available without payment. Account-based AI allowances, Project Pass and Plus limits are shown on Plans & pricing and at checkout. The Project Pass is for one selected project for 30 days without automatic renewal. Plus renews monthly until renewal is cancelled. Allowances do not roll over and there are no automatic overage charges. The checkout amount and currency are shown before you confirm. Sandbox checkout is labelled as a test and does not take a real payment.'],
 ['Cancellation and billing problems','Use Account → My plan & billing → Manage billing & cancellation to manage an existing subscription. Cancelling renewal stops future renewal charges; already-paid access normally continues until its displayed end date. Saved work remains readable after paid access ends. Contact us about duplicate charges, unavailable paid services or a refund request. Applicable consumer rights are not limited by these terms.'],
 ['Retailers and affiliate links','Kitsley may earn a commission from qualifying purchases through marked affiliate links. Retailers set their own prices, availability, delivery, returns and warranties. Published listings and estimates are not guaranteed checkout totals or verified local stock. Product suitability must be checked against the actual project and manufacturer specifications. A referral relationship is not a safety endorsement.'],
 ['Availability and responsibility','The service may change or be temporarily unavailable. Export important project information before relying on it offline. Kitsley does not guarantee a particular project outcome, uninterrupted access or error-free AI responses. Nothing in these terms excludes rights or responsibilities that cannot lawfully be excluded. These terms do not authorize work that is unsafe or prohibited.'],
 ['Changes and contact','We will identify updates with a new date and provide additional notice of material changes where appropriate. Contact the operator below with service or billing questions. Our Privacy policy explains how project and account information is used.']
];
