'use client';
import {prepareSignOut,recoveryVersions,stopWorkspaceSync} from '../lib/account-storage.mjs';
import SyncStatus from './sync-status';
import BrandMark from './brand-mark';
import {useEffect,useRef,useState} from 'react';
export default function Account({triggerLabel}){const dialog=useRef(null),[account,setAccount]=useState(null),[providers,setProviders]=useState({google:false,apple:false}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
async function load(){try{const r=await fetch('/api/account',{cache:'no-store'}),data=await r.json();setProviders(data.providers||{google:false,apple:false});if(!r.ok)throw new Error(data.error);setAccount(data.user);}catch(e){setError(e.message||'Could not load account information.');}finally{setLoaded(true);}}
useEffect(()=>{load();if(new URLSearchParams(window.location.search).get('signin')==='failed'){setError('Sign-in was not completed. Please try again.');dialog.current?.showModal();}},[]);
async function signIn(provider){setBusy(true);setError('');try{const r=await fetch('/auth/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,returnTo:window.location.pathname+window.location.search})}),d=await r.json();if(!r.ok)throw new Error(d.error);window.location.assign(d.url);}catch(e){setError(e.message);setBusy(false);}}
async function signOut(){setBusy(true);setError('');try{await prepareSignOut();const r=await fetch('/api/account',{method:'POST'});const data=await r.json();if(!r.ok)throw new Error(data.error);stopWorkspaceSync();localStorage.setItem('kitsley-session-account','guest');window.location.assign('/');}catch(e){setError(e.message);}finally{setBusy(false);}}
return <><button className="account-button" onClick={()=>dialog.current?.showModal()}>{triggerLabel||(account?'Account':'Sign in')}</button><dialog className="account-dialog" ref={dialog} aria-labelledby="account-heading" onClick={e=>{if(e.target===dialog.current)dialog.current.close();}}><button className="dialog-close" aria-label="Close sign-in" onClick={()=>dialog.current?.close()}>×</button><BrandMark/><h2 id="account-heading">{account?'Your Kitsley account':'Welcome to Kitsley.'}</h2>{account?<><p>Signed in as {account.name}.</p><p className="small">Your projects, conversations, toolbox, materials and saved designs sync across devices when you sign in with this account.</p><p><SyncStatus/></p><details className="account-recovery"><summary>Recovery options</summary><button className="text-button" onClick={()=>{const data=recoveryVersions();if(!Object.keys(data).length){setError("No conflicting versions to recover.");return;}const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download="kitsley-recovered-versions.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download recovered versions</button></details><a className="secondary" href="/offers">My plan & billing →</a><button className="secondary" disabled={busy} onClick={signOut}>Sign out</button></>:<><p>Sign in with an account you already use. You can also keep exploring as a guest.</p><button className="provider-button" disabled={busy||!providers.google} onClick={()=>signIn('google')}>Continue with Google</button>{providers.apple&&<button className="provider-button apple-provider" disabled={busy} onClick={()=>signIn('apple')}>Continue with Apple</button>}{loaded&&!providers.google&&!providers.apple&&<p className="auth-preview-note">Sign-in is not available in this preview yet. You can browse, plan and save on this device without it.</p>}<button className="text-button" onClick={()=>dialog.current?.close()}>Continue as guest →</button></>}{error&&<p className="error" role="alert">{error}</p>}</dialog></>;
}
