'use client';
import BrandMark from './brand-mark';
import {useEffect,useRef,useState} from 'react';
export default function Account(){const dialog=useRef(null),[account,setAccount]=useState(null),[providers,setProviders]=useState({google:false,apple:false}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
async function load(){try{const r=await fetch('/api/account',{cache:'no-store'}),data=await r.json();setProviders(data.providers||{google:false,apple:false});if(!r.ok)throw new Error(data.error);setAccount(data.user);}catch(e){setError(e.message||'Could not load account information.');}finally{setLoaded(true);}}
useEffect(()=>{load();if(new URLSearchParams(window.location.search).get('signin')==='failed'){setError('Sign-in was not completed. Please try again.');dialog.current?.showModal();}},[]);
async function signIn(provider){setBusy(true);setError('');try{const r=await fetch('/auth/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider})}),d=await r.json();if(!r.ok)throw new Error(d.error);window.location.assign(d.url);}catch(e){setError(e.message);setBusy(false);}}
async function signOut(){setBusy(true);setError('');try{const r=await fetch('/api/account',{method:'POST'});const data=await r.json();if(!r.ok)throw new Error(data.error);setAccount(null);dialog.current?.close();}catch(e){setError(e.message);}finally{setBusy(false);}}
return <><button className="account-button" onClick={()=>dialog.current?.showModal()}>{account?'Account':'Sign in'}</button><dialog className="account-dialog" ref={dialog} aria-labelledby="account-heading" onClick={e=>{if(e.target===dialog.current)dialog.current.close();}}><button className="dialog-close" aria-label="Close sign-in" onClick={()=>dialog.current?.close()}>×</button><BrandMark/><h2 id="account-heading">{account?'Your Kitsley account':'Welcome to Kitsley.'}</h2>{account?<><p>Signed in as {account.name}.</p><p className="small">This preview still stores your toolbox and project progress in this browser. Cross-device sync is not connected yet.</p><button className="secondary" disabled={busy} onClick={signOut}>Sign out</button></>:<><p>Sign in with an account you already use. You can also keep exploring as a guest.</p><button className="provider-button" disabled={busy||!providers.google} onClick={()=>signIn('google')}>Continue with Google</button><button className="provider-button apple-provider" disabled={busy||!providers.apple} onClick={()=>signIn('apple')}>Continue with Apple</button>{loaded&&!providers.google&&!providers.apple&&<p className="auth-preview-note">Sign-in is not available in this preview yet. You can browse, plan and save on this device without it.</p>}<button className="text-button" onClick={()=>dialog.current?.close()}>Continue as guest →</button></>}{error&&<p className="error" role="alert">{error}</p>}</dialog></>;
}
