'use client';
import DimensionInput from './dimension-input';
import {length,unitQuantity,measurementText,normalizeUnits,unitPreferenceKey} from '../lib/units.mjs';
import MaterialChoice from './material-choice';
import AIProjectIntake from './ai-project-intake';
import RetailerSearch from './retailer-search';
import {useEffect,useId,useRef,useState} from 'react';
import {workshopDefaults,workshopModel,workshopOptions,workshopProgress,workshopTools,workshopSupplies,workshopShopping,workshopSteps,workshopScope,workshopSources} from '../lib/bookcase-workshop.mjs';
import {workshopArt} from '../lib/bookcase-workshop-art.mjs';
import {downloadProjectPDF} from '../lib/pdf-download.mjs';
import {designChanged,reviseWorkshop} from '../lib/workshop-revision.mjs';
import {workspaceStorage} from '../lib/account-storage.mjs';
import {merchants} from '../lib/catalog.mjs';
import {fmt} from '../lib/bookcase.mjs';

function download(content,type,name){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function initial(pack){const input=pack?.input||{...workshopDefaults,material:'choose'},options=workshopOptions(pack?.build?.options||{finish:pack?.finish?.system});let progress;try{progress=workshopProgress(workshopModel(input),options,pack?.build);}catch{progress={stage:'size',active:0,done:[]};}return {input,options,progress};}
function Retailers({id}){return <details className="bc-retailers"><summary>Find options ↗</summary>{merchants.map(m=><a href={`/go/${id}?merchant=${m.id}`} key={m.id} target="_blank" rel="noopener noreferrer sponsored">{m.name} ↗</a>)}</details>;}
function CutTable({d,units}){return <div className="bc-table-wrap"><table><caption>{d.melamine?`Core cut sizes · exclude ${length(d.edgeThickness,units)} front edging`:'Finished sizes'} · length × width × thickness</caption><thead><tr><th>Part</th><th>Qty</th><th>Size ({units==='imperial'?'inches':'mm'})</th></tr></thead><tbody>{d.parts.map(p=><tr key={p.id}><td><strong>{p.id}</strong> {p.name}</td><td>{p.qty}</td><td>{[p.length,p.width,p.thickness].map(n=>length(n,units)).join(' × ')}</td></tr>)}</tbody></table></div>;}

export default function BookcasePack({owned=[],onToggleOwned,saved=[],onSave,embedded=false,onCreate,record,onUpdate}){
 const pack=saved.find(p=>p.id==='bookcase')?.pack,seed=initial(pack),ns=useId(),focus=useRef(null);
 const [input,setInput]=useState(seed.input),[options,setOptions]=useState(seed.options),[progress,setProgress]=useState(seed.progress),[kitTab,setKitTab]=useState('wood'),[stock,setStock]=useState([]),[notice,setNotice]=useState(''),[showOwned,setShowOwned]=useState(false),[askOpen,setAskOpen]=useState(false),[pending,setPending]=useState(null),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState('');
 const [units,setUnits]=useState('imperial');
 useEffect(()=>{const read=()=>{try{setUnits(normalizeUnits(workspaceStorage.getItem(unitPreferenceKey)));}catch{}};read();window.addEventListener('kitsley-sync',read);return()=>window.removeEventListener('kitsley-sync',read);},[]);
 function changeUnits(value){setUnits(value);workspaceStorage.setItem(unitPreferenceKey,value);}
 const u=value=>measurementText(value,units);
 const editDialog=useRef(null);
 useEffect(()=>{if(pending)editDialog.current?.showModal();else editDialog.current?.close();},[pending]);
 const savedJSON=JSON.stringify(pack||null),lastSaved=useRef(savedJSON);
 useEffect(()=>{if(savedJSON!==lastSaved.current){lastSaved.current=savedJSON;const s=initial(pack);setInput(s.input);setOptions(s.options);setProgress(s.progress);}},[savedJSON]);
 useEffect(()=>{const read=()=>{try{setStock(JSON.parse(workspaceStorage.getItem('kitsley-sheet-stock')||'[]'));}catch{}};read();window.addEventListener('kitsley-stock',read);return()=>window.removeEventListener('kitsley-stock',read);},[]);
 let d,error='';try{d=workshopModel(input);}catch(e){error=e.message;}
 const stage=error?'size':progress.stage,steps=d?workshopSteps(d,options):[],active=progress.active||0,s=steps[active];
 const tools=workshopTools(options,d),missing=tools.filter(p=>!owned.includes(p.id)),rows=d?workshopShopping(d,options,owned,stock):[];
 function moveFocus(){requestAnimationFrame(()=>{focus.current?.focus({preventScroll:true});focus.current?.scrollIntoView({block:'start',behavior:'instant'});});}
 function save(nextProgress,patch={},confirmed=false){if(!d||['choose','melamine-unknown'].includes(d.material))return;if(!confirmed&&!onCreate&&designChanged(pack,patch.input||input,patch.options||options)){setPending({nextProgress,patch});return;}const nextOptions=patch.options||options,nextInput=patch.input||input,nextModel=workshopModel(nextInput),clean=reviseWorkshop(pack,nextInput,nextOptions,nextProgress),nextPack={...pack,version:1,input:{...Object.fromEntries(['width','height','depth','thickness','shelves'].map(k=>[k,Number(nextInput[k])])),material:nextModel.material,edgeThickness:nextModel.edgeThickness,materialNeeds:nextInput.materialNeeds||{}},reviewed:[],finish:{...pack?.finish,system:nextOptions.finish,surface:nextModel.material,method:'brush'},build:clean};setProgress(clean);setOptions(nextOptions);setNotice('Saved');lastSaved.current=JSON.stringify(nextPack);if(onCreate){onCreate(nextPack);return;}onSave?.({id:'bookcase'},{pack:nextPack,material:nextModel.material});}
 function go(next){if(d)save({...progress,stage:next});moveFocus();}
 function changeOption(key,value){setOptions({...options,[key]:value});setNotice('Choose “Use this design” to save your changes.');}
 function step(index){save({...progress,stage:'build',active:index});moveFocus();}
 function check(){save({...progress,review:(progress.review||[]).filter(i=>i!==active),done:progress.done.includes(active)?progress.done.filter(i=>i!==active):[...progress.done,active]});}
 async function output(kind){if(!d||exporting)return;setExporting(true);setExportError('');try{await downloadProjectPDF({kind,input,options,units,owned,stock,revision:progress.revision||1,revisedAt:progress.revisedAt,projectId:record?.id,stepAdvice:record?.stepAdvice,designKey:progress.key});}catch(e){setExportError(e.message);}finally{setExporting(false);}}
 function cancelEdit(){const old=initial(pack);setInput(old.input);setOptions(old.options);setProgress(old.progress);setPending(null);setNotice('Current dimensions kept.');}

 const art=(kind)=>d&&<div className="bc-art" dangerouslySetInnerHTML={{__html:workshopArt(d,kind,{...options,units},ns)}}/>;
 return <section className={'bookcase-workshop'+(embedded?' bc-embedded':'')}>
 {!embedded&&<a className="quiet-link" href="/library">← Library</a>}
 <header className={"bc-heading"+(stage!=='size'?' bc-heading-compact':'')}><div><p className="page-kicker">THE BOOKCASE PROJECT</p><h1>{stage==='size'?'A place for your favourite things.':'Your bookcase'}</h1><p>{stage==='size'?'Choose your material and size. One clear step at a time.':`${length(d.width,units)} W × ${length(d.height,units)} H × ${length(d.depth,units)} D · ${d.shelves} interior shelves`}</p>{stage!=='size'&&<button className="quiet-link" onClick={()=>go('size')}>Edit design</button>}</div>{!onCreate&&pack?.build&&<span className="small">Progress saves automatically · Revision {progress.revision||1}</span>}</header>
 <div className="bc-unit-choice"><label>Measurements <select aria-label="Measurement units" value={units} onChange={e=>changeUnits(e.target.value)}><option value="imperial">Feet & inches</option><option value="metric">Millimetres</option></select></label><small>Saved preference · changing units does not resize your project</small></div>
 <nav className="bc-stages" aria-label="Bookcase project stages">{[['size','Your design'],['kit','Tools & materials'],['build','Make it']].map(([id,label],i)=><button key={id} aria-current={stage===id?'step':undefined} disabled={(!d||['choose','melamine-unknown'].includes(d.material))&&id!=='size'} onClick={()=>{if(onCreate){setProgress(p=>({...p,stage:id}));moveFocus();}else go(id);}}><span>{i+1}</span>{label}</button>)}</nav>
 {pending&&<dialog ref={editDialog} className="bc-edit-dialog" aria-labelledby="bc-edit-title" onCancel={e=>{e.preventDefault();cancelEdit();}}><h2 id="bc-edit-title">Already started cutting or assembling?</h2><p>Changing this design will update your drawings, cut list and material quantities. Pieces already cut may no longer fit. Check them against the revised plan before continuing.</p><p>Completed steps will be marked for review. Your project, notes and paid access stay with this project.</p><div className="bc-dialog-actions"><button className="secondary" onClick={cancelEdit}>Keep current design</button><button className="primary" onClick={()=>{const p=pending;setPending(null);save(p.nextProgress,p.patch,true);moveFocus();}}>Apply design changes</button></div></dialog>}
 {progress.review?.length>0&&<p className="bc-revision-note" role="status">Design revised. {progress.review.length} previously completed {progress.review.length===1?'step needs':'steps need'} review against the new dimensions. Check any pieces already cut before continuing.</p>}
 {exporting&&<p role="status">Preparing your Kitsley PDF…</p>}{exportError&&<p role="alert" className="error">{exportError}</p>}
 {record&&onUpdate&&<section className="bc-assistant-entry"><div><strong>Kitsley, alongside your build</strong><p>Ask about this step, the tools you have, or a change you want to make.</p></div><button className="primary" aria-expanded={askOpen} onClick={()=>setAskOpen(v=>!v)}>{askOpen?'Close assistant':'Ask Kitsley'} {askOpen?'×':'↗'}</button></section>}
 {askOpen&&record&&onUpdate&&<div className="bc-assistant-panel"><AIProjectIntake key={record.id} embedded record={record} onUpdate={onUpdate} owned={owned} onDesignProposal={proposal=>{setInput(proposal.input);const nextOptions={...options,finish:proposal.input.material==='mdf'?'paint':proposal.input.material?.startsWith('melamine-')?'factory':options.finish==='factory'?'clear':options.finish};setOptions(nextOptions);setPending({nextProgress:{...progress,stage:'kit'},patch:{input:proposal.input,options:nextOptions}});}} onNavigate={url=>{window.location.href=url;}}/><button className="secondary" onClick={()=>{setAskOpen(false);go('size');}}>Review material, dimensions & finish →</button><p className="bc-micro">Answers are saved with the step. Design changes update drawings only after you review and apply them.</p></div>}
 <div ref={focus} tabIndex={-1} className="bc-focus">
 {stage==='size'&&<><div className="bc-design"><div className="bc-preview">{d?art('overview'):<div className="bc-invalid-art"><h2>Let’s check the size.</h2><p>{error}</p></div>}{d&&<div className="bc-facts"><span>{d.partCount} cut pieces</span><span>{d.melamine?'Factory finish':options.finish==='clear'?'Natural wood finish':'Painted finish'}</span><span>Fixed shelves</span></div>}</div>
 <form className="bc-size-form" onSubmit={e=>{e.preventDefault();if(d){save({...progress,stage:'kit'});moveFocus();}}}><h2>Make it fit your space</h2><p>Measure the space, leaving room around skirting and nearby doors.</p><MaterialChoice units={units} input={input} onChange={patch=>{setInput({...input,...patch});setOptions({...options,finish:!patch.material?options.finish:patch.material==='mdf'?'paint':patch.material?.startsWith('melamine-')?'factory':options.finish==='factory'?'clear':options.finish});setNotice('Material changed. Use this design to save.');}}/><div className="bc-dimensions">{[['width','Width',400,650],['height','Height',600,1000],['depth','Depth',250,350]].map(([key,label,min,max])=><DimensionInput key={key+units} label={label} value={input[key]} min={min} max={max} units={units} onChange={value=>{setInput({...input,[key]:value});setNotice('Size changed. Choose “Use this design” to save.');}}/>)}</div><div className="bc-form-row"><label>Panel thickness<select value={input.thickness} onChange={e=>{setInput({...input,thickness:Number(e.target.value)});}}>{![18,19].includes(Number(input.thickness))&&<option value={input.thickness}>{input.thickness} mm · previous design</option>}<option value="18">{length(18,units)} actual (18 mm)</option><option value="19">{length(19,units)} actual (19 mm)</option></select></label><label>Interior shelves<select value={input.shelves} onChange={e=>{setInput({...input,shelves:Number(e.target.value)});}}>{![1,2,3].includes(Number(input.shelves))&&<option value={input.shelves}>{input.shelves} · previous design</option>}{[1,2,3].map(n=><option key={n} value={n}>{n} {n===1?'shelf':'shelves'}</option>)}</select></label></div><p className="bc-micro">Measure the panel: “¾ inch” on the shelf label may have a different actual thickness.</p><fieldset className="bc-choices"><legend>How should it look?</legend>{(d?.melamine?[['factory','Keep the factory finish']]:d?.material==='mdf'?[['paint','Painted — seal MDF edges first']]:[['clear','Natural wood'],['paint','Painted']]).map(([id,label])=><label className={options.finish===id?'selected':''} key={id}><input type="radio" name={ns+'-finish'} checked={options.finish===id} onChange={()=>changeOption('finish',id)}/><span className={'bc-swatch '+id}/>{label}</label>)}</fieldset>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={!d||['choose','melamine-unknown'].includes(d.material)}>{onCreate?'Start this bookcase':'Use this design'} →</button>{error&&<button type="button" className="text-button" onClick={()=>{setInput({...workshopDefaults,material:'choose'});setProgress({stage:'size',active:0,done:[]});}}>Try the 600 × 900 mm starter size</button>}</form></div>
 <details className="bc-disclosure"><summary>What this build includes</summary><p>{workshopScope}</p><p>18 or 19 mm selected sheet board, fixed pocket-screwed shelves and a 6 mm plywood back. MDF is painted; melamine retains its factory finish with supplier-applied front edging. Confirm the board grade and intended shelf loads before building. Larger sizes, doors and wall-hung installations need a different design.</p><p>Expect several work sessions plus glue and finish curing. You’ll use a drill and a pocket-hole jig; a supplier can cut the panels.</p></details></>}
 {stage==='kit'&&d&&<><div className="bc-section-heading"><div><h2>Tools & materials</h2><p>Use your tools first. Buy only the gaps.</p></div><button className="secondary" onClick={()=>output('shopping')}>Download shopping list PDF ↓</button></div><div className="bc-kit-tabs" role="group" aria-label="Shopping sections">{[['wood','Cut pieces'],['tools',`Tools · ${missing.length} to source`],['supplies','Screws & finish']].map(([id,label])=><button aria-pressed={kitTab===id} key={id} onClick={()=>setKitTab(id)}>{label}</button>)}</div>
 {kitTab==='wood'&&<div className="bc-wood"><div>{art('parts')}</div><div><h3>Your cut list</h3><CutTable d={d} units={units}/><button className="quiet-link" onClick={()=>output('cut')}>Download cut list PDF ↓</button><button className="quiet-link" onClick={()=>output('drawings')}>Download drawings PDF ↓</button><fieldset className="bc-cutting"><legend>Who’s cutting the panels?</legend>{[['supplier','Have a supplier cut them'],['self','I’ll cut them myself']].map(([id,label])=><label key={id}><input type="radio" name={ns+'-cutting'} checked={options.cutting===id} onChange={()=>save({...progress,done:[],active:0},{options:{...options,cutting:id}})}/>{label}</label>)}</fieldset><p className="bc-micro">{options.cutting==='supplier'?'The saw, blade and guide are removed from your tool list. Ask the supplier for matching offcuts to test the joints.':'The saw, blade and guide are added to your tool list. Cut on the waste side; never subtract kerf from these finished sizes.'}</p>{stock.length>0&&<p className="bc-stock-note">{rows.filter(r=>r.id.startsWith('wood-')).reduce((n,r)=>n+(d.parts.find(p=>'wood-'+p.id===r.id).qty-r.qty),0)} pieces match your recorded plywood stock. Other materials are not automatically substituted. Download the shopping list to see the remaining cuts.</p>}<a className="quiet-link" href="/toolbox">Check my leftover materials →</a></div></div>}
 {kitTab==='tools'&&<><div className="bc-tool-summary"><p>{tools.length-missing.length} of {tools.length} already in your toolbox</p><label><input type="checkbox" checked={showOwned} onChange={e=>setShowOwned(e.target.checked)}/> Show owned tools</label></div><div className="bc-shopping">{(showOwned?tools:missing).map(p=><article key={p.id}><label><input type="checkbox" checked={owned.includes(p.id)} onChange={()=>onToggleOwned(p.id)}/><span><strong>{u(p.name)}</strong><small>{u(p.note)}</small><em>{owned.includes(p.id)?'In your toolbox':'Tick if you have this'}</em></span></label>{!owned.includes(p.id)&&<Retailers id={p.id}/>}</article>)}</div>{missing.length===0&&!showOwned&&<p className="bc-stock-note">Your toolbox covers this list. Check the condition and size of each tool before you begin.</p>}</>}
 {kitTab==='supplies'&&<><div className="bc-shopping bc-supplies">{workshopSupplies(d,options).map(p=><article key={p.id}><div><strong>{u(p.name)}</strong><span className="bc-quantity">{unitQuantity(p.qty,p.unit,units)}</span><small>{u(p.note)}</small></div><Retailers id={p.id}/></article>)}</div><label className="bc-wall">What will you anchor it to?<select value={options.wall} onChange={e=>save({...progress,active:0,done:[]},{options:{...options,wall:e.target.value}})}><option value="unknown">I need to check</option><option value="stud">Wood studs behind the wall</option><option value="masonry">Solid brick or concrete</option></select></label></>}
 {record&&onUpdate&&<details className="bc-disclosure"><summary>Compare prices for missing tools & materials</summary><RetailerSearch items={rows} work={record} onUpdate={onUpdate}/></details>}
 <p className="bc-micro">Retailer links may earn Kitsley a commission. Confirm the listed specification, price and stock at the store. Supplies are not removed just because a similar item is in your toolbox.</p><div className="bc-bottom"><button className="text-button" onClick={()=>go('size')}>← Adjust design</button><button className="primary" onClick={()=>go('build')}>Continue to step {active+1} →</button></div></>}
 {stage==='build'&&d&&s&&<><div className="bc-section-heading"><div><p className="page-kicker">STEP {active+1} OF {steps.length}</p><h2>{s.title}</h2></div><label className="bc-step-select"><span className="sr-only">Jump to a build step</span><select aria-label="Jump to a build step" value={active} onChange={e=>step(Number(e.target.value))}>{steps.map((x,i)=><option value={i} key={x.id}>{progress.review?.includes(i)?'Review · ':progress.done.includes(i)?'✓ ':''}{i+1}. {x.title}</option>)}</select></label></div><progress className="bc-progress" value={progress.done.length} max={steps.length} aria-label="Completed build steps"/><article className="bc-build-step">{art(s.visual)}<div className="bc-step-copy">{record?.stepAdvice?.[active]?.designKey===progress.key&&<aside className="bc-tailored"><strong>Your tailored guidance</strong><p>{record.stepAdvice[active].text}</p></aside>}<p className="bc-parts">{u(s.parts)}</p><p className="bc-spec">{u(s.spec)}</p><div className="bc-tools">{s.tools.map(t=><span key={t}>{u(t)}</span>)}</div><button className="bc-kit-link" onClick={()=>{setKitTab('tools');go('kit');}}>Tools & materials →</button><ol>{s.actions.map(a=><li key={a}>{u(a)}</li>)}</ol><p className="bc-check"><strong>Ready when</strong>{u(s.check)}</p><details className="bc-disclosure"><summary>A little more help</summary><p>{u(s.detail)}</p>{s.id==='back'&&<p className="bc-micro">Screw centres (across, up) from bottom-left, in {units==='imperial'?'inches':'mm'}: {d.backScrews.map(p=>`(${length(p.x,units)}, ${length(p.y,units)})`).join(' · ')}</p>}</details><label className="bc-complete"><input type="checkbox" checked={progress.done.includes(active)} onChange={check}/> {progress.review?.includes(active)?'I’ve checked this step against the revised design':'I’ve completed this step'}</label></div></article>{active===0&&<details className="bc-disclosure"><summary>Show my cut list</summary><CutTable d={d} units={units}/><button className="quiet-link" onClick={()=>output('cut')}>Download cut list PDF ↓</button></details>}<div className="bc-bottom"><button className="secondary" onClick={()=>active?step(active-1):go('kit')}>{active?'← Previous step':'← Tools & materials'}</button><span className="bc-micro" aria-live="polite">{progress.done.length} / {steps.length} complete</span>{active<steps.length-1?<button className="primary" onClick={()=>step(active+1)}>Next step →</button>:<button className="primary" onClick={()=>output('guide')}>Download illustrated guide PDF ↓</button>}</div>{progress.done.length===9&&<div className="bc-finished"><h3>Made by you.</h3><p>Your steps are saved. Keep the guide for future care and adjustments.</p></div>}<div className="bc-guide-download"><button className="quiet-link" onClick={()=>output('guide')}>Download illustrated guide PDF ↓</button><p className="bc-micro">Includes your current dimensions, numbered steps and illustrations.</p></div></>}
 </div><span className="sr-only" role="status">{notice}</span><details className="bc-disclosure bc-references"><summary>Sources & design limits</summary><p>{workshopScope}</p><p>The dimensions, screw schedule and diagrams form a Kitsley design. These sources support product use; they do not certify the finished bookcase.</p><ul>{workshopSources.map(([label,url])=><li key={url}><a href={url} target="_blank" rel="noreferrer">{label} ↗</a></li>)}</ul></details>
 </section>;
}
