'use client';
import {useEffect,useState} from 'react';
import {equipmentPolicy,equipmentLabel} from '../lib/equipment-details.mjs';
import {practiceHistory} from '../lib/project-learning.mjs';
import {workspaceStorage} from '../lib/account-storage.mjs';
import {equipmentKey,experienceKey,cleanCompanion,validEquipment,validExperience,experienceAreas,experienceLevels,relevantAreas,experienceSuggestion} from '../lib/companion-profile.mjs';

const read=key=>{try{return JSON.parse(workspaceStorage.getItem(key)||'[]');}catch{return [];}};
export function useCompanion(){
 const [data,setData]=useState({equipment:[],experience:[],practice:[]});
 function reload(){setData({equipment:read(equipmentKey).filter(validEquipment),experience:read(experienceKey).filter(validExperience),practice:practiceHistory(read('kitsley-conversations-v1'))});}
 useEffect(()=>{reload();window.addEventListener('kitsley-sync',reload);window.addEventListener('kitsley-profile',reload);return()=>{window.removeEventListener('kitsley-sync',reload);window.removeEventListener('kitsley-profile',reload);};},[]);
 function save(key,entry){const rows=read(key).filter(v=>v.id!==entry.id);workspaceStorage.setItem(key,JSON.stringify([...rows,entry]));window.dispatchEvent(new Event('kitsley-profile'));}
 function remove(id){workspaceStorage.setItem(equipmentKey,JSON.stringify(read(equipmentKey).filter(v=>v.id!==id)));window.dispatchEvent(new Event('kitsley-profile'));}
 return {...data,saveEquipment:entry=>{if(!validEquipment(entry))throw Error(equipmentPolicy(entry.toolId,entry).modelRelevant?'Add a make or model for this equipment.':'Add a useful type, size or accessory detail.');if(read(equipmentKey).filter(v=>v.id!==entry.id).length>=100)throw Error('Your kit has 100 equipment records. Edit an existing record first.');save(equipmentKey,entry);},removeEquipment:remove,setExperience:(id,level)=>save(experienceKey,{id,level,source:'user',updatedAt:new Date().toISOString()}),context:owned=>cleanCompanion(data.equipment,data.experience,owned,data.practice)};
}
export function EquipmentDetails({toolId,name}){
 const profile=useCompanion(),items=profile.equipment.filter(t=>t.toolId===toolId),[editing,setEditing]=useState(null),[message,setMessage]=useState('');
 const blank={make:'',model:'',variant:'',accessories:''},policy=equipmentPolicy(toolId,editing||items[0]||{});
 const identityFields=[['make','Make / brand',100,'Manufacturer on the label'],['model','Exact model / product code',100,'Copy the model or product code']];
 const renderFields=fields=>fields.map(([key,label,max,placeholder])=><label key={key}>{label}<input value={editing[key]} maxLength={max} placeholder={placeholder} onChange={e=>setEditing({...editing,[key]:e.target.value})}/></label>);
 return <details className="equipment-details"><summary>{items.length?items.map(equipmentLabel).join(' · '):policy.summary}</summary>
 <p className="small">{policy.reason} These details follow you across projects.</p>
 {items.map(t=><div className="equipment-saved" key={t.id}><span><strong>{equipmentLabel(t)}</strong>{(t.make||t.model)&&t.variant&&<small>{t.variant}</small>}{t.accessories&&t.accessories!==equipmentLabel(t)&&<small>{t.accessories}</small>}</span><button type="button" className="quiet-link" onClick={()=>{setEditing(t);setMessage('');}}>Edit</button><button type="button" className="quiet-link" aria-label={'Remove details for '+equipmentLabel(t)} onClick={()=>{profile.removeEquipment(t.id);setEditing(null);setMessage('Details removed.');}}>×</button></div>)}
 {editing?<div className="equipment-form"><div className="profile-fields">
 {policy.modelRelevant&&renderFields(identityFields)}
 {renderFields([['variant',policy.modelRelevant?'Type / regional variant':'Type & size',100,policy.modelRelevant?'e.g. pneumatic, 120 V or regional version':policy.typeHint],['accessories',policy.modelRelevant?'Accessories & sizes':'Useful details (optional)',400,policy.modelRelevant?'e.g. tip code, blade, bit or sanding disc':'e.g. extra tips, blades or capacity']])}
 </div>{!policy.modelRelevant&&<details><summary>Brand or model, if useful (optional)</summary><div className="profile-fields">{renderFields(identityFields)}</div></details>}
 <div className="profile-actions"><button type="button" className="secondary" onClick={()=>{try{profile.saveEquipment({...editing,id:editing.id||crypto.randomUUID(),toolId,source:'user',updatedAt:new Date().toISOString()});setEditing(null);setMessage('Details saved.');}catch(e){setMessage(e.message);}}}>Save details</button><button type="button" className="quiet-link" onClick={()=>setEditing(null)}>Cancel</button></div></div>:<button type="button" className="quiet-link" onClick={()=>{setEditing(blank);setMessage('');}}>{items.length?'＋ Add another '+name.toLowerCase():'Add details'}</button>}
 {policy.modelRelevant&&<p className="small">Kitsley checks matching manufacturer instructions before giving model-specific settings or compatibility advice.</p>}{message&&<p role="status" className="small">{message}</p>}</details>;
}
export function ExperienceFields({profile,areas=experienceAreas.map(a=>a[0])}){return <div className="profile-fields">{experienceAreas.filter(([id])=>areas.includes(id)).map(([id,label])=><label key={id}>{label}<select value={profile.experience.find(v=>v.id===id)?.level||'unknown'} onChange={e=>profile.setExperience(id,e.target.value)}>{experienceLevels.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>)}</div>;}
export function ExperienceProfile({record,expanded=false}){const profile=useCompanion();return <details className="experience-profile" open={expanded||undefined}><summary>My DIY experience</summary><p>Set each area separately. Kitsley uses this to adjust explanations across your projects. You can change it any time.</p><ExperienceFields profile={profile} areas={record?relevantAreas(record):undefined}/><p className="small">Changes save automatically. Self-reported experience doesn’t replace qualifications or task safety checks.</p>{profile.practice.length>0&&<div className="practice-history"><h4>Practice from completed projects</h4><ul>{profile.practice.map(p=><li key={p.id}>{experienceAreas.find(a=>a[0]===p.id)[1]} · {p.projects} {p.projects===1?'project':'projects'} you reported completing</li>)}</ul><p className="small">These records come from your completion reviews. You control your level above.</p></div>}</details>;}
export function ExperienceSuggestion({message}){const profile=useCompanion(),[dismissed,setDismissed]=useState(''),suggestion=experienceSuggestion(message);if(!suggestion||dismissed===message||profile.experience.some(v=>v.id===suggestion.id&&v.level===suggestion.level))return null;return <aside className="experience-suggestion"><p>Remember “{experienceLevels.find(v=>v[0]===suggestion.level)[1]}” for {experienceAreas.find(v=>v[0]===suggestion.id)[1].toLowerCase()} in future projects?</p><button className="secondary" onClick={()=>{profile.setExperience(suggestion.id,suggestion.level);setDismissed(message);}}>Save my experience</button><button className="quiet-link" onClick={()=>setDismissed(message)}>Not now</button></aside>;}
