'use client';
import {contentSources} from '../lib/content-sources.mjs';
import {contentFor} from '../lib/project-content.mjs';
import {guideTypeLabel,categories} from '../lib/library.mjs';
import {guides} from '../lib/guides.mjs';
import {WorkspaceIcon} from './dashboard';
import PackKit from './pack-kit';
import {readiness} from '../lib/readiness.mjs';
export default function GuidePreview({entry,owned,onToggleOwned,onStart,onBack,onSave,isSaved}){
 const content=contentFor(entry.id);let kit={items:[],blocked:true};try{kit=readiness(entry,owned,entry.id==='planter'?'solid':'plywood');}catch{}
 const steps=content?.steps||guides[entry.id]||[];
 return <section className="guide-preview"><a className="quiet-link" href="/library" onClick={e=>{e.preventDefault();onBack();}}>← Project library</a><div className="guide-preview-heading"><span className="guide-topic-icon"><WorkspaceIcon name={entry.category} size={26}/></span><p className="page-kicker">{categories.find(c=>c.id===entry.category)?.name} · {guideTypeLabel(entry)}</p><h1>{entry.title}</h1><p className="intro">{entry.summary}</p><div className="guide-action-row"><button className="primary" onClick={onStart}>Make this my project →</button><button className="secondary" aria-pressed={isSaved} onClick={onSave}>{isSaved?'✓ Guide saved':'Save guide'}</button></div><p className="small">Free reference guide. Start a project for advice based on your situation.</p></div><section className="guide-overview"><h2>Start here</h2><p>{content?.scope||entry.observe}</p>{entry.next&&!content&&<p>{entry.next}</p>}{(content?.stop||entry.stop)&&<p className="context-note">{content?.stop||entry.stop}</p>}</section>{steps.length>0&&<section className="guide-outline"><h2>What the guide covers</h2>{steps.map((s,i)=><details key={s.title}><summary><span>{String(i+1).padStart(2,'0')}</span>{s.title}</summary><p>{s.action||s.body}</p>{(s.check||s.tip)&&<p className="small">{s.check||s.tip}</p>}</details>)}</section>}{!kit.blocked&&kit.items.length>0&&<details className="guide-kit"><summary>Suggested tools <span>{kit.covered} of {kit.items.length} owned</span></summary><PackKit items={kit.items} owned={owned} onToggleOwned={onToggleOwned} scope={kit.scope}/></details>}<details className="guide-sources"><summary>Sources & guide limits</summary><p className="small">Follow the instructions for your exact product and local requirements.</p>{content?.sources.map(id=><p key={id}><a href={contentSources[id].url} target="_blank" rel="noreferrer">{contentSources[id].title} ↗</a></p>)}{entry.source&&<p><a href={entry.source[1]} target="_blank" rel="noreferrer">{entry.source[0]} ↗</a></p>}{!content?.sources.length&&!entry.source&&<p className="small">This is a planning outline. Confirm the method and parts with the product manufacturer before starting.</p>}</details><div className="guide-end"><p>Want help applying this to your home?</p><button className="primary" onClick={onStart}>Start with this guide →</button></div></section>;
}
