'use client';
import {length,measurementText} from '../lib/units.mjs';
import {useState} from 'react';
const labels={'melamine-unknown':'Melamine-faced board',plywood:'Plywood',mdf:'MDF','melamine-mdf':'Melamine · MDF core','melamine-particleboard':'Melamine · particleboard core'};
export default function MaterialChoice({input,onChange,units='metric'}){
 const [help,setHelp]=useState(false),[answers,setAnswers]=useState(input.materialNeeds||{});
 const question=!answers.place?'place':!answers.contents?'contents':!answers.look?'look':null;
 const questions={place:['Where will it live?',[['dry','A dry indoor room'],['damp','A damp area or outdoors']]],contents:['What will it hold?',[['display','Decorations and light items'],['books','Books'],['heavy','Heavy equipment or unusual loads']]],look:['Which finish do you prefer?',[['wood','Visible wood grain'],['paint','A smooth painted colour'],['ready','A ready-finished surface']]]};
 const recommended=answers.look==='paint'?'mdf':answers.look==='ready'?'melamine-unknown':'plywood';
 const unsuitable=answers.place==='damp'||answers.contents==='heavy';
 const select=material=>onChange({material,edgeThickness:material.startsWith('melamine-')?1:0,materialNeeds:answers});
 return <section className="bc-material"><div className="bc-section-heading"><h3>What will you build with?</h3><button type="button" className="quiet-link" onClick={()=>setHelp(v=>!v)}>{help?'Close help':'Help me choose'}</button></div>
 {help&&<div className="bc-material-help">{question?<><strong>{questions[question][0]}</strong><div className="bc-material-buttons">{questions[question][1].map(([value,label])=><button type="button" className="secondary" key={value} onClick={()=>{const next={...answers,[question]:value};setAnswers(next);onChange({materialNeeds:next});}}>{label}</button>)}</div></>:<><strong>{unsuitable?'This starter design needs a different specification':`Consider ${labels[recommended]}`}</strong><p>{unsuitable?'This guide is for a small bookcase in a dry indoor room. Damp exposure or unusual loads need a design and material review before cutting.':recommended==='mdf'?'MDF offers a smooth painted finish. Its edges need sealing, it is heavy to handle, and screw holes need careful preparation.':recommended==='plywood'?'Plywood keeps a natural wood appearance and can also be painted. Face quality and exposed layered edges affect the finished look.':'Melamine gives you a factory-finished surface without painting. It needs protected edges and a confirmed core; take care to avoid chipping when cutting.'}</p>{answers.contents==='books'&&!unsuitable&&<p>For books, have the supplier check your selected board grade and shelf span for the intended load. This guide has no tested load rating.</p>}{!unsuitable&&<button type="button" className="primary" onClick={()=>{select(recommended);setHelp(false);}}>Use this material →</button>}<button type="button" className="quiet-link" onClick={()=>{setAnswers({});onChange({materialNeeds:{}});}}>Start questions again</button></>}</div>}
 <div className="bc-material-buttons">{[['plywood','Plywood','Visible wood; clear or painted'],['mdf','MDF','Smooth paint finish; seal edges'],['melamine-unknown','Melamine-faced board','Ready-finished; choose the core']].map(([id,label,detail])=><button type="button" className="secondary" aria-pressed={id.startsWith('melamine')?input.material?.startsWith('melamine'):input.material===id} key={id} onClick={()=>select(id)}><strong>{label}</strong><small>{detail}</small></button>)}</div>
 {input.material?.startsWith('melamine')&&<div className="bc-form-row"><label>What is the core?<select value={input.material} onChange={e=>select(e.target.value)}><option value="melamine-unknown" disabled>Choose the supplier’s core</option><option value="melamine-particleboard">Particleboard / chipboard</option><option value="melamine-mdf">MDF</option></select><small>Check the supplier’s label. Melamine describes the surface, not the core.</small></label><label>Finished front edging<select value={input.edgeThickness??1} onChange={e=>onChange({edgeThickness:Number(e.target.value)})}>{[0.5,1,2].map(n=><option key={n} value={n}>{length(n,units)} · supplier applied</option>)}</select><small>Core cut sizes allow for this thickness.</small></label></div>}
 <p className="bc-micro">{input.material==='choose'?'Choose a material to continue.':'Selected: '+(labels[input.material]||'Plywood')+measurementText('. The back remains 6 mm plywood.',units)}</p></section>;
}
