'use client';
import {workspaceStorage} from '../lib/account-storage.mjs';
import {useState,useEffect} from 'react';
export default function MaterialStock({expanded=false}){
 const [stock,setStock]=useState([]),[error,setError]=useState('');
 useEffect(()=>{const read=()=>{try{const data=JSON.parse(workspaceStorage.getItem('kitsley-sheet-stock')||'[]');if(Array.isArray(data))setStock(data);}catch{setError('Material stock could not be loaded.');}};read();window.addEventListener('kitsley-stock',read);return()=>window.removeEventListener('kitsley-stock',read);},[]);
 function save(next){try{workspaceStorage.setItem('kitsley-sheet-stock',JSON.stringify(next));setStock(next);window.dispatchEvent(new Event('kitsley-stock'));setError('');}catch{setError('Material stock could not be saved.');}}
 function add(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget)),item={id:crypto.randomUUID(),name:data.name.trim(),sound:data.sound==='on',...Object.fromEntries(['length','width','thickness','qty'].map(k=>[k,Number(data[k])]))};if(!item.name||!item.sound||![item.length,item.width,item.thickness,item.qty].every(n=>Number.isFinite(n)&&n>0)||!Number.isInteger(item.qty)||item.qty>100){setError('Enter positive dimensions, a whole quantity up to 100, and confirm the plywood condition.');return;}save([...stock,item]);e.currentTarget.reset();}
 return <details className="project-detail" open={expanded||undefined}><summary>My materials · {stock.reduce((n,s)=>n+Number(s.qty||0),0)} plywood pieces recorded</summary><p>Record sound plywood sheets and offcuts. Bookcase packs check these dimensions before listing pieces to source.</p><form className="stock-form" onSubmit={add}><label>Label<input name="name" required maxLength="80" placeholder="Plywood in the garage"/></label>{[['length','Along-grain length (mm)'],['width','Width (mm)'],['thickness','Thickness (mm)'],['qty','Quantity']].map(([key,label])=><label key={key}>{label}<input name={key} required type="number" min="1" max={key==='qty'?100:10000} step="1" defaultValue={key==='qty'?1:undefined}/></label>)}<label className="stock-condition"><input name="sound" type="checkbox" required/>Dry, flat plywood without visible damage</label><button className="secondary">Add material</button></form>{stock.map(s=><article className="stock-row" key={s.id}><span><strong>{s.name}</strong><br/>{s.qty} × {s.length} × {s.width} × {s.thickness} mm</span><button className="text-button" onClick={()=>save(stock.filter(x=>x.id!==s.id))}>Remove <span className="sr-only">{s.name}</span></button></article>)}<p className="small">Fit checks allocate one stock piece per cut part within a project. They do not reserve stock across projects or optimize sheet cutting. Always confirm grain, kerf and material suitability.</p>{error&&<p role="alert">{error}</p>}</details>;
}
