'use client';
import PackKit from './pack-kit';
import ProjectInstructions from './project-instructions';
import {contentLabel,contentFor} from '../lib/project-content.mjs';
import {readiness} from '../lib/readiness.mjs';
import {useState} from 'react';
import {packLibrary,findPacks} from '../lib/pack-library.mjs';
import {library} from '../lib/library.mjs';
const title=id=>library.find(p=>p.id===id)?.title||id;
export default function PackLibrary({id,onNavigate,saved,onSave,onGuide,owned,onToggleOwned}){const [query,setQuery]=useState(''),[category,setCategory]=useState('all'),[onlySaved,setOnlySaved]=useState(false);const p=packLibrary.find(p=>p.id===id),work=saved.find(s=>s.id===id)?.planningPack||{};
 function update(patch){onSave({id:p.id},{planningPack:{...work,...patch}});}
 const kit=p?readiness(library.find(g=>g.id===p.id),owned,p.id==='planter'?'solid':'plywood'):null;
 if(p)return <section className="inner-page workbook-page"><button className="text-button" onClick={()=>onNavigate('/packs')}>← All project packs</button><span className="eyebrow">{p.category} · {contentLabel(p.id)}</span><h1>{title(p.id)}</h1><p className="intro">{p.summary}</p><p className="pack-caution">{contentFor(p.id)?.scope}</p><details className="workbook-section"><summary>1. Your project details</summary><div className="finish-fields">{p.questions.map((q,i)=><label key={q}>{q}<textarea rows="3" maxLength="1500" value={work.answers?.[i]||''} onChange={e=>update({answers:{...work.answers,[i]:e.target.value}})}/></label>)}</div><p className="small">Answers and review checks save automatically in My projects on this browser.</p></details><details className="workbook-section"><summary>2. Your tools & shopping list</summary><PackKit items={kit.items} owned={owned} onToggleOwned={onToggleOwned} scope={kit.scope}/><details className="finish-section"><summary>Materials and specialist tools to confirm</summary><div className="offer-grid"><section><h2>Materials to specify</h2><ul>{p.materials.map(m=><li key={m}>{m}</li>)}</ul></section><section><h2>Tools to review</h2><ul>{p.tools.map(t=><li key={t}>{t}</li>)}</ul></section></div></details></details><ProjectInstructions key={p.id} record={{...work,guideId:p.id,answers:work.answers||{}}} onUpdate={update}/><details className="workbook-section"><summary>4. Review & save money</summary><div className="pack-kit">{p.checks.map((c,i)=><label key={c}><input type="checkbox" checked={work.checked?.includes(i)||false} onChange={()=>update({checked:work.checked?.includes(i)?work.checked.filter(x=>x!==i):[...(work.checked||[]),i]})}/>{c}</label>)}</div><section className="finish-section"><h2>Save a Buck</h2><p>{p.savings}</p></section><label className="tool-search-label">Further customization request<textarea rows="3" maxLength="2000" value={work.request||''} onChange={e=>update({request:e.target.value})} placeholder="Describe preferences, constraints or changes for review…"/></label><p className="small">Saved as a brief. Live AI customization is not connected.</p></details><button className="secondary" onClick={()=>onGuide({id:p.id})}>Open related guide and toolbox check →</button></section>;
 const results=findPacks(query,category).filter(p=>!onlySaved||saved.some(s=>s.id===p.id));return <section className="inner-page packs-hub"><span className="eyebrow">CHOOSE A PROJECT · MAKE IT YOURS</span><h1>Project packs</h1><p className="intro">Find your next job. Check your kit. Make a plan that fits your home.</p><div className="finish-fields"><label>Find a project<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try shelves, garden, paint or wall…"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{[...new Set(packLibrary.map(p=>p.category))].map(c=><option key={c}>{c}</option>)}</select></label></div><div className="pack-results-bar"><p role="status">{results.length} projects · practical instructions, checks and references</p><label><input type="checkbox" checked={onlySaved} onChange={e=>setOnlySaved(e.target.checked)}/>Saved only</label></div><div className="packs-grid">{results.map(p=><button className="library-card" key={p.id} onClick={()=>onNavigate('/packs/'+p.id)}><span className="entry-type">{contentLabel(p.id)}</span><h2>{title(p.id)}</h2><p>{p.summary}</p><span className="pack-category">{p.category}<b aria-hidden="true">→</b></span></button>)}</div>{!results.length&&<p>No projects match these filters. Try another term or clear your filters.</p>}<button className="text-button" onClick={()=>{setQuery('');setCategory('all');setOnlySaved(false);}}>Clear filters</button></section>;
}
