'use client';
import {useEffect,useState} from 'react';
import {plans} from '../lib/plans.mjs';
import {syncNow} from '../lib/account-storage.mjs';
import Account from './account';
import EmbeddedCheckout from './embedded-checkout';
export default function PaidOffer({onExplore}){
 const [checkout,setCheckout]=useState(null),[pendingPlan,setPendingPlan]=useState('');
 const [state,setState]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[projectId,setProjectId]=useState('');
 async function refresh(){try{const r=await fetch('/api/billing',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setState(d);}catch(e){setError(e.message);}}
 useEffect(()=>{setProjectId(new URLSearchParams(window.location.search).get('project')||'');refresh();},[]);
 async function purchase(plan){setPendingPlan(plan);setBusy(true);setError('');try{await syncNow();const r=await fetch('/api/billing/'+(plan==='portal'?'portal':'checkout'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan,projectId})}),d=await r.json();if(!r.ok)throw Error(d.error);if(plan==='portal'){window.location.assign(d.url);}else{setCheckout({session:d,plan});setBusy(false);}}catch(e){setError(e.message);setBusy(false);}}
 return <section className="inner-page offer-page">{checkout&&<EmbeddedCheckout session={checkout.session} plan={checkout.plan} projectId={projectId} onClose={()=>{setCheckout(null);refresh();}} onActivated={refresh}/>}<span className="eyebrow">HELP THAT FITS THE JOB</span><h1>Start free. Build with a plan.</h1><p className="intro">Get useful advice first. When you’re ready, turn your idea into a project you can follow.</p>
 {!state&&<p role="status">Checking your plan…</p>}{state&&!state.ready&&<p className="notice">Launch pricing preview. Checkout is not open yet; no payment will be taken.</p>}
 {state?.testMode&&<p className="notice">Sandbox checkout — available to all signed-in accounts. Test payments only; no real charges.</p>}
 {state?.ready&&new URLSearchParams(typeof window==='undefined'?'':window.location.search).get('checkout')==='returned'&&<div className="notice"><p>Your confirmed access is shown below. If your new plan is missing, refresh its status.</p><button className="secondary" onClick={refresh}>Refresh plan status</button></div>}
 {state?.signedIn===false&&<div className="offer-sign-in"><p>Sign in to keep your allowance, purchases and projects together across devices.</p><Account/></div>}
 <div className="offer-grid"><article className="offer-card"><span className="eyebrow">FIND YOUR STARTING POINT</span><h2>Free</h2><div className="offer-price">C$0</div><p>Work out where to start.</p><ul><li>Free guided project setup</li><li>3 useful AI replies per project</li><li>Up to 3 projects each calendar month</li><li>Project library and your toolbox</li><li>Saved work and urgent safety guidance</li></ul><button className="secondary" onClick={onExplore}>Start free →</button></article>
 {['project-pass','plus'].map(id=>{const p=plans[id],active=state?.grants?.find(g=>g.plan===id&&(id==='plus'||g.project_id===projectId));return <article className="offer-card" key={id}><span className="eyebrow">{id==='plus'?'FOR REGULAR DIYERS':'ONE JOB. ONE PAYMENT.'}</span><h2>{p.name}</h2><div className="offer-price">C${p.cents/100}<span> / {id==='plus'?'month':'project'}</span></div><p>{id==='plus'?'3 projects per billing month. Cancel renewal any time.':'One defined project, with 30 days of help. No automatic renewal.'}</p><ul><li>{p.answers} AI follow-up replies {id==='plus'?'per billing month':'over 30 days'}</li><li>A tailored plan, steps and tool checks</li><li>Drawings for supported designs</li><li>{p.searches} retailer comparisons {id==='plus'?'per billing month':'over 30 days'}</li><li>Keep reading saved work after paid access ends</li></ul>{active?<p className="notice">Active until {new Date(active.ends_at).toLocaleDateString()}</p>:<button className="primary" disabled={busy||!state?.ready||!state.signedIn||(id==='project-pass'&&!projectId)} onClick={()=>purchase(id)}>{busy&&pendingPlan===id?'Opening checkout…':id==='plus'?'Subscribe to Plus →':'Get this Project Pass →'}</button>}{error&&pendingPlan===id&&<p className="error" role="alert">{error}</p>}{id==='project-pass'&&!projectId&&<p className="small"><a href="/projects">Choose a project →</a> to test a Project Pass for that job.</p>}</article>;})}</div>
 <p className="small">Prices in CAD, before applicable tax. Allowances do not roll over. Plus covers up to three distinct projects used in each billing month, including projects you resume. A Project Pass stays with the selected project. No automatic usage overage charges.</p>
 <p className="small">Drawings currently support selected designs, including the bookcase. Check your project’s available outputs before buying; generated diagrams are not engineer-approved construction plans. Retailer comparisons use published listings, not guaranteed branch stock.</p>
 {state?.grants?.length>0&&<section className="project-detail"><h2>Your paid access</h2>{state.grants.map(g=>{const u=state.usage.filter(x=>x.bucket===g.id);return <p key={g.id}>{plans[g.plan].name}: {u.filter(x=>x.feature==='answer').length} / {plans[g.plan].answers} replies · {u.filter(x=>x.feature==='search').length} / {plans[g.plan].searches} comparisons · until {new Date(g.ends_at).toLocaleDateString()}{g.project_id&&<> · <a href={'/project/'+encodeURIComponent(g.project_id)}>Open project</a></>}</p>;})}</section>}
 {state?.portal&&<button className="secondary" disabled={busy} onClick={()=>purchase('portal')}>Manage billing & cancellation →</button>}{error&&(!pendingPlan||pendingPlan==='portal')&&<p className="error" role="alert">{error}</p>}
 <section className="free-promise"><h2>Useful before you pay.</h2><p>Your free replies should help you make a decision, not just collect details. Upgrade when you want a tailored plan and ongoing help. Urgent safety guidance stays free.</p><button className="secondary" onClick={onExplore}>Start a free project →</button></section></section>;
}
