'use client';
import {useState,useEffect} from 'react';
import {offers,offerVersion} from '../lib/project-experience.mjs';
export default function PaidOffer({onExplore}){
 const [busy,setBusy]=useState(false),[choice,setChoice]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{try{setChoice(localStorage.getItem('kitsley-offer-choice-'+offerVersion)||'');}catch{}},[]);
 async function vote(offerId){setBusy(true);setError('');setMessage('');try{let clientId;try{clientId=localStorage.getItem('kitsley-interest-id');if(!clientId){clientId=crypto.randomUUID();localStorage.setItem('kitsley-interest-id',clientId);}}catch{throw new Error('Browser storage is needed to keep one preference per browser. You can still explore the free preview.');}const r=await fetch('/api/offer-interest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({offerId,clientId})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not save your preference.');setChoice(offerId);try{localStorage.setItem('kitsley-offer-choice-'+offerVersion,offerId);}catch{}setMessage('Preference recorded. This is research only: no purchase, subscription or payment.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="inner-page offer-page"><span className="eyebrow">HELP US SHAPE KITSLEY</span><h1>Finish the job. Spend wisely.</h1><p className="intro">Would you pay for a plan that fits your home, useful help while you work, and less time comparing what to buy?</p><div className="offer-disclosure"><strong>Pricing research — nothing is for sale yet.</strong><p>These are proposed CAD prices and allowances. AI discovery and web-sourced retailer search work now. Subscription checkout is not connected. Custom drawings currently support selected designs only.</p></div>
 <div className="offer-grid">{offers.map(o=><article className="offer-card" key={o.id}><span className="eyebrow">{o.id==='project-pass'?'ONE JOB AT A TIME':'FOR REGULAR DIYERS'}</span><h2>{o.name}</h2><p>{o.description}</p><div className="offer-price">C${o.price}<span> / {o.unit}</span></div><p className="small">Proposed price before applicable tax.</p><ul><li>AI help tailored to your project and tools</li><li>Follow-up help as you work</li><li>Custom drawings and illustrated steps for supported projects</li><li>Save a Buck: compatible purchase and rental comparisons</li><li>Saved project decisions, notes and progress</li></ul><p>{o.allowance}</p><button className="primary" disabled={busy} aria-pressed={choice===o.id} onClick={()=>vote(o.id)}>{choice===o.id?'✓ My preferred offer':`I’d consider ${o.name}`}</button></article>)}</div>
 <p className="small">Selecting an offer sends an anonymous preference and a random browser identifier to this app’s server. No email or payment details are requested. Changing your selection replaces your previous preference.</p><button className="text-button" disabled={busy} aria-pressed={choice==='none'} onClick={()=>vote('none')}>{choice==='none'?'✓ I prefer the free tools':'Neither — I prefer the free tools'}</button>{message&&<p className="notice" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}
 <section className="free-promise"><h2>Useful before you pay.</h2><p>Keep reading guides, checking your toolbox, saving progress and comparing prices you enter. Urgent safety guidance stays free. Proposed paid features add tailored assistance and comparison work; they do not replace the free foundation.</p><button className="secondary" onClick={onExplore}>Try a free project workspace →</button></section></section>;
}
