'use client';
import {useEffect,useState} from 'react';
import {plans} from '../lib/plans.mjs';
import {projectTitle} from '../lib/journey.mjs';
import {syncNow} from '../lib/account-storage.mjs';
import Account from './account';
import EmbeddedCheckout from './embedded-checkout';
export default function PaidOffer({onExplore,onNavigate,conversations=[]}){
 const [checkout,setCheckout]=useState(null),[pendingPlan,setPendingPlan]=useState(''),[state,setState]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[projectId,setProjectId]=useState('');
 async function refresh(){setError('');try{const r=await fetch('/api/billing',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setState(d);}catch(e){setError(e.message);}}
 useEffect(()=>{setProjectId(new URLSearchParams(window.location.search).get('project')||'');refresh();},[]);
 function selectProject(id){setProjectId(id);const url='/offers'+(id?'?project='+encodeURIComponent(id):'');window.history.replaceState({},'',url);}
 async function purchase(plan){setPendingPlan(plan);setBusy(true);setError('');try{await syncNow();const r=await fetch('/api/billing/'+(plan==='portal'?'portal':'checkout'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan,projectId})}),d=await r.json();if(!r.ok)throw Error(d.error);if(plan==='portal')window.location.assign(d.url);else setCheckout({session:d,plan});}catch(e){setError(e.message);}finally{setBusy(false);}}
 const back=()=>projectId?onNavigate('/project/'+projectId):onExplore();
 return <section className="journey-page pricing-page">{checkout&&<EmbeddedCheckout session={checkout.session} plan={checkout.plan} projectId={projectId} onClose={()=>{setCheckout(null);refresh();}} onActivated={refresh}/>}<button className="quiet-link" onClick={back}>← {projectId?'Back to my project':'Start a project'}</button><div className="pricing-heading"><p className="page-kicker">HELP WHEN YOU NEED IT</p><h1>A plan for the job ahead.</h1><p>Keep your free advice. Choose more help when you’re ready to continue.</p></div>
 {state?.testMode&&<p className="test-mode-note">Test checkout · no real charges</p>}
 {!state&&<p role="status">Checking your plan…</p>}{state&&!state.ready&&<p className="context-note">Checkout is temporarily unavailable. You can still use free guides and saved advice.</p>}
 {state?.signedIn===false&&<div className="pricing-signin"><p>Sign in to choose a plan and keep it with your account.</p><Account triggerLabel="Sign in to choose a plan"/></div>}
 {state?.grants?.some(g=>g.plan==='plus')&&<p className="context-note">Your Plus plan is already active. Use its included help first; a Project Pass is a separate purchase for help beyond that allowance.</p>}<div className="pricing-project"><label htmlFor="plan-project">Your project</label><select id="plan-project" value={projectId} onChange={e=>selectProject(e.target.value)}><option value="">Choose a project for a Project Pass</option>{conversations.filter(r=>!r.archived||r.id===projectId).map(r=><option key={r.id} value={r.id}>{projectTitle(r)}</option>)}</select>{!projectId&&<button className="quiet-link" onClick={onExplore}>Or start a new project →</button>}</div>
 <div className="pricing-options">{['project-pass','plus'].map(id=>{const p=plans[id],active=state?.grants?.find(g=>g.plan===id&&(id==='plus'||g.project_id===projectId));return <article key={id} className={'pricing-option '+(id==='project-pass'?'single-project-option':'')}><span className="page-kicker">{id==='plus'?'FOR YOUR NEXT FEW PROJECTS':'FOR THIS ONE JOB'}</span><h2>{p.name}</h2><p className="pricing-amount">C${p.cents/100}<span>{id==='plus'?' / month':' once'}</span></p><p>{id==='plus'?'Help with up to 3 projects each billing month.':'30 days of help with one defined project.'}</p><ul><li>Guidance tailored to your project</li><li>Tool checks and retailer comparisons</li><li>Drawings for supported designs</li></ul><div className="pricing-cta">{active?<><p className="plan-active">Active until {new Date(active.ends_at).toLocaleDateString()}</p><button className="primary" onClick={back}>{projectId?'Continue my project →':'Start a project →'}</button></>:<button className="primary" disabled={busy||!state?.ready||!state?.signedIn||id==='project-pass'&&!projectId} onClick={()=>purchase(id)}>{busy&&pendingPlan===id?'Opening checkout…':id==='plus'?'Choose Plus →':'Choose Project Pass →'}</button>}<p className="small">{id==='plus'?'Renews monthly. Cancel renewal any time.':'One payment. No automatic renewal.'}</p></div>{error&&pendingPlan===id&&<p role="alert" className="error">{error}</p>}<details className="plan-inclusions"><summary>What’s included</summary><ul><li>{p.answers} AI follow-up replies {id==='plus'?'per billing month':'over 30 days'}</li><li>{p.searches} retailer comparisons {id==='plus'?'per billing month':'over 30 days'}</li><li>{id==='plus'?'Up to 3 distinct projects, including resumed projects':'Access applies to the selected project'}</li><li>Saved work stays readable when access ends</li><li>Allowances do not roll over. No automatic overage charges.</li></ul></details></article>;})}</div>
 <div className="free-plan-note"><div><h2>Just finding your starting point?</h2><p>Free setup, 3 AI replies per project, up to 3 projects each calendar month. Your toolbox, library and urgent help stay free.</p></div><button className="secondary" onClick={back}>Keep exploring free →</button></div>
 <p className="pricing-fine-print">Prices in CAD before applicable tax. Drawings support selected designs, including the bookcase; they are not engineer-approved construction plans. Retailer comparisons use published listings, not guaranteed store stock.</p>
 {state?.grants?.length>0&&<details className="billing-details"><summary>My access & usage</summary>{state.grants.map(g=>{const u=(state.usage||[]).filter(x=>x.bucket===g.id);return <p key={g.id}><strong>{plans[g.plan].name}</strong> · {u.filter(x=>x.feature==='answer').length} of {plans[g.plan].answers} AI replies · {u.filter(x=>x.feature==='search').length} of {plans[g.plan].searches} comparisons · until {new Date(g.ends_at).toLocaleDateString()}{g.project_id&&<> · <a href={'/project/'+g.project_id}>Open project →</a></>}</p>;})}{state.portal&&<button className="secondary" disabled={busy} onClick={()=>purchase('portal')}>Manage billing & cancellation ↗</button>}</details>}{error&&(!pendingPlan||pendingPlan==='portal')&&<div role="alert"><p className="error">{error}</p>{!pendingPlan&&<button className="secondary" onClick={refresh}>Retry plan status</button>}</div>}
 </section>;
}
