'use client';
import {useState} from 'react';
import {shoppingRows} from '../lib/project-pack.mjs';
import RetailerSearch from './retailer-search';
import {packLibrary} from '../lib/pack-library.mjs';
import {compareQuotes,quoteTotal,validateQuote} from '../lib/project-experience.mjs';
export default function ProjectSavings({entry,items,work,onUpdate,onOffer}){
 let materialOptions=packLibrary.find(p=>p.id===entry?.id)?.materials||[];try{if(work?.answers)materialOptions=[...materialOptions,...shoppingRows(work,items,items.filter(i=>i.owned).map(i=>i.id)).filter(r=>r.kind==='material'&&!r.owned).map(r=>r.name)];}catch{}
 const [error,setError]=useState('');const quotes=work?.quotes||[];const comparisons=compareQuotes(quotes);const alternatives=items.filter(i=>!i.owned&&i.alternative);const missing=items.filter(i=>!i.owned&&['essential','preparation'].includes(i.tier));
 function add(e){e.preventDefault();setError('');if(quotes.length>=30){setError('This project has 30 quotes. Remove an old quote before adding another.');return;}const f=Object.fromEntries(new FormData(e.currentTarget));try{const q=validateQuote({...f,compatible:f.compatible==='on'},items.map(i=>i.id));onUpdate({quotes:[...quotes,{...q,id:crypto.randomUUID(),at:new Date().toISOString()}]});e.currentTarget.reset();}catch(err){setError(err.message);}}
 return <section className="savings-panel" id="project-savings"><div className="section-heading"><div><h2>Find tools & materials</h2><p>{items.filter(i=>i.owned).length} items already owned · {missing.length} essential or preparation items to review.</p></div><span className="entry-type">Save a Buck preview</span></div>
 <RetailerSearch items={items} materials={materialOptions} work={work} onUpdate={onUpdate}/>
 {alternatives.map(i=><div className="substitute" key={i.id}><b>{i.name}: {i.alternative.owned?'you own':'consider'} {i.alternative.name}</b><p>{i.alternative.note}</p></div>)}
 <details className="manual-quotes"><summary>Compare quotes manually</summary><h3>Compare prices you find</h3><p>Enter purchase quotes in CAD for the same specification and quantity. Include delivery and tax as amounts. These are your entries, not live stock or local-store prices.</p>
 <details className="quote-editor"><summary>Add a retailer quote</summary><form onSubmit={add} className="quote-form"><label>Kit item<select name="itemId" required>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>Retailer (purchase quote)<input name="retailer" required maxLength={80} placeholder="e.g. Home Depot"/></label><label className="wide">Specification / model<input name="spec" required maxLength={160} placeholder="Use the same model or specification for matching quotes"/></label><label>Quantity<input name="quantity" type="number" min="1" max="999" step="1" defaultValue="1" required/></label><label>Unit price · CAD<input name="price" type="number" min="0" max="100000" step="0.01" required/></label><label>Delivery · CAD<input name="delivery" type="number" min="0" max="100000" step="0.01" defaultValue="0" required/></label><label>Tax · CAD<input name="tax" type="number" min="0" max="100000" step="0.01" defaultValue="0" required/></label><label className="own-toggle wide"><input name="compatible" type="checkbox"/>I checked that this specification suits the job.</label><button className="primary">Save quote to project</button></form>{error&&<p role="alert" className="error">{error}</p>}</details>
 {quotes.length>0&&<div className="quote-list">{quotes.map(q=><article key={q.id}><div><strong>{q.retailer} · {items.find(i=>i.id===q.itemId)?.name||q.itemId}</strong><p>{q.quantity} × {q.spec} · entered {new Date(q.at).toLocaleDateString()}</p><small>{q.compatible?'Suitability checked by you':'Suitability not checked — excluded from comparison'}</small></div><strong>C${quoteTotal(q).toFixed(2)}</strong><button className="text-button" aria-label={`Remove quote from ${q.retailer} for ${q.spec}`} onClick={()=>onUpdate({quotes:quotes.filter(x=>x.id!==q.id)})}>Remove</button></article>)}</div>}
 {comparisons.map(({best,difference,count})=><p className="comparison-result" key={best.id}><strong>{best.retailer}: C${quoteTotal(best).toFixed(2)}</strong> is the lowest of your {count} matching quotes for {best.quantity} × {best.spec}. Difference to highest: C${difference.toFixed(2)}. Recheck the quote before purchasing.</p>)}
 {quotes.length>1&&!comparisons.length&&<p className="small">To compare, use the same kit item, quantity and specification text on at least two quotes, and check suitability for each.</p>}
 </details></section>;
}
