'use client';
import {useState} from 'react';
import {projectTitle,projectStage} from '../lib/journey.mjs';
import {library} from '../lib/library.mjs';
import WorkspaceBackup from './workspace-backup';
export default function ProjectList({conversations,saved,owned,onNavigate,onUpdate,onDelete,onCopy,onResume,onRestore}){
 const [tab,setTab]=useState('projects'),[query,setQuery]=useState('');
 const records=conversations.filter(r=>tab==='archived'?r.archived:!r.archived).filter(r=>(projectTitle(r)+' '+r.request).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt));
 const entries=saved.filter(r=>(library.find(g=>g.id===r.id)?.title||'').toLowerCase().includes(query.toLowerCase()));
 return <section className="journey-page project-list-page"><div className="page-title-row"><div><p className="page-kicker">PICK UP WHERE YOU LEFT OFF</p><h1>My projects</h1><p>Your ideas, advice and progress, together.</p></div><button className="primary" onClick={()=>onNavigate('/')}>＋ New project</button></div><div className="list-toolbar"><div className="section-nav" role="group" aria-label="Saved work">{[['projects','Projects'],['guides','Saved guides'],['archived','Archived']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div><label className="sr-only" htmlFor="project-search">Search saved work</label><input id="project-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a project…"/></div>
 {tab==='guides'?entries.length?<div className="project-list-grid">{entries.map(r=><article className="project-list-card" key={r.id}><span className="small">{r.pack?'Saved design':r.planningPack?'Saved workbook':'Reference guide'}</span><button className="project-delete" aria-label={'Delete '+(library.find(g=>g.id===r.id)?.title||'guide')} onClick={()=>onDelete(r.id,library.find(g=>g.id===r.id)?.title||'guide',false)}>×</button><h2>{library.find(g=>g.id===r.id)?.title}</h2><button className="secondary" onClick={()=>onResume(r)}>Open {r.pack?'design':'guide'} →</button></article>)}</div>:<div className="calm-empty"><h2>No saved guides {query?'match':'yet'}</h2><p>Save useful references from the library to find them here.</p><button className="secondary" onClick={()=>onNavigate('/library')}>Explore the library →</button></div>:records.length?<div className="project-list-grid">{records.map(r=><article className="project-list-card" key={r.id}><span className="project-stage">{projectStage(r)}</span><button className="project-delete" aria-label={'Delete '+projectTitle(r)} onClick={()=>onDelete(r.id,projectTitle(r),true)}>×</button><h2>{projectTitle(r)}</h2><p className="small">Updated {new Date(r.updatedAt).toLocaleDateString()}</p><button className="primary" onClick={()=>onNavigate('/project/'+r.id)}>Continue project →</button><details className="project-manage"><summary>Manage</summary><label>Project name<input maxLength={100} value={r.title||''} placeholder={r.request} onChange={e=>onUpdate({...r,title:e.target.value,updatedAt:new Date().toISOString()})}/></label><button className="text-button" onClick={()=>onCopy(r)}>Make a copy</button><button className="text-button" onClick={()=>onUpdate({...r,archived:!r.archived,updatedAt:new Date().toISOString()})}>{r.archived?'Restore project':'Archive project'}</button></details></article>)}</div>:<div className="calm-empty"><h2>{query?'No matching projects':tab==='archived'?'No archived projects':'Your next project starts here'}</h2><p>{query?'Try a shorter search.':tab==='archived'?'Projects you archive will appear here.':'Tell Kitsley what you want to fix or make.'}</p>{tab==='projects'&&!query&&<button className="primary" onClick={()=>onNavigate('/')}>Start a project →</button>}</div>}
 <div className="project-backup-area"><WorkspaceBackup conversations={conversations} owned={owned} onRestore={onRestore}/></div></section>;
}
