'use client';
import BrandMark from './brand-mark';
import {useState} from 'react';
import PackKit from './pack-kit';
import DoorCheck from './door-check';
export default function SimpleGuide({p,work,check,owned,onToggleOwned,onSave,onUpdate,onBack,isSaved}){const [prompt,setPrompt]=useState(work.request||''),[started,setStarted]=useState(false),[submitted,setSubmitted]=useState('');return <section className={'simple-guide ai-conversation '+(started?'has-response':'')}><div className="conversation-top"><button className="text-button" onClick={onBack}>← Explore guides</button><span>PROJECT ASSISTANT</span></div><div className="simple-guide-heading"><div><span className="assistant-emblem"><BrandMark/></span><h1>A little know-how.<br/>A lot you can do.</h1><p>What are we fixing or making today?</p></div></div><form className="prompt-first" onSubmit={e=>{e.preventDefault();if(!prompt.trim())return;onUpdate({request:prompt.trim()});setSubmitted(prompt.trim());setStarted(true);}}><label className="sr-only" htmlFor="project-prompt">Describe your problem or project</label><textarea id="project-prompt" rows="3" maxLength="3000" value={prompt} onChange={e=>{setPrompt(e.target.value);setStarted(false);}} placeholder={p.id==='dripping-faucet'?'My kitchen tap keeps dripping after I turn it off. I have basic tools. Where should I start?':'Describe your project, what you have tried, and what you would like help with…'} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form.requestSubmit();}}}/><div><span className="small">Preview · AI offline</span><button className="primary" disabled={!prompt.trim()} aria-label="Send your request">↑</button></div></form>
 {started&&<section className="conversation-response" aria-live="polite"><div className="user-message">{submitted}</div><div className="assistant-name"><BrandMark/><strong>Kitsley</strong><span>Guide preview</span></div><h2>Let’s start here.</h2><p>{p.observe}</p><p>{p.next}</p><p className="small">Your request is saved. This is the existing guide for this page, not an AI diagnosis or a personalized repair plan.</p>{p.id==='sticking-door'&&<DoorCheck work={work} onUpdate={onUpdate}/>}<div className="simple-extras">{!check.blocked&&<details><summary>Check what I already own</summary><PackKit items={check.items} owned={owned} onToggleOwned={onToggleOwned} scope="Initial-check tools only. A repair kit depends on identifying the problem."/></details>}<details><summary>My notes</summary><label htmlFor="simple-notes">Keep useful details<textarea id="simple-notes" rows="3" maxLength="3000" value={work.notes||''} onChange={e=>onUpdate({notes:e.target.value})}/></label></details></div></section>}

 {!started&&<p className="composer-hint">Describe it in your own words. Add measurements or what you’ve already tried.</p>}
 {check.blocked&&<p className="small">{check.scope}</p>}{p.stop&&<p className="small muted">{p.stop}</p>}</section>;}
