'use client';
import {initializeWorkspace,stopWorkspaceSync,workspaceStorage} from '../lib/account-storage.mjs';
import ProjectConversation, {ProjectEntry} from './project-conversation';
import {conversationKey,createConversation,repairConversationMatch} from '../lib/conversation.mjs';
import ProjectList from './project-list';
import {projectTitle} from '../lib/journey.mjs';
import ToolboxWorkspace from './toolbox-workspace';
import WorkspaceBackup from './workspace-backup';
import {mergeBackup} from '../lib/workspace-backup.mjs';
import BrandMark from './brand-mark';
import {useState,useEffect,useRef} from 'react';
import {projects,products,ownedChoices,merchants} from '../lib/catalog.mjs';
import {guides,materialTips} from '../lib/guides.mjs';
import Library from './library';
import Account from './account';
import SyncStatus,{useSyncStatus} from './sync-status';
import Dashboard, {WorkspaceIcon} from './dashboard';
import {searchLibrary,library} from '../lib/library.mjs';
import Urgent from './urgent';
import PaidOffer from './paid-offer';
import PackLibrary from './pack-library';
import BookcasePack from './bookcase-pack';
import {starterKit,toolGroups,toolGroup,refreshOwnership} from '../lib/toolbox.mjs';

function Icon({name='arrow',size=20}){const paths={close:'M6 6l12 12M18 6 6 18',arrow:'M5 12h14m-6-6 6 6-6 6',plus:'M12 5v14M5 12h14',check:'m5 12 4 4L19 6',book:'M3 4h6l3 2 3-2h6v15h-6l-3 2-3-2H3zM12 6v15',tool:'m14 6-8 8a3 3 0 1 0 4 4l8-8M14 6a5 5 0 0 0 6 6l-4-4 1-4a5 5 0 0 0-3 2',save:'M5 3h14v18l-7-4-7 4z',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',back:'M19 12H5m6-6-6 6 6 6',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z'};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.arrow}/></svg>}
const materialNames={mdf:'MDF',plywood:'Plywood',solid:'Solid wood'};
export default function Home(){
 const [packId,setPackId]=useState(''),[libraryRequest,setLibraryRequest]=useState(null),[toolQuery,setToolQuery]=useState(''),[view,setView]=useState('home'),[description,setDescription]=useState(''),[projectId,setProjectId]=useState(''),[material,setMaterial]=useState('plywood'),[finish,setFinish]=useState('none'),[owned,setOwned]=useState([]),[saved,setSaved]=useState([]),[result,setResult]=useState(null),[tab,setTab]=useState('steps'),[done,setDone]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ready,setReady]=useState(false),[question,setQuestion]=useState(''),[answer,setAnswer]=useState('');
 const [conversations,setConversations]=useState([]),[conversationId,setConversationId]=useState(''),[aiEnabled,setAiEnabled]=useState(false),[conversationPanel,setConversationPanel]=useState('conversation'),[showArchived,setShowArchived]=useState(false);
 const sync=useSyncStatus();
 const form=useRef(null),results=useRef(null),persisted=useRef({});
 const [loadError,setLoadError]=useState('');
 function route(){const url=new URL(window.location.href),parts=url.pathname.split('/').filter(Boolean),params=Object.fromEntries(url.searchParams);setNotice('');document.title=(parts[0]==='guides'?library.find(p=>p.id===parts[1])?.title:parts[0]==='plan'?projects.find(p=>p.id===parts[1])?.name:{library:'Project library',toolbox:'My toolbox',projects:'My projects',urgent:'Urgent help',offers:'Plans & pricing',packs:'Project packs'}[parts[0]])?'Kitsley · '+(parts[0]==='guides'?library.find(p=>p.id===parts[1])?.title:parts[0]==='plan'?projects.find(p=>p.id===parts[1])?.name:{library:'Project library',toolbox:'My toolbox',projects:'My projects',urgent:'Urgent help',offers:'Plans & pricing',packs:'Project packs'}[parts[0]]):'Kitsley — Your home, handled.';
 if(parts[0]==='project'){setView('conversation');setConversationId(parts[1]||'');setConversationPanel(['plan','steps'].includes(params.panel)?params.panel:'conversation');document.title='Kitsley · Your project';}
 else if(parts[0]==='guides'||parts[0]==='library'){setView('library');setLibraryRequest({...params,id:parts[0]==='guides'?parts[1]:undefined,nonce:Date.now()});}
 else if(parts[0]==='toolbox'){setView('tools');setToolQuery(params.q||'');}
 else if(parts[0]==='packs'){if(!parts[1]){setView('library');setLibraryRequest({nonce:Date.now()});}else{setView('pack');setPackId(parts[1]);}}
 else if(parts[0]==='offers')setView('offers');
 else if(parts[0]==='projects')setView('saved');else if(parts[0]==='urgent')setView('urgent');
 else {setView('home');if(parts[0]==='plan'){setProjectId(parts[1]);setDescription('Plan '+(projects.find(p=>p.id===parts[1])?.name||'my project'));setMaterial(params.material||'plywood');setFinish(params.finish||'none');try{const draft=JSON.parse(workspaceStorage.getItem('kitsley-plan-'+parts[1])||'null')||JSON.parse(workspaceStorage.getItem('kitsley-saved')||'[]').find(p=>p.id===parts[1]&&p.result),items=JSON.parse(workspaceStorage.getItem('kitsley-owned')||'[]');if(draft?.result?.project?.id===parts[1]&&draft.result.material===(params.material||'plywood')&&draft.result.finish===(params.finish||'none')){setResult(refreshOwnership(draft.result,items));setDone(JSON.parse(workspaceStorage.getItem('kitsley-saved')||'[]').find(p=>p.id===parts[1])?.done||draft.done||[]);setTab(['kit','steps','tips'].includes(params.tab)?params.tab:'kit');}else setResult(null);}catch{setResult(null);}}else{setResult(null);setProjectId('');}}
 }
 function navigate(url,replace=false){if(window.location.pathname+window.location.search!==url)window.history[replace?'replaceState':'pushState']({},'',url);route();if(!replace)window.scrollTo({top:0,behavior:'instant'});}
 useEffect(()=>{fetch('/api/conversation').then(r=>r.json()).then(d=>setAiEnabled(d.enabled===true)).catch(()=>{});},[]);
 useEffect(()=>{route();window.addEventListener('popstate',route);return()=>window.removeEventListener('popstate',route);},[]);
 useEffect(()=>{if(!ready)return;setResult(p=>refreshOwnership(p,owned));setSaved(s=>s.map(p=>p.result?{...p,result:refreshOwnership(p.result,owned)}:p));},[owned,ready]);

 function loadWorkspace(){try{const records=JSON.parse(workspaceStorage.getItem(conversationKey)||'[]'),o=JSON.parse(workspaceStorage.getItem('kitsley-owned')||'[]'),s=JSON.parse(workspaceStorage.getItem('kitsley-saved')||'[]');
 const cs=Array.isArray(records)?records.map(repairConversationMatch):[],os=Array.isArray(o)?o.filter(id=>ownedChoices.includes(id)):[],ss=Array.isArray(s)?s.filter(p=>p&&library.some(x=>x.id===p.id)&&Array.isArray(p.done)):[];
 persisted.current={conversations:JSON.stringify(cs),owned:JSON.stringify(os),saved:JSON.stringify(ss)};setConversations(cs);setOwned(os);setSaved(ss);
 }catch{setLoadError('Your workspace could not be loaded. Please retry.');}}
 useEffect(()=>{let alive=true;initializeWorkspace().then(()=>{if(alive){loadWorkspace();setReady(true);route();}}).catch(e=>{if(alive)setLoadError(e.message);});window.addEventListener('kitsley-sync',loadWorkspace);return()=>{alive=false;stopWorkspaceSync();window.removeEventListener('kitsley-sync',loadWorkspace);};},[]);
 useEffect(()=>{if(ready)try{for(const [name,key,value] of [['conversations',conversationKey,conversations],['owned','kitsley-owned',owned],['saved','kitsley-saved',saved]]){const json=JSON.stringify(value);if(persisted.current[name]!==json){workspaceStorage.setItem(key,json);persisted.current[name]=json;}}}catch{setNotice('Device storage is full or unavailable. Download a backup before leaving this page.');}},[owned,saved,conversations,ready]);
 function startConversation(request,guideId){const record=createConversation(request,crypto.randomUUID(),guideId);setConversations(rows=>[record,...rows]);navigate('/project/'+record.id);}
 function restoreWorkspace(backup){const stock=JSON.parse(workspaceStorage.getItem('kitsley-sheet-stock')||'[]');const ids=new Set(stock.map(s=>s.id));workspaceStorage.setItem('kitsley-sheet-stock',JSON.stringify([...stock,...backup.stock.filter(s=>!ids.has(s.id))]));setConversations(rows=>mergeBackup(rows,backup,()=>crypto.randomUUID()));setOwned(rows=>[...new Set([...rows,...backup.owned])]);window.dispatchEvent(new Event('kitsley-stock'));}
 function deleteCard(id,title,conversation=false){if(!window.confirm('Delete “'+title+'”? This removes its saved details from your workspace and synced devices. This cannot be undone.'))return;if(conversation)setConversations(rows=>rows.filter(r=>r.id!==id));else{setSaved(rows=>rows.filter(r=>r.id!==id));try{workspaceStorage.removeItem('kitsley-plan-'+id);}catch{}}setNotice('Project deleted.');}
 function updateConversation(record){setConversations(rows=>rows.map(r=>r.id===record.id?record:r));}
 function browseGuide(request={},replace=false){openLibrary(request,replace);}
 function openLibrary(request={},replace=false){const {id,...filters}=request;const params=new URLSearchParams(Object.entries(filters).filter(([k,v])=>v&&v!=='all'&&k!=='nonce'));navigate((id?'/guides/'+id:'/library')+(params.size?'?'+params:''),replace);}
 function resume(p){if(p.planningPack){navigate('/packs/'+p.id);return;}if(p.pack){navigate('/packs/bookcase');return;}if(!p.result){openLibrary({id:p.id,material:p.material});return;}navigate('/plan/'+p.id+'?'+new URLSearchParams({material:p.result.material,finish:p.result.finish||'none'}));setResult(refreshOwnership(p.result,owned));setDone(p.done);setTab('kit');setAnswer('');setTimeout(()=>results.current?.scrollIntoView({behavior:'smooth'}),100);}
 function go(v){if(v==='offers'&&view==='conversation'){navigate('/offers?project='+encodeURIComponent(conversationId));return;}navigate({home:'/',tools:'/toolbox',saved:'/projects',urgent:'/urgent',offers:'/offers'}[v]||'/');}
 function choose(p,m=material){navigate('/plan/'+p.id+'?material='+(p.id==='planter'?'solid':m));setResult(null);setTimeout(()=>form.current?.scrollIntoView({behavior:'smooth',block:'center'}),50);}
 function updateGuide(p,patch){setSaved(s=>{const previous=s.find(x=>x.id===p.id)||{id:p.id,done:[],at:new Date().toISOString()};return [{...previous,...patch},...s.filter(x=>x.id!==p.id)];});}
 function saveGuide(p){setSaved(s=>s.some(x=>x.id===p.id)?s:[{id:p.id,done:[],at:new Date().toISOString()},...s]);setNotice('Guide saved in My projects.');}
 async function build(e){e.preventDefault();if(!projectId){const matches=searchLibrary({query:description});openLibrary(matches.length===1?{id:matches[0].id}:{query:description});return;}setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/recommend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({description,projectId,material,finish,owned})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not create your plan.');setResult(data);try{workspaceStorage.setItem('kitsley-plan-'+data.project.id,JSON.stringify({result:data,done:[]}));}catch{}window.history.replaceState({},'', '/plan/'+data.project.id+'?'+new URLSearchParams({material,finish}));setDone([]);setTab('kit');setQuestion('');setAnswer('');setTimeout(()=>results.current?.scrollIntoView({behavior:'smooth',block:'start'}),80);}catch(e){setError(e.message);}finally{setBusy(false);}}
 function savePlan(){const entry={...saved.find(p=>p.id===result.project.id),id:result.project.id,result,done,at:new Date().toISOString()};setSaved(s=>[entry,...s.filter(p=>p.id!==entry.id)]);try{workspaceStorage.setItem('kitsley-plan-'+entry.id,JSON.stringify(entry));}catch{}setNotice('Project and progress saved.');}
 function toggleDone(i){const next=done.includes(i)?done.filter(x=>x!==i):[...done,i];setDone(next);setSaved(s=>s.map(p=>p.id===result.project.id?{...p,done:next}:p));try{workspaceStorage.setItem('kitsley-plan-'+result.project.id,JSON.stringify({result,done:next}));}catch{}}
 function toggleOwned(id){setOwned(o=>o.includes(id)?o.filter(x=>x!==id):[...o,id]);}
 function ask(e){e.preventDefault();const q=question.toLowerCase();if(!q.trim())return;let reply;if(/material|mdf|plywood|wood/.test(q))reply=materialTips[result.material];else if(/buy|tool|need|kit|cost/.test(q)){const items=result.items.filter(p=>p.tier==='essential'&&!p.owned);reply='Start with the essential items in Your kit: '+items.map(p=>p.name).join(', ')+'. The price range is an illustrative equipment budget; raw material and quantities are not included.';}else if(/hinge|door|depth/.test(q)&&result.project.id==='cabinet-doors')reply=guides['cabinet-doors'][2].body+' '+guides['cabinet-doors'][2].tip;else if(/next|start|first/.test(q)){const next=guides[result.project.id].find((_,i)=>!done.includes(i));reply=next?next.title+': '+next.body:'You have checked off every step. Review your finished work against the plan and manufacturer instructions before use.';}else if(/finish|paint|sand/.test(q))reply=materialTips[result.material]+' Follow the chosen coating system’s preparation, ventilation, recoat and cure instructions. Test on an offcut first.';else reply='This guide can explain the next step, essential kit, material or finish. Start a project from the main prompt for tailored AI advice.';setAnswer(reply);}
 const activeSteps=result?guides[result.project.id]:[];
 return <><header className="header focused-header journey-header"><a className="brand" href="/" onClick={e=>{e.preventDefault();go('home');}} aria-label="Kitsley home"><BrandMark/>kitsley</a><nav aria-label="Main navigation">{[['home','/','Start a project'],['saved','/projects','My projects'],['library','/library','Library'],['tools','/toolbox','My toolbox']].map(([id,url,label])=><a key={id} href={url} aria-current={view===id?'page':undefined} onClick={e=>{e.preventDefault();navigate(url);}}>{label}</a>)}</nav><div className="header-account"><Account/></div><details className="site-more"><summary aria-label="Help and plans">•••</summary><div onClick={e=>e.currentTarget.parentElement.removeAttribute('open')}><button onClick={()=>go('offers')}>Plans & pricing</button><button onClick={()=>go('urgent')}>Urgent help</button></div></details></header>
 <main className="workspace-main">
 {!ready||sync.state==='expired'?<section className="inner-page" role="status"><p>{loadError||(sync.state==='expired'?sync.text:"Loading your workspace…")}</p>{(loadError||sync.state==='expired')&&<button className="primary" onClick={()=>window.location.reload()}>Retry</button>}</section>:<>
 {notice&&<div role="status" className="notice">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
 {view==='conversation'&&ready&&(conversations.find(r=>r.id===conversationId)?<ProjectConversation key={conversationId} panel={conversationPanel} record={conversations.find(r=>r.id===conversationId)} onUpdate={updateConversation} onNavigate={navigate} owned={owned} onToggleOwned={toggleOwned} aiEnabled={aiEnabled}/>:<section className="inner-page"><h1>This project wasn’t found in your workspace.</h1><p>Check that you’re signed in to the account used to create it.</p><button className="primary" onClick={()=>go('home')}>Start a new project</button></section>)}
 {view==='home'&&<>
 {!projectId&&!result?<ProjectEntry key={view} conversations={conversations} onResume={id=>navigate('/project/'+id)} onStart={startConversation} onUrgent={()=>go('urgent')} aiEnabled={aiEnabled}/>:<Dashboard description={description} setDescription={setDescription} projectId={projectId} setProjectId={setProjectId} material={material} setMaterial={setMaterial} finish={finish} setFinish={setFinish} onSubmit={build} busy={busy} error={error} owned={owned} saved={saved} onLibrary={openLibrary} onToolbox={()=>go('tools')} onUrgent={()=>go('urgent')} onResume={resume} formRef={form} hasResult={!!result}/>}

 {result&&<section className="plan-result" ref={results}><div className="section-heading"><div><div className="eyebrow">YOUR PROJECT, BROKEN DOWN</div><h2>{result.project.name}</h2><p>{materialNames[result.material]} · {activeSteps.length} steps · {result.ownedCount} kit items already owned</p></div><button className="secondary" onClick={()=>openLibrary({id:result.project.id,material:result.material})}>Project workspace</button><button className="secondary" onClick={savePlan}><Icon name="save"/>Save project</button></div><div className="result-layout"><div><div className="tabs" role="tablist" aria-label="Project details">{[['kit','Your kit'],['steps','Your steps'],['tips','Useful tips']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>{setTab(id);const url=new URL(window.location.href);url.searchParams.set('tab',id);window.history.pushState({},'',url.pathname+url.search);}}>{label}</button>)}</div>
 {tab==='steps'&&<div className="step-list"><div className="progress-line"><span>{done.length} of {activeSteps.length} steps complete</span><progress max={activeSteps.length} value={done.length}/></div>{activeSteps.map((s,i)=><article className={'step '+(done.includes(i)?'complete':'')} key={s.title}><button className="step-check" aria-label={`${done.includes(i)?'Unmark':'Complete'} step ${i+1}`} aria-pressed={done.includes(i)} onClick={()=>toggleDone(i)}>{done.includes(i)?'✓':String(i+1).padStart(2,'0')}</button><div><h3>{s.title}</h3><p>{s.body}</p><div className="tip"><Icon name="spark" size={15}/><span>{s.tip}</span></div></div></article>)}</div>}
 {tab==='kit'&&<div className="kit-list"><p className="small muted">Illustrative CAD equipment ranges, not live prices. Timber, sheet stock, quantities and delivery are additional. Links search Canadian retailers; configured affiliate links may earn a commission.</p>{['essential','recommended','optional'].map(tier=><section key={tier}><h3 className="tier-heading">{tier}<span>{result.items.filter(p=>p.tier===tier).length}</span></h3>{result.items.filter(p=>p.tier===tier).map(p=><article className="kit-item" key={p.id}><div className="kit-symbol"><Icon name="tool"/></div><div><h4>{p.name}{p.owned&&<span className="owned-tag">Already owned</span>}</h4><p>{p.why}</p>{!p.owned&&<details><summary>Find at a retailer</summary><div className="retailers">{merchants.map(m=><a key={m.id} href={`/go/${p.id}?merchant=${m.id}`} target="_blank" rel="noopener noreferrer sponsored">{m.name} ↗</a>)}</div></details>}</div><div><label className="own-toggle"><input type="checkbox" aria-label={`I have this: ${p.name}`} checked={p.owned} onChange={()=>toggleOwned(p.id)}/>I have this</label><span className="price">C${p.min}–{p.max}</span></div></article>)}</section>)}</div>}
 {tab==='tips'&&<div className="tips-panel"><h3>Before you begin</h3><p>{result.project.note}</p><h3>Working with {materialNames[result.material]}</h3><p>{materialTips[result.material]}</p><h3>Make the plan your own</h3><p>These are project outlines, not dimensioned construction drawings. Confirm the design, dimensions, loads and manufacturer instructions before cutting or fastening.</p></div>}
 </div><aside className="project-aside"><div className="guide-card"><span className="guide-avatar"><BrandMark/></span><h3>A little help, right here.</h3><p>Ask about your next step, material, finish, or essential tools.</p><form onSubmit={ask}><label className="sr-only" htmlFor="question">Ask about this plan</label><input id="question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What should I do next?" maxLength={1000}/><button className="primary" disabled={!question.trim()}>Ask Kitsley<Icon/></button></form>{answer&&<p className="answer" role="status">{answer}</p>}<small>Quick answers from this guide. Start a project for tailored AI advice.</small></div><div className="budget-card"><span className="eyebrow">ESSENTIAL EQUIPMENT · EST. CAD</span><strong>C${result.estimate.min}–{result.estimate.max}</strong><p>Illustrative range, not live prices. Excludes items you already own, raw material and project quantities.</p></div></aside></div></section>}

 </>}
 <div hidden={view!=='library'}><Library request={libraryRequest} owned={owned} saved={saved} onSave={saveGuide} onToggleOwned={toggleOwned} onNavigate={browseGuide} onStart={p=>startConversation(p.name||p.title,p.id)} onUpdateGuide={updateGuide} onOffer={()=>go('offers')}/></div>
 {view==='pack'&&ready&&packId!=='bookcase'&&<PackLibrary owned={owned} onToggleOwned={toggleOwned} id={packId} onNavigate={navigate} saved={saved} onSave={updateGuide} onGuide={browseGuide}/>}
 {view==='pack'&&ready&&packId==='bookcase'&&<BookcasePack owned={owned} onToggleOwned={toggleOwned} saved={saved} onSave={updateGuide}/>}
 {view==='offers'&&<PaidOffer onExplore={()=>navigate('/')} onNavigate={navigate} conversations={conversations}/>}
 {view==='urgent'&&<Urgent onGuide={openLibrary}/>}
 {view==='tools'&&<ToolboxWorkspace owned={owned} toggleOwned={toggleOwned} addStarter={()=>setOwned(o=>[...new Set([...o,...starterKit])])} query={toolQuery} onQuery={q=>{setToolQuery(q);window.history.replaceState({},'', '/toolbox'+(q?'?q='+encodeURIComponent(q):''));}}/>}
 {view==='saved'&&<ProjectList conversations={conversations} saved={saved} owned={owned} onNavigate={navigate} onUpdate={updateConversation} onDelete={deleteCard} onResume={resume} onRestore={restoreWorkspace} onCopy={r=>setConversations(rows=>[{...r,id:crypto.randomUUID(),title:projectTitle(r)+' (copy)',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),archived:false},...rows])}/>}
 <section className="promise-strip" hidden><BrandMark/><p>You bring the idea.<br/><strong>We’ll help with the how.</strong></p><span>Useful guidance. Thoughtful tools. More doing.</span></section>
 </>}</main><footer><span>© {new Date().getFullYear()} Kitsley · Your home, handled.</span><span><SyncStatus/></span></footer></>;
}
