import {drawingReviewHTML} from './drawing-review.mjs';
import {contentHTML} from './project-content.mjs';
import {manualHTML} from './assembly-manual.mjs';
export const defaults={width:600,height:1000,depth:300,thickness:18,shelves:2};
export function design(input){const d=Object.fromEntries(Object.keys(defaults).map(k=>[k,Number(input[k])]));for(const [k,min,max] of [['width',400,800],['height',600,1200],['depth',250,400],['thickness',18,21],['shelves',1,4]])if(!Number.isFinite(d[k])||d[k]<min||d[k]>max||!Number.isInteger(d[k]))throw Error(`${k}: use a whole number from ${min} to ${max}.`);const {width:w,height:h,depth:z,thickness:t,shelves:n}=d,opening=(h-(n+2)*t)/(n+1);if(opening<150)throw Error('Leave at least 150 mm clear between shelves. Reduce the shelf count or increase the height.');return {...d,opening,parts:[{id:'A',name:'Side',qty:2,length:h,width:z-6,thickness:t},{id:'B',name:'Top / bottom',qty:2,length:w-2*t,width:z-6,thickness:t},{id:'C',name:'Interior shelf',qty:n,length:w-2*t,width:z-6,thickness:t},{id:'D',name:'Applied back',qty:1,length:h,width:w,thickness:6}]};}
export const fmt=n=>Number(n.toFixed(1));
export const caveat='Geometry preview only. Joinery, fasteners, shelf loads and wall anchoring require review before cutting or building. No load rating is provided.';
export function steps(d){return [
'Review the design: confirm actual sheet thickness, intended contents, suitable shelf spans, joint method and fasteners with a competent furniture maker before cutting.',
`Prepare the reviewed parts: label two A sides, two B top/bottom panels, ${d.shelves} C shelves and one D back. All dimensions are finished sizes in mm; allow for saw kerf and any finishing method.`,
`Lay out from the same bottom datum on both sides. Interior shelf undersides are ${Array.from({length:d.shelves},(_,i)=>fmt(d.thickness+(i+1)*d.opening+i*d.thickness)).join(', ')} mm above the cabinet base. Avoid adding rounded opening dimensions together.`,
'Dry-fit the top and bottom between the sides on a stable surface. Check squareness and fit before using the reviewed fastening method; hole positions and screw sizes are not specified in this preview.',
'Install the interior shelves using the reviewed joints. Square the carcass before attaching the applied back. Follow adhesive and finish manufacturers’ instructions.',
'Before use, anchor the bookcase to suitable wall structure with an appropriate furniture restraint. Select the restraint and wall fixings for the wall type; check the reviewed load limits.'
];}
export function drawing(d,exploded=false){const {width:w,height:h,depth:z,thickness:t,shelves:n}=d;const scale=Math.min(320/w,360/h),X=90,Y=75,rect=(x,y,a,b,fill='#e0eeec')=>`<rect x="${x}" y="${y}" width="${a}" height="${b}" fill="${fill}" stroke="#244b50"/>`,text=(x,y,s)=>`<text x="${x}" y="${y}" font-size="14" fill="#17252f">${s}</text>`;const dim=(x1,y1,x2,y2)=>`<path d="M${x1} ${y1}L${x2} ${y2}" stroke="#52616d" marker-start="url(#a)" marker-end="url(#a)"/>`;let body='';if(!exploded){body+=rect(X,Y,w*scale,h*scale,'#f8fafb');body+=rect(X,Y,t*scale,h*scale)+rect(X+(w-t)*scale,Y,t*scale,h*scale);for(let i=0;i<n+2;i++){let bottom=i===0?0:i===n+1?h-t:t+i*d.opening+(i-1)*t;body+=rect(X+t*scale,Y+(h-bottom-t)*scale,(w-2*t)*scale,t*scale);}body+=dim(X,Y-12,X+w*scale,Y-12)+dim(X-20,Y,X-20,Y+h*scale);body+=text(X,Y-25,`FRONT · ${w} mm wide`)+text(X,Y+h*scale+30,`${h} mm high · ${fmt(d.opening)} mm clear openings`);const sx=470;body+=dim(sx,Y+h*scale+12,sx+z*scale,Y+h*scale+12);body+=rect(sx,Y,(z-6)*scale,h*scale)+rect(sx+(z-6)*scale,Y,6*scale,h*scale,'#b9cad6')+text(sx,Y-25,'SIDE')+text(sx,Y+h*scale+30,`${z} mm total depth`);}else{const s=Math.min(0.29,280/h);const poly=(x,y,a,b,c,label)=>{const p=(xx,yy,zz)=>`${fmt(270+(xx-zz*.6)*s)},${fmt(100+(yy+zz*.35)*s)}`;return `<polygon points="${p(x,y,0)} ${p(x+a,y,0)} ${p(x+a,y,c)} ${p(x,y,c)}" fill="#b9d7d2" stroke="#244b50"/><polygon points="${p(x,y,0)} ${p(x+a,y,0)} ${p(x+a,y+b,0)} ${p(x,y+b,0)}" fill="#e0eeec" stroke="#244b50"/><polygon points="${p(x+a,y,0)} ${p(x+a,y,c)} ${p(x+a,y+b,c)} ${p(x+a,y+b,0)}" fill="#c7ddda" stroke="#244b50"/>${text(270+(x+a/2)*s,95+y*s,label)}`;};body+=poly(-100,0,t,h,z-6,'A')+poly(w+100,0,t,h,z-6,'A')+poly(t,-100,w-2*t,t,z-6,'B')+poly(t,h+100,w-2*t,t,z-6,'B');for(let i=1;i<=n;i++)body+=poly(t,i*(h/(n+1)),w-2*t,t,z-6,'C');body+=rect(590,95,w*.15,h*.15,'#f1e5d3')+text(590,75,'D · back')+text(80,525,'Exploded assembly reference · parts separated for clarity');}return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 570" role="img" aria-label="${exploded?'Exploded parts diagram':'Dimensioned front and side views'}"><defs><marker id="a" markerWidth="6" markerHeight="6" refX="3" refY="3" orient="auto-start-reverse"><path d="M6 0L0 3L6 6" fill="none" stroke="#52616d"/></marker></defs><rect width="800" height="570" fill="white"/>${body}${text(80,555,'All measurements in mm · do not scale from drawing')}</svg>`;}
// Conservative one-offcut-per-part matching. Never promises an optimized sheet yield.
export function matchStock(d,stock){const pool=stock.filter(s=>s.sound===true&&[s.length,s.width,s.thickness,s.qty].every(Number.isFinite)&&s.length>0&&s.width>0&&s.thickness>0&&Number.isInteger(s.qty)&&s.qty>0&&s.qty<=100).flatMap(s=>Array.from({length:s.qty},()=>({...s})));return d.parts.flatMap(p=>Array.from({length:p.qty},(_,i)=>{const index=pool.findIndex(s=>s.thickness===p.thickness&&s.length>=p.length&&s.width>=p.width);const found=index>=0?pool.splice(index,1)[0]:null;return {...p,qty:1,piece:p.id+(i+1),stock:found?.name||null};}));}
export function csv(d){return 'Part,Description,Quantity,Length mm,Width mm,Thickness mm\n'+d.parts.map(p=>[p.id,p.name,p.qty,p.length,p.width,p.thickness].join(',')).join('\n');}
export function packHTML(d,review){return `<!doctype html><html lang="en"><meta charset="utf-8"><title>Kitsley bookcase pack</title><style>body{font:16px system-ui;max-width:900px;margin:32px auto;padding:20px;color:#17252f}svg{width:100%;max-height:560px}td,th{padding:12px;border-bottom:1px solid #ccc;text-align:left}li{margin:16px 0}section{break-inside:avoid}</style><h1>Kitsley · Bookcase design preview</h1><p>${d.width} × ${d.height} × ${d.depth} mm · ${d.thickness} mm plywood · ${d.shelves} interior shelves</p><p><strong>${caveat}</strong></p>${drawingReviewHTML(d,review)}<section>${drawing(d)}</section><section>${drawing(d,true)}</section><h2>Finished cut list</h2><table><tr><th>Part</th><th>Qty</th><th>Length × width × thickness (mm)</th></tr>${d.parts.map(p=>`<tr><td>${p.id} · ${p.name}</td><td>${p.qty}</td><td>${p.length} × ${p.width} × ${p.thickness}</td></tr>`).join('')}</table>${manualHTML(d)}${contentHTML('bookcase')}<p>Allow for kerf. Grain follows the length column. Hardware and finishing allowances are not included.</p><p>Tip-over guidance: https://www.cpsc.gov/Safety-Education/Safety-Education-Centers/AnchorItgov</p></html>`;}
