// Generic equipment specifications, not endorsements or live merchant inventory.
const rows = [
['claw-hammer','Claw hammer','General fastening and nail removal with suitable eye protection',15,45,'hand-tools'],
['pliers','Combination pliers','Grip suitable mechanical parts; not for live electrical work',15,40,'hand-tools'],
['utility-knife','Utility knife','Use the right blade and controlled cutting method',10,25,'hand-tools'],
['drywall-knife','Drywall joint knife','Match width to the chosen patch or finishing system',12,35,'hand-tools'],
['sanding-block','Hand sanding block','Controlled manual sanding with appropriate dust controls',8,20,'finishing'],
['caulk-gun','Caulking gun','Match the gun to the sealant cartridge',12,35,'hand-tools'],
['screwdriver','Screwdriver set','Correct tip and size for accessible mechanical hardware',15,40,'hand-tools'],
['wrench','Adjustable wrench','Correct size and access for suitable mechanical fittings',15,40,'hand-tools'],
['bucket','Utility bucket','For ordinary clean-water and material handling',8,20,'workshop'],
['flashlight','Flashlight','Inspect visible areas from a safe position',15,45,'workshop'],
['gloves','Work gloves','Select protection for the task; avoid entanglement around rotating tools',10,30,'protection'],
['shovel','Shovel','For ground work only after buried services have been identified',25,60,'garden'],
['rake','Landscape rake','Prepare suitable soil or aggregate surfaces',25,60,'garden'],
['wheelbarrow','Wheelbarrow','Move material within its load rating',80,180,'garden'],
['stakes-string','Layout stakes and string','Mark boundaries after checking the site and buried services',12,30,'layout'],
['tamper','Hand tamper','Suitable only where the base design permits manual compaction',35,80,'garden'],
['trowel','Garden hand trowel','Small-scale planting in checked ground',10,30,'garden'],
['pruner','Hand pruners','Choose cutting capacity for the plant material',15,45,'garden'],
['watering-can','Watering can','Controlled watering for planting work',15,40,'garden'],
['rubber-mallet','Rubber mallet','Use a suitable non-marking head for the material',15,35,'hand-tools'],
['handsaw','Wood handsaw','Manual cutting for suitable small timber and supported work',20,55,'cutting'],

['eye','Safety glasses','Impact-rated eye protection',12,30,'protection'],
['hearing','Hearing protection','Earmuffs or correctly fitted earplugs',15,45,'protection'],
['respirator','Particulate respirator','Suitable, properly fitted protection for wood dust',25,65,'protection'],
['extractor','Dust extraction','Extractor and tool-compatible hose; collect dust at source',120,400,'protection'],
['saw','Circular saw','A portable saw for straight sheet cuts',90,220,'cutting'],
['blade','Fine-finish saw blade','Correct diameter, arbor, speed rating and material compatibility for your saw',30,80,'cutting'],
['guide','Straight-edge cutting guide','A securely clamped guide for repeatable straight cuts',30,100,'cutting'],
['clamps','Clamps','Hold work and guides securely',25,80,'assembly'],
['tape','Tape measure','Measure openings and check dimensions',10,30,'layout'],
['square','Combination square','Check square cuts and mark offsets',15,45,'layout'],
['drill','Drill / driver','Drill pilot holes and drive fasteners',65,180,'assembly'],
['hinge-jig','35 mm concealed-hinge jig','For compatible 35 mm cup hinges only',30,85,'joinery'],
['forstner','35 mm Forstner bit','Match the hinge cup and jig requirements',18,45,'joinery'],
['depth-stop','Drill depth stop','Set the depth to avoid drilling through the panel',8,25,'joinery'],
['sandpaper','Sanding abrasives','Progress through appropriate grits without over-sanding',12,35,'finishing'],
['sander','Random-orbit sander','Speed up broad surface preparation',55,160,'finishing'],
['primer','MDF-compatible primer','Seal faces and edges using a compatible coating system',25,60,'finishing'],
['paint','Cabinet paint','Durable finish compatible with the primer',35,95,'finishing'],
['roller','Fine-finish roller & tray','An accessible alternative to spraying',15,40,'finishing'],
['sprayer','Paint sprayer','Optional finish method; follow coating ventilation and PPE instructions',100,350,'finishing'],
['router','Router','For edge shaping and compatible joinery',100,280,'cutting'],
['router-bit','Edge-profile router bit','Match shank, speed rating and profile to your router',25,70,'cutting'],
['hinges','Concealed cabinet hinges','Verify overlay, opening angle, cup size and panel thickness',15,60,'hardware'],
['handles','Cabinet handles','Match screw centers and door thickness',15,65,'hardware'],
['screws','Wood screws','Choose type and length for the material and joint',10,25,'hardware'],
['glue','Wood glue','Choose a glue suitable for the material and environment',10,25,'assembly'],
['pocket-jig','Pocket-hole jig','For suitable panel thicknesses and joints',35,130,'joinery'],
['pocket-screws','Pocket-hole screws','Match thread and length to material and jig settings',12,30,'hardware'],
['level','Spirit level','Align cabinets, shelves and wall fixings',20,60,'layout'],
['stud-finder','Stud finder','Locate framing; verify positions before fastening',25,75,'layout'],
['brackets','Shelf brackets','Use rated supports and a suitable fixing design',20,75,'hardware'],
['anchors','Wall fasteners','Choose for the actual substrate and expected load',12,40,'hardware'],
['jigsaw','Jigsaw','Cut curves and internal openings',60,160,'cutting'],
['jigsaw-blades','Wood-cutting jigsaw blades','Match the blade fitting and material thickness',10,30,'cutting'],
['miter-saw','Miter saw','Repeatable crosscuts and angled trim cuts',150,400,'cutting'],
['miter-box','Miter box & handsaw','Manual alternative for small trim jobs',25,65,'cutting'],
['nailer','Brad nailer','Optional fixing aid; fasteners do not replace structural joinery',100,240,'assembly'],
['filler','Wood filler','Choose a paintable or stain-compatible filler',10,25,'finishing'],
['putty-knife','Filling knife','Apply filler and scrape loose material',6,20,'finishing'],
['drop-cloth','Drop cloth','Protect surrounding floors and furniture',12,35,'finishing'],
['degreaser','Surface cleaner','Remove grease before refinishing; follow product instructions',10,25,'finishing'],
['brush','Finishing brush','Choose bristles compatible with the coating',10,35,'finishing'],
['stain','Wood stain','Test on an offcut before applying',20,55,'finishing'],
['clearcoat','Clear protective finish','Select for the intended use and coating compatibility',25,70,'finishing'],
['workbench','Work support / sawhorses','Support the work and offcuts during cutting',45,150,'workshop'],
['drill-bits','Wood drill-bit set','Pilot and clearance holes sized for the fastener',15,45,'assembly'],
['countersink','Countersink bit','Seat suitable screw heads flush',10,30,'assembly'],
['chisel','Wood chisel','Clean up joints and hinge recesses',15,50,'joinery'],
['mallet','Woodworking mallet','Controlled assembly and chisel work',15,40,'assembly'],
['drawer-slides','Drawer slides','Match length, clearance and load rating to the design',25,90,'hardware'],
['edge-band','Edge banding','Cover exposed plywood edges',15,40,'finishing'],
['flush-trim','Edge-band trimmer','Trim applied banding neatly',15,35,'finishing'],
['pegboard','Pegboard panel','Workshop storage panel with appropriate supports',25,75,'workshop'],
['hooks','Pegboard hooks','Match the panel spacing and hole system',15,40,'hardware'],
['exterior-finish','Exterior wood finish','Choose a weather-resistant finish suited to the timber',30,80,'finishing'],
['exterior-screws','Exterior screws','Corrosion-resistant fasteners compatible with the timber',15,40,'hardware']
];
export const products = rows.map(([id,name,description,min,max,category])=>({id,name,description,min,max,category,enabled:true}));
const project = (id,name,subtitle,essential,recommended,optional,note) => ({id,name,subtitle,essential:essential.split(' '),recommended:recommended.split(' '),optional:optional.split(' '),note});
export const projects = [
project('cabinet-doors','Cabinet doors','A fresh face for your kitchen','eye hearing respirator extractor saw blade guide clamps tape square drill hinge-jig forstner depth-stop sandpaper hinges workbench','sander handles drill-bits','router router-bit sprayer','This plan assumes flat slab doors with compatible 35 mm concealed hinges. Verify overlay, hinge boring depth and panel thickness before buying.'),
project('shelves','Wall shelves','Make a little more room','eye hearing respirator extractor saw blade guide clamps tape square drill level stud-finder brackets anchors sandpaper workbench','drill-bits countersink edge-band','sander clearcoat','Confirm the wall construction, load, bracket rating and fastening design. Do not rely on drywall alone for heavy shelving.'),
project('bookcase','Bookcase','A home for your favorite stories','eye hearing respirator extractor saw blade guide clamps tape square drill screws glue sandpaper workbench anchors','pocket-jig pocket-screws drill-bits edge-band','sander clearcoat','Design suitable shelf spans and anchor tall furniture to appropriate wall structure to reduce tip-over risk.'),
project('workbench','Workbench','Build the heart of your workshop','eye hearing respirator extractor saw blade guide clamps tape square drill screws glue workbench','drill-bits countersink level','sander clearcoat','Use a tested bench design with suitable joinery and load capacity. Existing work supports are needed during assembly.'),
project('refinish','Furniture refinishing','Give a good piece a second life','eye respirator extractor sandpaper degreaser drop-cloth brush','sander filler putty-knife clearcoat','stain','Identify the old finish before disturbing it. Unknown or older coatings may require testing and specialist removal; dust PPE alone does not protect against coating vapors.'),
project('drawers','Drawer boxes','A smoother everyday detail','eye hearing respirator extractor saw blade guide clamps tape square drill screws glue drawer-slides sandpaper workbench','pocket-jig pocket-screws drill-bits','sander handles','Measure the chosen slide system first; drawer clearances and mounting locations vary.'),
project('trim','Interior trim','The finishing touch','eye hearing respirator extractor miter-box tape square sandpaper filler putty-knife','nailer level','miter-saw paint brush','Use suitable fasteners for the wall and trim. Check for hidden services before fastening.'),
project('planter','Outdoor planter','Make space for something green','eye hearing respirator extractor saw blade guide clamps tape square drill exterior-screws sandpaper workbench','drill-bits exterior-finish','sander','Use suitable exterior timber, drainage and a design appropriate for wet soil loads. MDF is unsuitable outdoors.'),
project('pegboard','Workshop pegboard','Everything in its place','eye drill tape level stud-finder pegboard hooks anchors','drill-bits workbench','brackets','Allow clearance behind the panel and fasten into a suitable structure. Check hook and panel load limits.'),
project('paint-cabinets','Paint cabinets','A new look, with the cabinets you have','eye respirator degreaser sandpaper primer paint roller drop-cloth','extractor sander brush filler putty-knife','sprayer handles','Check coating compatibility and identify existing coatings before sanding. Follow the finish manufacturer’s ventilation and respiratory-protection requirements.')
];
export const ownedChoices = products.map(p=>p.id);
export const merchants = [
{id:'amazon',name:'Amazon Canada',host:'www.amazon.ca',search:'https://www.amazon.ca/s?k='},
{id:'homedepot',name:'Home Depot Canada',host:'www.homedepot.ca',search:'https://www.homedepot.ca/search?q='},
{id:'rona',name:'RONA',host:'www.rona.ca',search:'https://www.rona.ca/en/search?query='},
{id:'walmart',name:'Walmart Canada',host:'www.walmart.ca',search:'https://www.walmart.ca/search?q='}
];
