// Topic recognition routes evidence; it never establishes skill, safety or permission.
export const domainVersion='2026-09-26.1';
const domain=(id,name,match,categories,questions,boundary)=>({id,name,match,categories,questions,boundary});
export const diyDomains=[
 domain('cabinetry','Cabinets, shelves & drawers',/\b(?:cabinet\w*|carca(?:s|ss)\w*|book\s?shel\w*|bookcase\w*|drawer\w*|shel(?:f|ves))\b/i,['Cabinetry','Screws & joints','Hardware & loads'],['What will it hold, and how is it supported?','What are the measured opening, actual board thickness and chosen hardware?'],'New cabinet, drawer, wall-hung and pet-enclosure designs require their own validated builder and connection checks. The bookcase builder cannot certify them.'),
 domain('cabinet-doors','Cabinet doors & hardware',/\b(?:cabinet doors?|door fronts?|hinge\w*|overlay|inset doors?)\b/i,['Cabinet doors','Hardware & loads'],['Which hinge/plate and overlay or inset arrangement?','What are the door thickness, size and weight?'],'Do not invent hinge boring, reveal, clearances or hinge count. Use the exact hardware planning data.'),
 domain('electrical','Electrical',/\b(?:electrical\w*|wir(?:e|es|ing)|gfci|gfi|rcd|afci|breakers?|outlets?|receptacles?|sockets?)\b/i,['Electrical'],['Is this routine user operation or wiring work?','What device, symptoms, country and local authority apply?'],'Observation, explanation and planning only for invasive electrical work; no live work, bypasses or repeated reset procedures.'),
 domain('plumbing','Plumbing',/\b(?:plumb\w*|pipes?|pex|cpvc|pvc|abs|faucet\w*|taps?|toilets?|drain\w*|sink\w*|shutoff|water heater)\b/i,['Plumbing'],['Which pipe, fitting system and service: potable water, waste or another system?','Can the system be isolated safely, and are there leaks or contamination?'],'Gas, pressurized repairs, concealed drainage/vent changes and unknown isolation need specialist assessment. A fitting example is not a universal procedure.'),
 domain('drywall','Drywall & plaster repairs',/\b(?:drywall|plaster\w*|sheetrock|gypsum|joint compound|taping|mud(?:ding)?)\b/i,['Drywall'],['Is this cosmetic damage or a rated/wet/structural assembly?','What board, framing, damage cause and compound/tape system are present?'],'Resolve moisture, hidden services and suspect old materials first. Do not invent a rated assembly or universal fastening schedule.'),
 domain('materials','Materials & fabrication',/\b(?:materials?|plywood|mdf|melamine|veneer|particleboard|wood|lumber|foam\w*|acrylic|polycarbonate|metal|alumin\w*|steel)\b/i,['Materials','Repairs','Blades & bits'],['What is the exact core, facing, thickness and product?','What load, exposure, cut and edge quality are required?'],'Unidentified material stays unknown. Do not infer strength or heat/cutting compatibility from a name or photograph.'),
 domain('adhesives','Adhesives & sealants',/\b(?:adhesive\w*|glu(?:e|ing)|epoxy|resin|sealant\w*|caulk\w*|silicone|solvent cement)\b/i,['Glues','Adhesives & sealants'],['What are both bonding surfaces, coatings and exposure?','Which adhesive formulation, joint role and cure conditions?'],'A bond or scrap test does not establish structural capacity. Do not substitute solvent cement, sealant and structural adhesive.'),
 domain('fastening','Fasteners, anchors & joints',/\b(?:fasten\w*|screws?|nails?|bolts?|anchor\w*|joist hanger|fixings?|joints?|wall[- ]mount|tv mount)\b/i,['Screws & joints','Hardware & loads','Fasteners & anchors'],['Which substrate, thickness, connection and load direction?','What exact connector/anchor and manufacturer schedule?'],'No load or hole size from a generic screw number. Verify concealed services, embedment, edge distances and corrosion compatibility.'),
 domain('hvac','HVAC & ventilation',/\b(?:hvac|furnace|air filter|merv|heat pump|thermostat|air condition\w*|refrigerant|duct\w*|ventilation)\b/i,['HVAC'],['Which equipment model and user-accessible maintenance task?','Which filter size/rating or symptom, and what does the manual permit?'],'Fuel, combustion, refrigerant, high-voltage and safety-control work need qualified service. Never bypass an interlock.'),
 domain('doors','Hanging doors & trim',/\b(?:prehung|pre-hung|hanging (?:a )?door|hang (?:a )?door|interior door|exterior door|door jamb|door frame|door sticking|sticking door|trim|baseboard|skirting)\b/i,['Doors & trim'],['Is this a slab, prehung unit, interior, exterior or rated door?','What are the opening, jamb depth, floor clearance and swing?'],'Do not transfer ordinary interior-door instructions to fire-rated or exterior assemblies. Assess movement or damage before trimming.'),
 domain('finishing','Painting, preparation & sanding',/\b(?:paint\w*|prim(?:er|ing)|stain\w*|sanding|sander\w*|grit|finish\w*|spray\w*|orange peel|coating\w*)\b/i,['Surface preparation','Paints & primers','Stains & topcoats','Sanding','Equipment'],['What substrate, existing coating and selected finish system?','What equipment/nozzle and application conditions?'],'Do not invent thinning ratios, pressure, grit or recoat times. Resolve old-coating hazards and product incompatibility first.'),
 domain('wet-areas','Tile, showers & waterproofing',/\b(?:tile\w*|tiling|grout|waterproof\w*|shower|wet room|kerdi|bathroom)\b/i,['Waterproofing & tile'],['Which substrate, membrane, drain and tile system?','What moisture condition and local requirements apply?'],'Tiles and grout alone do not establish a waterproof assembly. Changes to structure, drains or rated walls require assessment.'),
 domain('flooring','Flooring',/\b(?:flooring|laminate floor|vinyl plank|subfloor|underlay\w*|floating floor|hardwood floor)\b/i,['Flooring'],['What exact flooring and substrate?','What are the moisture, flatness, climate and expansion requirements?'],'Do not apply one product’s moisture, expansion or acclimation limits to another.'),
 domain('maintenance','Home maintenance & alarms',/\b(?:maintenance|smoke alarm|carbon monoxide|co alarm|dryer|lint|appliance|weatherstrip\w*)\b/i,['Home maintenance'],['What appliance/device model and maintenance interval?','Is there an alarm, heat, smoke, leakage or another fault?'],'Active alarms and hazardous faults are emergencies, not maintenance prompts. Internal appliance repairs need appropriate service.'),
 domain('outdoor','Outdoor, decks & building envelope',/\b(?:outdoor|deck\w*|fence\w*|gutter\w*|roof\w*|flashing|exterior|weatherproof\w*)\b/i,['Outdoor & envelope','Fasteners & anchors'],['What exposure, material treatment and support system?','Is work at height or a structural/weatherproofing alteration involved?'],'Do not issue an unverified deck, roof or ladder-work design. Obtain applicable local and manufacturer requirements.')
];
export function domainsFor(question,record={}){
 const current=diyDomains.filter(d=>d.match.test(String(question||'')));
 // Context can help an ambiguous follow-up, but cannot override an explicit topic switch.
 return current.length?current:diyDomains.filter(d=>d.match.test([record?.guideId,record?.request,record?.pack?.input?.material].filter(Boolean).join(' ')));
}
export function domainContext(question,record={}){
 const domains=domainsFor(question,record);
 return {version:domainVersion,domains:domains.map(({match,categories,...d})=>d),coverage:domains.length?'partial-reference-coverage':'research-required',rule:'Topic recognition is not expertise or approval. Answer the current request, reuse confirmed answers, ask only one missing decisive question. Reference knowledge is partial. Research unsupported details and keep unsupported designs in planning. Never infer a licence or competence from project completions.'};
}
export function aggregateDomainLearning(records=[]){
 const rows=new Map();
 for(const r of records)for(const [id,count] of Object.entries(r?.knowledge?.domains||{})){
  if(!diyDomains.some(d=>d.id===id)||!Number.isSafeInteger(count)||count<=0)continue;
  const row=rows.get(id)||{id,questions:0,projects:0};row.questions+=Math.min(count,10000);row.projects++;rows.set(id,row);
 }
 return [...rows.values()].sort((a,b)=>b.questions-a.questions);
}
