export const finishDefaults={system:'paint',surface:'plywood',method:'brush',colour:'',sheen:'satin',notes:''};
export const surfaces={plywood:{name:'Bare plywood',prep:'Inspect the thin face veneer and exposed ply edges. Fill voids with a paint-compatible filler; lightly smooth without sanding through the veneer. Decide on edge banding before finishing.',prime:'Choose a primer approved for the plywood and topcoat. Treat exposed edges and any stains with a compatible system; test for bleed-through.'},mdf:{name:'Bare MDF',prep:'Inspect for swollen or damaged edges. Keep cleaning moisture minimal and collect fine sanding dust. Smooth cut edges without rounding the joints.',prime:'Use an MDF-compatible sealer/primer, paying particular attention to porous cut edges. Let it dry and smooth raised fibres as the product directs; test the edge finish before coating the whole piece.'},solid:{name:'Bare solid wood',prep:'Check for knots, resin and surface defects. Fill where appropriate and sand with the grain using the coating system’s recommended preparation. Remove dust.',prime:'Choose a wood primer compatible with your topcoat and species. Knots and tannin-prone timber may need a specific stain-blocking treatment.'},laminate:{name:'Laminate / melamine',prep:'Confirm the surface is securely bonded. Clean off grease and residue without soaking seams. Do not sand through the decorative layer; follow the bonding system’s surface-preparation directions.',prime:'Select a bonding primer explicitly approved for your exact laminate or melamine. Test the complete system on a hidden area and allow the specified cure time before checking adhesion.'},painted:{name:'Previously painted wood',prep:'Identify the existing coating and check adhesion. Before disturbing older or unknown paint, resolve lead or other hazardous-coating concerns. Clean and repair sound surfaces; do not paint over loose coating.',prime:'Use a compatible primer on bare repairs and stains, or across the surface if your chosen system requires it. Test for lifting, wrinkling and poor adhesion before proceeding.'}};
export const methods={brush:'Brush / roller',spray:'Sprayer',aerosol:'Aerosol can'};
export const finishSources=[['Surface preparation · Sherwin-Williams','https://www.sherwin-williams.com/en-us/project-center/paint/how-to-paint-prep'],['Cabinet paint application · Rust-Oleum','https://rustoleumsupport.zendesk.com/hc/en-us/articles/18513705255949-Cabinet-Transformations-Basics-Cabinet-and-Trim-Paint']];
export function normalizeFinish(f={}){return {system:['paint','clear','undecided'].includes(f.system)?f.system:'paint',surface:surfaces[f.surface]?f.surface:'plywood',method:methods[f.method]?f.method:'brush',colour:String(f.colour||'').slice(0,100),sheen:['matte','satin','semi-gloss','gloss'].includes(f.sheen)?f.sheen:'satin',notes:String(f.notes||'').slice(0,2000)};}
export function finishingSteps(raw){const f=normalizeFinish(raw),s=surfaces[f.surface];if(f.system==='undecided')return [['Choose the finish first','Record whether you want an opaque colour or visible wood grain, then select a compatible coating system before buying preparation products.']];if(f.system==='clear')return [['Confirm the clear-finish system','Choose a product approved for the actual surface and intended use. The paint-primer steps do not apply to this selection.'],['Test before finishing the project','Use an offcut of the same material to review appearance and compatibility. Follow the selected product’s preparation, application, ventilation and cure instructions; record its reference below.']];return [
['Prepare the surface',s.prep],['Prime and test',s.prime],
['Set up your tools',f.method==='brush'?'Use the brush bristle type and roller sleeve specified by the coating maker. Mask glue faces, hardware seats and areas that must remain uncoated. Support pieces so you can reach edges.':f.method==='spray'?'Confirm the coating is suitable for your sprayer. Use its specified tip/nozzle, pressure and thinning limits; do not invent a universal setting. Provide suitable ventilation, overspray containment and protection specified by the coating SDS and equipment manual. A dust mask is not vapour protection. Avoid ignition sources; two-component/isocyanate finishes are outside this DIY guide.':'Choose an aerosol approved for the prepared substrate. Follow the can’s shaking, distance, temperature and recoat instructions. Control overspray, keep away from ignition sources and use the ventilation and protection required on the label.'],
['Apply controlled coats',f.method==='brush'?'Work in manageable sections, keeping a wet edge. Apply the specified film thickness and avoid repeatedly brushing paint that has started to set. Check corners for runs.':'Practise on scrap first. Move in even, parallel passes at the product’s specified distance and overlap; avoid building up paint at edges. For powered sprayers, follow the manual’s trigger-lock and pressure-release procedure before clearing or cleaning the equipment.'],
['Dry, inspect and cure','Use the actual product’s recoat window and environmental limits. Smooth between coats only when its instructions call for it. Dry-to-touch is not fully cured: wait the specified handling and service times before assembly, stacking or loading shelves.']];}
export const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function finishHTML(raw){const f=normalizeFinish(raw);return `<section><h2>Prep &amp; finish</h2><p>${f.system} · ${surfaces[f.surface].name} · ${methods[f.method]} · ${escapeHTML(f.colour||'Colour to choose')} · ${f.sheen}</p><p>Finishing selection only; the bookcase construction remains plywood. Confirm the coating label and SDS before work.</p><ol>${finishingSteps(f).map(([a,b])=>`<li><strong>${a}</strong><p>${b}</p></li>`).join('')}</ol>${f.notes?`<h3>Customization brief — not applied to drawings</h3><p>${escapeHTML(f.notes)}</p>`:''}<p>${finishSources.map(([name,url])=>`<a href="${url}">${name}</a>`).join(' · ')}</p></section>`;}
