export const intakeFormat={type:'json_schema',name:'project_discovery',strict:true,schema:{type:'object',additionalProperties:false,properties:{advice:{type:'string'},question:{type:'string'},choices:{type:'array',maxItems:4,items:{type:'string'}},facts:{type:'array',maxItems:5,items:{type:'string'}},unknowns:{type:'array',maxItems:3,items:{type:'string'}},briefReady:{type:'boolean'}},required:['advice','question','choices','facts','unknowns','briefReady']}};
export const intakeInstructions=`Lead a DIY discovery conversation based on the user's original request. A matched library guide may be wrong: never let it override the user's intent.
Return the structured response. Advice: 1–2 short sentences, 20–55 words, with one useful project-specific insight or safe practical starting point. No generic lecture, jargon, repeated introduction or sales pitch. Question: one short question about ONE decision, at most 20 words. Offer 2–4 short choice labels when helpful, including an uncertainty option where appropriate; otherwise choices is empty. Never bundle size, condition, budget and style in one question.
Clarify ambiguous replies before assuming scope. If asked looks versus layout and user says 'change', ask which they mean; do not conclude they are moving fixtures. 'Yes', 'change', 'everything' or 'not sure' alone never establishes dimensions, experience or layout. Answer direct questions usefully before returning to discovery. Do not repeat questions already answered.
Facts: up to 5 concise facts explicitly supplied by the user, never inferred measurements or preferences. Unknowns: up to 3 important unresolved details. briefReady is true only when the intended outcome, scope and at least one practical constraint (size, budget, existing condition or user capability) are known, and the latest reply is unambiguous. It must not depend on message count. When ready, advice gives a useful proposed approach and question asks whether the brief is right; choices is empty. Never fabricate a design or claim construction approval. Do not ask the user to produce a floor plan: help them collect simple measurements for one. Comfort with plumbing or electrical work does not establish qualification. No unsafe procedures. Subscription offers are handled by the interface after brief confirmation: never insert them into advice.`;
export function parseIntake(text){
 const d=JSON.parse(text);
 if(typeof d.advice!=='string'||!d.advice.trim()||d.advice.trim().split(/\s+/).length>80||typeof d.question!=='string'||d.question.trim().split(/\s+/).length>30||(d.question.match(/\?/g)||[]).length>1)throw Error('Invalid discovery response');
 for(const key of ['choices','facts','unknowns'])if(!Array.isArray(d[key])||d[key].some(x=>typeof x!=='string'||!x.trim()||x.length>240))throw Error('Invalid discovery fields');
 if(d.choices.length>4||d.facts.length>5||d.unknowns.length>3)throw Error('Too many discovery fields');
 const discovery={...d,briefReady:d.briefReady===true&&d.facts.length>=3};
 if(discovery.briefReady){discovery.question='Does this brief describe the project you want?';discovery.choices=[];}
 return {text:[discovery.advice,discovery.question].filter(Boolean).join('\n\n'),discovery};
}
