// Practical, non-invasive checks for library topics that are not universal repair recipes.
// Model-specific work remains a separate, explicitly identified next step.
const s=(title,visual,tools,spec,action,check)=>({title,visual,tools:tools.split('|'),spec,action,check});
const b=(need,steps)=>({need,steps});
export const libraryChecks={
 'leaking-pipe':b('Leak location, pipe material and an accessible shutoff',[
 s('Find the first wet point','plumbing','Flashlight|Phone','Supply pipe, waste pipe or appliance hose','From a dry, safe position, look above the visible drip: water can travel along a pipe before falling. Photograph the first wet joint and the wider arrangement.','You can point to the first visible wet area, not just the puddle.'),
 s('Separate a drip from an emergency','plumbing','No repair tools yet','Continuous flow versus water only during drainage','If water is near electricity, stay out and use urgent help. If a familiar shutoff is safely reachable from dry ground, close it; do not force a seized valve.','Water is controlled or professional help has been arranged.'),
 s('Match the repair to the pipe','parts','Pipe markings|Photos','Material, fitting type and size from markings','Record copper, plastic or another identified material and any printed size. Send a clear joint photo and symptoms to the plumber or supplier; do not buy a push-fit connector from appearance alone.','The proposed part and repair method match the identified pipe system.')]),
 'running-toilet':b('Toilet model, tank water level and when refilling occurs',[
 s('Look inside the tank','toilet','Phone|Dry towel','Water level relative to the overflow tube','For a conventional exposed cistern, lift the loose lid carefully and place it on a padded surface. Photograph the tank parts and any model stamp. Do not open concealed mechanisms.','You have the model and a clear view of the fill and flush parts.'),
 s('Watch one refill','toilet','Clock or phone','Continuous filling or occasional restart','Observe without adjusting anything. Water reaching the overflow suggests a fill/level issue; intermittent refilling with no external leak may involve the flush seal. These observations narrow the check rather than prove the cause.','You know whether filling stops and whether water reaches the overflow.'),
 s('Choose the matching service part','parts','Model’s parts diagram','Fill valve versus flapper or canister seal','Match the actual flush mechanism and part number. Locate the working toilet shutoff before any service; a stiff or leaking valve needs attention first.','The part is confirmed for this toilet, not just labelled “universal”.')]),
 'dripping-faucet':b('Brand/model, handle type and exact leak location',[
 s('Locate the drip','faucet','Dry cloth|Phone','Spout, handle base or underneath the sink','Wipe accessible surfaces dry. With the tap closed normally, watch where water first appears. Look underneath from a dry position without moving pipework.','You can distinguish a spout drip from a supply or base leak.'),
 s('Identify the faucet','faucet','Phone|Existing paperwork','Brand, model and number of handles','Photograph the whole faucet, logo and any accessible label. Note whether the handle lifts, turns or uses separate hot/cold controls. Use those details to find the manufacturer’s parts drawing.','You have a model or enough identification photos for the manufacturer.'),
 s('Confirm the cartridge and shutoffs','parts','Official parts diagram','Exact cartridge or seal number; hot/cold orientation','For example, Moen cartridges vary by model and date and are not interchangeable. Confirm the exact part and service instructions; verify both supply shutoffs before disassembly.','A matching part and a safe isolation method are known.')]),
 'slow-drain':b('Affected fixtures, standing water and any chemicals already used',[
 s('Check how widespread it is','plumbing','Notes|Phone','One drain versus several fixtures','Note which sinks, shower or toilet are slow and whether water backs up elsewhere. Several affected fixtures or sewage needs a plumber, not repeated treatment of one trap.','You know whether this is local to one fixture.'),
 s('Inspect the accessible strainer','plumbing','Gloves|Fixture manual','Removable strainer or stopper type','If no drain chemicals have been used, remove only a user-removable strainer as the fixture manual describes and collect visible hair or debris. Do not force a concealed mechanism or reach blindly into a drain.','The accessible opening is clear without opening pipework.'),
 s('Check flow without overflowing','plumbing','Small amount of water','Drain response after the accessible clean','Run a small amount of water while watching the basin. Stop before it backs up. If it stays slow, give a plumber the fixture list and names of any chemicals used.','Flow improved, or the next service action is clear.')]),
 'pex-line':b('Fixture, route, tubing system and plumbing design',[
 s('Draw the proposed route','room','Tape|Paper','Route length, bends and accessible connections','Sketch the fixture and existing supply. Measure the accessible route and label obstacles; do not cut or open the supply to identify it.','A plumber can see where the proposed line would run.'),
 s('Record the system markings','parts','Phone|Manufacturer literature','Tubing standard and fitting method','Photograph tubing and fitting markings. PEX expansion, crimp and clamp systems need compatible tubing, fittings and tools; colour alone does not establish compatibility.','The proposed system is identified by markings and documentation.'),
 s('Get a complete installation specification','record','Route sketch|Fixture information','Sizing, supports, bends, insulation and pressure test','Have a qualified plumber confirm the layout, local permits, exact parts and test method. Ask for those values on the plan before buying a tool or cutting pipe.','The project has an installation and test plan, not only a pipe length.')]),
 showerhead:b('Connection type, included washer and condition of the wall arm',[
 s('Check the existing arm','faucet','Phone|Dry cloth','Corrosion, cracking or movement at the wall','Look at the shower arm and connection without twisting it. A moving wall arm or leak at the wall needs repair before fitting a new head.','The arm appears fixed and the leak location is known.'),
 s('Read the new head’s sealing detail','parts','New head instructions','Washer seal versus threaded seal','Lay out the supplied washer and parts. Some heads seal with a washer and do not call for thread tape; use the exact head’s instructions rather than adding tape automatically.','You know which part makes the watertight seal.'),
 s('Use the model’s fitting sequence','faucet','Tools specified by the head manufacturer','Tightening method and leak check','With the shower off, follow the model’s removal and fitting instructions. Support the connection as instructed, never force the wall arm, then test briefly and inspect the joint.','No joint leak or movement; stop if either appears.')]),
 'sink-trap':b('First wet joint, trap arrangement and chemical-use history',[
 s('Clear a safe view','plumbing','Flashlight|Dry cloth|Shallow tray','Do not disturb suspect chemicals or wiring','Remove stored items only if the area is safe. Dry the outside of accessible drain parts; position a tray without moving pipes.','You can see the connections and the area remains dry and safe.'),
 s('Observe a small drainage test','plumbing','Phone','Basin outlet, slip joint or trap body','If no chemical exposure or overflow risk exists, drain a small amount of clean water and watch which exterior point becomes wet first. Stop immediately if water spreads.','A photo identifies the first leak point.'),
 s('Match parts before opening anything','parts','Photos|Drain model information','Pipe size, washer shape and joint arrangement','Take a wide photo and close-up to a plumbing supplier. Different joint seals are not interchangeable; do not smear sealant onto every threaded connection as a default repair.','A matching part and safe service method are established.')]),
 'water-shutoffs':b('Known main and fixture shutoff locations',[
 s('Make a room-by-room map','room','Phone|Paper','Main, kitchen, bathroom and laundry valves','Locate familiar accessible valves without removing service covers or touching utility-owned equipment. Photograph each with its surrounding area.','Another person can locate each valve from the photo.'),
 s('Label without forcing valves','record','Tags|Pen','Fixture served and access route','Add a clear label to known valves. Record seized, leaking or unfamiliar valves for a plumber; do not force them to test the map.','Labels distinguish verified locations from valves needing assessment.'),
 s('Keep the map accessible','record','Household contact list','Utility and plumber contact details','Save the map where the household can find it offline. Include who to call when safe access or valve operation is uncertain.','Everyone knows where the map is and when to call for help.')]),
 'gfci-trip':b('Device type, moisture/damage and whether trips repeat',[
 s('Check for danger first','electrical','No tools','Dry access; no heat, scorch, water or damaged casing','Keep covers on. If there is moisture, heat, burning or damage, do not touch or reset the device; use urgent electrical help.','There is no reason to approach a hazardous device.'),
 s('Identify the protection device','electrical','Phone|Device instructions','GFCI/RCD outlet or breaker; affected equipment','Read visible labels from a safe position and list what lost power. Photograph the front only, without opening any cover.','The device and affected equipment are recorded.'),
 s('Follow its user reset instructions','electrical','Owner instructions','A reset is not a repair for repeated tripping','Use only the documented test/reset procedure if conditions are safe. If it will not reset or trips again, stop using affected equipment and arrange an electrician.','Normal operation resumes once, or the problem is referred for investigation.')]),
 'dead-outlet':b('Which outlets/lights failed and any visible hazard',[
 s('Keep the faceplate on','electrical','Phone','Heat, scorch, looseness or moisture','Do not insert test objects or remove covers. Record visible damage from a safe distance; heat, smoke or water requires urgent help.','The inspection has not exposed live parts.'),
 s('Map the outage','room','Paper|Phone','One outlet, a room or several rooms','List affected lights and outlets and when the outage began. Note any safely visible GFCI/RCD device involved.','You have a clear symptom map for the electrician.'),
 s('Arrange the right service','record','Symptom map','Repeated trip, damaged device or unexplained failure','Use only documented owner controls where safe. Leave outlet replacement, wiring tests and panel work to qualified help.','The electrician has useful observations without DIY wiring exposure.')]),
 'flickering-light':b('Lamp, bulb and dimmer models; one light or several',[
 s('Observe the pattern','electrical','Notes','Single lamp versus multiple circuits','Note whether flickering occurs only when dimmed or when another appliance starts. Burning, heat or widespread changes need an electrician.','The conditions that trigger flickering are recorded.'),
 s('Match the bulb and dimmer','parts','Model labels|Compatibility list','Dimmable bulb, base type and fixture wattage limit','With the light off and cool, read only accessible labels. Check whether the exact LED bulb is listed for the dimmer; “LED” alone does not prove compatibility.','The bulb/dimmer combination is documented.'),
 s('Stay within user maintenance','electrical','Fixture manual','User-replaceable bulb only','Follow the fixture manual for replacing an accessible bulb with a compatible one. Do not open a switch or fitting; persistent flicker needs service.','The symptom resolves or is passed on with model details.')]),
 'light-fixture':b('Fixture weight, environment and existing support',[
 s('Measure the intended position','room','Tape|Floor plan','Drop, clearances and room location','Measure from the floor or another safe accessible position. Note doors, cabinets and anything the new light could obstruct.','The proposed light fits the space.'),
 s('Record the fixture requirements','parts','Product sheet','Weight, environment rating and control type','Keep the exact model, assembly sheet and dimmer information. Do not assume the old ceiling support can carry a heavier fitting.','The installer has the fixture specifications.'),
 s('Have support and wiring verified','mount','Qualified installer','Support, supply, controls and local requirements','Give the installer the model and location notes. They must verify mounting support and electrical compatibility before installation.','The plan includes support and electrical work, not only the decorative fitting.')]),
 'smart-switch':b('Switch, bulb and control arrangement',[
 s('List what the switch controls','electrical','Notes','Bulb models and number of control locations','Count control points and note whether the circuit includes a fan or other equipment. Do not remove the wall plate to look for wires.','The controlled loads and locations are known.'),
 s('Check the product compatibility list','parts','Smart-switch product sheet','Load type, dimming and network requirements','Compare exact bulb models and the switch’s stated load types. Verify your home network meets the device requirements before buying.','The chosen device is suited to the intended function.'),
 s('Verify wiring with an installer','electrical','Qualified electrician','Neutral, multi-way arrangement and box suitability','Have the required wiring and installation conditions checked by an electrician. Wire colour or the old switch’s shape is not proof of compatibility.','The installation is confirmed before purchase or wiring work.')]),
 'outdoor-lighting':b('Location, exposure and complete lighting system',[
 s('Map light positions','room','Tape|Site sketch','Path, planting and access routes','Mark the areas needing light and the proposed cable route. Include wet areas, mowing and any route people cross.','The layout shows both lighting and access needs.'),
 s('Choose one compatible system','parts','System instructions','Outdoor rating, transformer capacity and connectors','Specify whether it is solar, plug-in low voltage or hardwired. Do not mix connectors or assume low voltage removes all outdoor electrical requirements.','Components belong to a compatible rated system.'),
 s('Confirm supply and ground work','electrical','Qualified installer where required','Protected supply and buried-cable requirements','Have supply and protection verified. Clear underground services and use the system’s cable-routing rules before any trenching or stakes.','The installation route and supply requirements are known.')]),
 'basement-finishing':b('Room dimensions, moisture conditions and intended use',[
 s('Sketch the existing space','room','Tape|Paper','Length, width, ceiling obstructions and openings','Draw the outside walls and mark columns, stairs, windows, drains and equipment access. Measure headroom to the lowest obstruction and include units.','The sketch records the space that is actually usable.'),
 s('Record conditions before covering walls','inspect','Phone|Notebook','Damp areas, staining and access needs','Photograph visible dampness and note when it occurs. Do not hide it behind insulation or drywall. Keep service access and existing ventilation shown on the sketch.','Moisture and access issues are visible in the project brief.'),
 s('Develop the layout with the required checks','room','Measured sketch|Local permit information','Room use, escape routes, structure and services','Place the intended rooms on the sketch. Have permit, egress, moisture, structural and service requirements checked before treating a partition drawing as buildable.','The next design can use measured inputs and identified constraints.')]),
 'large-drywall-patch':b('Damage dimensions, panel type and concealed services',[
 s('Measure the damaged area','inspect','Ruler|Phone','Full extent of damaged paper and board','Photograph the wall and measure across all damaged material. Note moisture and whether this is a fire/sound-rated wall. Do not enlarge the opening yet.','The repair size and wall conditions are recorded.'),
 s('Plan support and panel matching','patch','Panel information|Repair-system instructions','Board thickness, backing and joint system','Match the original board and approved wall assembly. A loose patch needs specified backing; filler alone is not a replacement for missing board.','The patch has a support and jointing method.'),
 s('Clear the cutting area first','mount','Service-location assessment','Wiring, plumbing and framing behind the patch','Confirm what is behind every proposed cut. Follow the selected repair system once hazards and services are resolved, or arrange a drywall professional.','No cut depends on guessing what is inside the wall.')]),
 'drywall-seam':b('Whether the crack is stable, dry and a failed taped joint',[
 s('Record the crack','inspect','Ruler|Phone','Width, location and dated comparison','Photograph with a ruler and note whether it reappears, grows or is accompanied by sticking doors. Do not cover continuing movement.','You have a record that distinguishes recurring damage.'),
 s('Check the tape and wall condition','patch','Flashlight','Loose tape, moisture or sound surrounding board','Inspect the visible surface with side lighting. Softness, dampness or movement needs investigation before a cosmetic retape.','The cause has been addressed or referred for assessment.'),
 s('Choose a complete joint repair system','parts','Tape and compound instructions','Paper/mesh tape and compatible compound','Match the compound to the chosen tape; they are not all interchangeable. Plan thin, tapered coats, drying and a separate primer over the repair.','The repair plan includes tape, compound, finishing and paint.')]),
 'drywall-anchor':b('Load, wall construction and damage around the failed hole',[
 s('Remove the load safely','mount','Helper if needed|Phone','Weight and condition of the mounted item','Keep people clear of an unstable shelf or fitting. Support/remove its load safely rather than pulling on the failed anchor to test it.','The loose fixing is not carrying an unattended load.'),
 s('Measure and identify the wall','inspect','Ruler|Wall information','Damaged area and actual backing','Photograph the hole and bracket and record the intended loaded weight. Locate sound backing and concealed services before considering a new fixing position.','The new support will not rely on crumbled board.'),
 s('Select the whole fixing arrangement','mount','Rated fixing instructions','Wall type, bracket geometry and installed load','Choose fixings for sound material or verified framing and the complete load. Filling the old hole does not restore its original anchor capacity.','The replacement design has suitable backing and specified fixings.')]),
 'drywall-sheet':b('Room, panel type, framing and required wall/ceiling assembly',[
 s('Measure a sheet layout','room','Tape|Paper','Surface dimensions and framing positions','Sketch sheet joints and openings. Plan where sheet edges land rather than simply dividing wall area by sheet area.','The layout identifies edge support and cuts.'),
 s('Select the right panel system','parts','Manufacturer assembly details','Thickness, moisture exposure and fire/sound rating','Match the required assembly, including framing, fasteners, joint materials and spacing. A thicker board alone does not establish a fire rating.','All components match the required assembly.'),
 s('Plan safe lifting and fastening','mount','Suitable lifting equipment|Helper','Sheet weight, access and service clearance','Arrange support for sheets, especially overhead. Resolve concealed services and copy the fixing schedule from the approved assembly before installation.','Handling and fixing are planned before sheets arrive.')]),
 'wall-crack':b('Dated photos, movement symptoms and moisture',[
 s('Take a repeatable photograph','inspect','Ruler|Phone','Crack location and visible width','Put a ruler beside the crack without disturbing it. Photograph a wider view so the same point can be found later.','The photo provides both location and scale.'),
 s('Record related changes','room','Notebook','Doors, windows, displacement and dampness','Note nearby sticking doors, unevenness, leaks and when the crack appeared. A new coat of filler cannot diagnose the cause.','The observations can be compared over time.'),
 s('Choose assessment before concealment','record','Photos|Building professional if needed','Rapid change, displacement or uncertain cause','Get significant, growing or unexplained cracking assessed. Only plan a cosmetic repair after the wall and cause are understood.','The next action addresses the cause rather than hides a symptom.')]),
 'wall-texture':b('Existing texture, coating and repair size',[
 s('Photograph in side light','inspect','Lamp|Phone|Ruler','Pattern size, height and sheen','Take a close-up and a wider photo with light coming across the wall. Record the size of the patch and existing coating.','The finish is visible as a pattern, not only a colour.'),
 s('Make a sample panel','patch','Scrap board|Chosen texture system','Texture tool, consistency and drying interval','Practise the identified texture on scrap using the product directions. Let it dry before deciding whether peaks and spacing match.','The dry sample matches closely enough before work starts on the wall.'),
 s('Prime and paint the sample','paint','Matching primer and wall paint','Final colour and sheen in room lighting','A raw texture sample can look different after painting. Test the complete finish, then decide how far to repaint to avoid a visible patch.','The finished sample is accepted in the lighting where it will be seen.')]),
 'peeling-paint':b('Surface material, moisture pattern and existing coating',[
 s('Map where paint is failing','inspect','Phone|Notes','Peeling, bubbles, damp patches or stains','Record whether failure clusters near plumbing, windows or exterior walls. Do not start dry scraping unknown old paint.','The pattern and possible moisture connection are recorded.'),
 s('Resolve the cause','drainage','Appropriate moisture/building assessment','Leak, dampness or coating incompatibility','Repair active moisture and let the substrate recover before coating. Soft or damaged material may need replacement rather than another primer.','The surface is sound and the cause is controlled.'),
 s('Test a compatible repair finish','prime','Identified coating system','Safe preparation, primer and topcoat','Once old-material hazards are resolved, test the proposed preparation and full coating on a small area. Observe its stated adhesion/drying interval.','The new finish stays attached before the full area is repainted.')]),
 'caulk-bath':b('Joint material, old seal type and signs of water damage',[
 s('Check the joint before removal','caulk','Flashlight|Phone','Loose surfaces, soft edges and recurring leaks','Inspect the joint and nearby surfaces. If tiles move or backing feels damaged, investigate waterproofing before treating it as a cosmetic seal replacement.','The joint is sound enough for routine resealing.'),
 s('Choose the right sealant','parts','Bath/shower sealant label','Compatibility, joint width and water-exposure cure time','Choose a sanitary sealant approved for the actual bath, tile and joint. Record the bead and cure guidance; general decorator’s caulk is not the default shower seal.','The product is intended for this wet joint and its materials.'),
 s('Prepare and seal continuously','caulk','Safe removal tool|Caulk gun|Masking tape','Clean, dry joint and label bead size','Remove failed seal without damaging the waterproofing, clean and dry as the product directs, then apply a continuous bead and tool it once. Keep water away for the full stated cure interval.','No gaps remain and the joint has cured before shower use.')]),
 'loose-tile':b('Location, neighbouring damage and waterproofing involvement',[
 s('Protect the loose area','pavers','Phone','Floor trip, falling tile or sharp edges','Keep use away from a loose or broken tile. Record its location without prying at neighbouring tiles.','People are not relying on the damaged surface.'),
 s('Map the surrounding symptoms','inspect','Ruler|Photos','Cracked joints, soft backing and water exposure','Photograph several tiles around the fault and note recent leaks or movement. One replacement tile will not solve a failing substrate.','The repair scope includes adjacent symptoms.'),
 s('Identify the installation system','parts','Tile/adhesive information','Substrate, adhesive, grout and waterproofing','Have wet-area or substrate damage assessed before removal. Match replacement tile size and thickness, but also the underlying installation system.','The repair restores the system rather than only the visible tile.')]),
 'floor-scratch':b('Floor product, finish and scratch depth',[
 s('Clean and inspect gently','clean','Soft cloth|Approved floor cleaner','Scuff on top versus a cut through the finish','Use the floor maker’s cleaner on a hidden test area and inspect when dry. A transferred scuff may clean away; a deep cut needs another method.','You know whether material is missing or only marked.'),
 s('Identify the floor construction','parts','Product records|Exposed edge if already accessible','Solid wood, veneer, laminate or vinyl','Find the manufacturer and collection if possible. Do not sand to identify it: laminate print and thin wear layers can be destroyed.','The repair method matches the actual floor.'),
 s('Use the matching repair method','paint','Manufacturer repair kit','Colour, sheen and permitted preparation','Test the maker’s compatible touch-up or repair product where inconspicuous. Deep damage or an unknown wear layer needs a flooring specialist.','The test blends without damaging adjacent finish.')]),
 backsplash:b('Wall dimensions, tile sizes, sockets and heat/water exposure',[
 s('Draw the wall face','room','Tape|Paper','Length, height, sockets and appliance edges','Measure each wall run and mark outlets and corners. Include the exact tile dimensions and intended joint width in the layout.','Cuts can be planned before ordering tile.'),
 s('Dry-lay a sample row','parts','Sample tiles|Spacers|Straightedge','Actual tile size plus grout joint','Lay a row on a protected flat surface. Shift the starting point to avoid awkward slivers at visible ends; account for movement joints in the chosen system.','The pattern and end cuts have been reviewed.'),
 s('Specify the complete wall system','mount','Tile-system instructions','Substrate, adhesive, grout and appliance clearance','Match adhesive and grout to the tile and exposure. Plan electrical changes with an electrician and follow appliance clearance requirements before tiling around them.','The layout and installation materials are compatible.')]),
 'sticking-door':b('Ordinary interior door, contact point and hinge condition',[
 s('Find where it catches','hinge','Flashlight|Paper strip','Top, hinge edge, latch edge or latch only','Close gently and stop at the first resistance. Look for a fresh rub mark and compare the gap around the door. If it swings freely but the latch misses, record that separately.','You can identify the contact without forcing the door.'),
 s('Check visible hinge screws','hinge','Correctly fitting hand screwdriver','Ordinary interior door only; no material removal','With the door open and stable, snug a visibly loose screw a little at a time while keeping hinges attached. Test after each adjustment. Stop if a screw spins or wood is damaged.','The screw holds and the door moves normally, or the repair needs further assessment.'),
 s('Recheck before trimming','seal','Notes|Photos','Seasonal change, frame movement or persistent rubbing','Compare the gap again. Do not start planing a door because tightening did not solve it. Note any frame cracks or sudden movement and get those assessed.','The next action is based on the remaining contact and cause.')]),
 'squeaky-hinge':b('Hinge type, looseness and finish-compatible lubricant',[
 s('Locate the noisy hinge','hinge','Soft cloth','Noise during opening versus latch contact','Move an ordinary door slowly and listen from a safe position. Check visible loose screws or damage without removing hinge pins.','You know whether the sound comes from the hinge.'),
 s('Choose a suitable lubricant','parts','Hinge maker’s maintenance advice','Lubricant type and protection of the finish','Match the product to the hinge maker’s guidance. Protect nearby painted surfaces and keep spray off floors; unfamiliar spring/fire hinges need specialist maintenance.','The lubricant and maintenance method suit this hardware.'),
 s('Apply a small controlled amount','hinge','Approved lubricant|Cloth','Only the specified lubrication point','Apply sparingly as directed, move the door gently to distribute it and wipe away excess. Persistent grinding or looseness needs repair, not more lubricant.','The door moves quietly without oily residue or loose hardware.')]),
 'window-draft':b('Draft location, seal profile and window condition',[
 s('Locate the air path','seal','Paper strip|Notes','Moving sash joint versus frame-to-wall joint','From safe indoor access, compare gaps and damaged seals around the closed window. Note water staining or rot separately. Do not use a flame to find a draft.','The likely leaking joint is identified.'),
 s('Record the seal profile','parts','Phone|Window information','Brand, seal shape and attachment method','Photograph the seal and any model label. A generic thick strip may prevent proper closure or block designed drainage.','A supplier can match the correct profile.'),
 s('Preserve drainage and safe closure','seal','Exact replacement instructions','Weep openings, locks and glazing remain unobstructed','Use the window system’s approved seal method. Loose glass, rot, failed locks or water entry needs assessment before cosmetic sealing.','The window closes normally and intended drainage is open.')]),
 'dryer-vent':b('Dryer model, user-accessible lint path and visible exhaust condition',[
 s('Notice the warning signs','appliance','Notes','Longer drying, unusual heat or burning smell','Stop the dryer for burning or abnormal heat and arrange service. Record whether drying time recently increased and when the lint filter was last cleaned.','Potential fire symptoms are not treated as a routine cleaning task.'),
 s('Clean the user-accessible lint screen','filter','Owner manual|Soft brush if specified','Switch off/cool down and exact screen removal','Follow the manual to remove and clean the accessible lint screen. Do not reach into powered equipment or push tools into unseen internals.','The screen is clean and correctly refitted.'),
 s('Inspect visible exhaust from safe access','drainage','Phone','Crushed duct, lint accumulation or obstructed outlet','Look at accessible ducting and the outdoor outlet from ground level. Inaccessible duct cleaning, disconnection or appliance movement needs a suitable service plan.','The next maintenance task and safe access are identified.')]),
 'washer-hoses':b('Hose condition, compatible replacement and safe shutoff access',[
 s('Inspect accessible hose surfaces','hose','Flashlight|Phone','Bulges, rubbing, cracks or corrosion','Look without pulling the machine or twisting fittings. Photograph deterioration and keep clear of water near electrical equipment.','The visible condition and leak location are recorded.'),
 s('Identify the appliance and connection','parts','Owner manual|Model label','Hose type, connector and any leak-stop device','Match the washer’s approved hose requirements. Do not choose a replacement by length alone.','The replacement fits the machine and supply connection.'),
 s('Plan safe replacement access','appliance','Helper or service provider','Working shutoffs and heavy-appliance access','Have seized/leaking valves addressed first. Follow the appliance’s isolation and hose-change instructions or arrange service where access is unsafe.','No hose is opened while pressurised or with unsafe access.')]),
 'dishwasher-drain':b('Model, error code and whether the sink also backs up',[
 s('Record the symptom','appliance','Phone','Error code and amount/location of standing water','Stop the cycle as the owner manual describes. Photograph the error and note whether the connected sink is also slow; do not repeatedly start cycles into an overflow.','The fault information is preserved.'),
 s('Check only the owner-accessible filter','filter','Manual|Gloves if specified','Filter removal and hot-water precautions','Follow the model’s safe shutdown and filter-cleaning steps. Do not open pump/electrical covers or reach blindly into areas that may contain glass.','The accessible filter is cleaned and refitted correctly.'),
 s('Test as the manual directs','appliance','Owner troubleshooting guide','Drain test and stop conditions','Use the documented test only when overflow risk is controlled. Persistent standing water or a shared sink blockage needs service with the model and error details.','The dishwasher drains normally or service has the required clues.')]),
 'fridge-seal':b('Door obstruction, gasket condition and exact appliance model',[
 s('Check what prevents closure','appliance','No tools','Food, drawers, shelves and door alignment','Remove anything obstructing the door and check drawers are fully seated. Do not assume a gap means the gasket needs replacing.','The door can reach its normal closed position.'),
 s('Clean and inspect the gasket','clean','Soft cloth|Manual-approved cleaner','Dirt, folds, tears and separated corners','Clean the accessible gasket folds gently and dry them. Avoid harsh solvents or heating the gasket without the maker’s procedure.','The visible seal is clean and any damage is recorded.'),
 s('Match a replacement if needed','parts','Model/serial label','Exact gasket and retention method','Use the appliance model to select the seal and fitting instructions. Similar dimensions do not prove a magnetic profile or corner shape will fit.','A replacement is confirmed for this fridge.')]),
 'bath-fan':b('Model, accessible cover and whether the issue is dust, noise or weak extraction',[
 s('Record the symptom','appliance','Notes|Phone','Noise, condensation, visible dust or failure to run','Note when the symptom occurs. Burning, electrical damage or abnormal heat needs service; do not remove a live cover to investigate.','The problem is described without opening electrical parts.'),
 s('Use the model’s owner-cleaning method','filter','Owner manual|Specified cleaning tools','Safe isolation and cover-only access','Follow the manual’s shutdown and cover-removal procedure. Clean only the parts identified for owner maintenance; keep water away from the motor and wiring.','Accessible dust is removed and the cover is securely refitted.'),
 s('Check normal operation','appliance','Owner manual','Vent route and persistent moisture symptoms','Restore operation as instructed. Persistent poor extraction may involve the duct or fan and needs assessment rather than repeated cover cleaning.','The issue is resolved or a service task is clearly defined.')]),
 'fence-panel':b('Panel size, post condition and boundary/site constraints',[
 s('Identify what has failed','inspect','Phone|Tape','Panel, rail, post or footing movement','Keep clear of unstable sections. Photograph both supports and the panel; a replacement panel will not repair a loose post.','The failed component is distinguished from sound parts.'),
 s('Measure a matching replacement','measure','Tape|Panel system details','Clear span, height and fixing arrangement','Record measurements with units and compare the manufacturer’s actual sizes. Include access and neighbouring panels in the sketch.','The replacement fits the existing system.'),
 s('Resolve support before fitting','mount','Appropriate contractor or complete system','Post support, fixings and utility clearance','Confirm boundary arrangements and underground services before any post work. Use the selected system’s support and fastening method.','The panel will be held by sound, correctly specified supports.')]),
 'deck-inspection':b('Visible movement, decay and coating condition',[
 s('Inspect from safe access','inspect','Phone|Flashlight','Loose rails, soft boards and corrosion','Stay off any suspect area. Photograph visible damage without leaning on a loose rail or probing a structural connection.','The inspection has not loaded an unsafe part.'),
 s('Separate structure from finish','parts','Notes','Sound boards versus failed support or connections','List movement/rot separately from faded stain. Structural issues need an appropriate deck professional before any cleaning or coating.','A finish is not being used to hide a safety defect.'),
 s('Plan a finish test only on sound wood','paint','Identified coating|Test area','Deck wood, existing finish and product preparation','After the deck is confirmed sound, select an exterior decking coating and test the maker’s preparation in a small area. Interior cabinet paint is not a decking substitute.','The coating plan suits the actual deck material and use.')]),
 'gutter-check':b('Where water overflows and where downspouts discharge',[
 s('Observe from the ground','drainage','Phone|Binoculars if useful','Overflow location, sag and detached joints','Watch only in safe weather and from firm ground. Photograph the gutter run and downspout without using a ladder for this check.','You have a location-specific record.'),
 s('Trace visible discharge','drainage','Site sketch','Water route away from buildings and paths','Record where each downspout releases water and any pooling. Do not redirect water onto neighbouring property.','The downstream problem is included in the observations.'),
 s('Arrange cleaning or repair with safe access','record','Photos|Service contact','Blockage versus slope, joint or support problem','Give the service provider the photos and locations. Specify whether inspection of joints/supports is needed as well as debris removal.','The requested service addresses the observed problem.')]),
 'yard-drainage':b('Rainfall timing, pooling locations and nearby buildings',[
 s('Map where water collects','room','Phone|Site sketch','Pool locations and visible inflow/outflow','After safe access is possible, mark wet areas and photograph them from the same points. Include downspouts and neighbouring levels.','The map shows the pattern, not only one puddle.'),
 s('Keep a dated record','record','Clock|Notes','How long water remains after rainfall','Record rain timing and how long the area stays wet. Note whether it happens only in exceptional rain or after ordinary watering.','A drainage adviser has useful timing information.'),
 s('Choose a site-specific remedy','drainage','Local drainage professional','Outfall, soil, grading, permissions and utilities','Do not dig a trench or soakaway based only on the wet spot. Have a lawful discharge route and ground/service conditions checked first.','The remedy has somewhere appropriate to send the water.')]),
 'hose-leak':b('Hose washer, coupling or fixed tap leak',[
 s('Locate the leak','faucet','Dry cloth','Coupling, hose body or fixed wall fitting','Turn the water off normally and inspect the visible connection. A leak at a moving wall tap needs a plumber; keep it separate from an ordinary hose coupling drip.','The leaking component is identified.'),
 s('Inspect the hose washer','parts','Matched hose washer','Washer size and sound coupling threads','With the supply off and pressure released, disconnect only the ordinary accessible hose coupling. Inspect its rubber washer and replace a damaged one with a matching washer.','The washer lies flat and the coupling is undamaged.'),
 s('Reconnect and test gently','hose','Hands; tools only if specified','Washer seal rather than extra force','Reconnect as the coupling maker directs and turn water on slowly. If it still leaks, stop and inspect the parts; do not force or twist the fixed tap.','The coupling seals without stressing wall plumbing.')]),
 'lawn-bare-patch':b('Grass type, sunlight and cause of the bare area',[
 s('Find why grass is missing','plants','Phone|Notes','Traffic, shade, dryness, puddling or pests','Compare the patch with healthy nearby grass and record recent changes. Reseeding alone will not fix constant foot traffic or standing water.','The likely site problem is included in the repair plan.'),
 s('Select locally suitable seed or turf','parts','Local lawn guidance|Product label','Grass species, season and label sowing rate','Match the existing grass and climate. Measure patch area before buying and use the actual seed label rate instead of guessing handfuls.','The product and timing suit the site.'),
 s('Prepare and establish as a small test','soil','Rake|Chosen seed or turf|Watering equipment','Seed depth, firm contact and establishment moisture','Follow the selected grass system’s preparation and watering method. Keep traffic off and monitor moisture at the seed/soil interface.','The repair is establishing rather than drying out or washing away.')]),
 'sunken-pavers':b('Low-spot dimensions, recurring water and movement',[
 s('Mark the uneven area','pavers','Straightedge|Ruler|Phone','Height difference at the trip and repair boundary','Keep users away from the trip. From stable access, photograph the straightedge across the low area with a ruler showing the difference.','The extent and height change are documented.'),
 s('Look for the cause','drainage','Notes|Photos after rain','Drainage, roots, washout or repeated settlement','Record recurring puddles, root uplift and open edges. Do not simply add sand on top of an unresolved base problem.','The repair plan includes why the area moved.'),
 s('Restore the complete paving system','pavers','Paver-system specification','Base, bedding, edge restraint and joint material','Have the required repair layers and drainage established. Match the existing units and levels; use the system’s compaction and reinstatement method.','The repaired surface has support and drainage, not only a level top.')]),
 'paver-joints':b('Paver type, joint dimensions and current joint material',[
 s('Identify the existing joints','pavers','Ruler|Phone','Joint width/depth and paver surface','Measure a representative joint and record existing sand or mortar. Note weeds, loose pavers and water problems separately.','The supplier can identify a compatible jointing product.'),
 s('Check the product conditions','parts','Jointing-product instructions','Minimum depth, dry weather window and permitted pavers','Do not assume any polymeric sand suits every gap or surface. Record the product’s preparation and weather limits before opening the bag.','The installation conditions match the selected material.'),
 s('Test cleanup and activation','pavers','Specified broom/tools|Small test area','Face cleanup before the stated water/activation step','Follow the exact system sequence. Residue left on paver faces may harden or haze; do not improvise the amount of water.','The test joints are filled and faces remain clean after drying.')])
};
