import {projects} from './catalog.mjs';
import {contentFor,contentLabel} from './project-content.mjs';
export const guideType=p=>contentFor(p.id)?.level||(p.category==='safety'?'safety':'outline');
export const guideTypeLabel=p=>contentFor(p.id)?contentLabel(p.id):p.category==='safety'?'Safety guide':'Check & plan';
const contentRank=p=>({procedure:4,design:3,system:2,safety:1,outline:0}[guideType(p)]);
export const categories=[
['woodworking','Woodworking & storage','▤'],['plumbing','Plumbing & water','◉'],['electrical','Electrical & lighting','ϟ'],['drywall','Drywall & walls','▧'],['finishes','Paint, tile & floors','▦'],['doors','Doors, windows & hardware','▥'],['maintenance','Home maintenance','⚙'],['yard','Yard & landscaping','♧'],['pavers','Pavers & patios','▦'],['garden','Planting & garden beds','❧'],['safety','Urgent issues & safety','△']
].map(([id,name,symbol])=>({id,name,symbol}));
export const modeNames={make:'Make or install',fix:'Troubleshoot',maintain:'Maintain',urgent:'Urgent help'};
// Planning briefs have task-specific preparation. They are not installation instructions.
const batches={
plumbing:[
['leaking-pipe','A leaking pipe','fix','drip burst copper supply leak','Identify where water is escaping and how urgent it is.','Record the visible location and flow, from a dry, safe position.','Locate a familiar, accessible water shutoff; operate it only if safe. Arrange repair of the identified leak.'],
['running-toilet','A toilet that keeps running','fix','cistern flapper tank refill flush','Separate a refill issue from water leaking onto the floor.','Record the toilet model and whether filling is continuous or intermittent.','Find the model’s parts diagram and identify the fill valve or flush seal before ordering parts.'],
['dripping-faucet','A dripping faucet','fix','tap cartridge washer mixer sink','Match the repair to the faucet type.','Identify the brand and whether the drip is at the spout or base.','Confirm the service manual, replacement part and access to a working shutoff before disassembly.'],
['slow-drain','A slow sink or shower drain','fix','clog clogged blocked blockage trap','Determine whether one fixture or several drains are affected.','Record standing water, affected fixtures and any drain chemicals already used.','Use the fixture’s accessible strainer maintenance instructions. Never mix drain chemicals; tell a plumber about products used.'],
['pex-line','Plan a new PEX water line','make','pex tubing expansion crimp cinch pipe plumbing','Prepare a system-specific plan before cutting into a supply.','Record location, fixture, route, existing pipe and exact tubing and fitting system.','Confirm local requirements and manufacturer compatibility, sizing and test procedures with a qualified plumber.'],
['showerhead','Replace a showerhead','make','shower head hose bathroom','Check the connection and existing fitting first.','Identify the connection type and look for corrosion or movement at the wall arm.','Use the fixture instructions for sealing and tightening; stop if the wall connection moves.'],
['sink-trap','Inspect an under-sink drain leak','fix','p trap waste drain underneath sink','Find the visible source before replacing drain parts.','Observe whether water starts at the basin, trap or connection during drainage.','Photograph the arrangement and identify parts. Avoid disassembly where drain chemicals have been used.'],
['water-shutoffs','Map your water shutoffs','maintain','main stopcock isolation valve meter','Make a household reference for isolating water.','Locate known fixture and main shutoffs without disturbing utility equipment.','Label accessible valves and have a plumber assess seized or unfamiliar ones.']
],
electrical:[
['gfci-trip','A tripped GFCI outlet or breaker','fix','gfci gfi rcd tripped trip reset socket receptacle','Identify the device and conditions around the trip.','From a dry, safe position, note the device type, affected equipment and any moisture or damage.','Consult the device’s test/reset instructions. Repeated trips need an electrician; do not bypass protection or keep resetting.'],
['dead-outlet','An outlet has stopped working','fix','socket receptacle no power dead plug','Record the extent of the outage without opening fittings.','Note which lights and outlets are affected and whether a GFCI is involved.','Give an electrician the symptom list. This brief does not cover exposed wiring or panel work.'],
['flickering-light','A flickering light','fix','lamp bulb dimmer flicker led','Distinguish a single lamp issue from a wider problem.','Record lamp and dimmer models and whether other lights flicker.','Check lamp/dimmer compatibility. Follow the fixture manual for user-replaceable bulbs.'],
['light-fixture','Plan a light-fixture replacement','make','ceiling pendant chandelier lighting','Check support, fixture and control requirements.','Record fixture weight, location and mounting arrangement without exposing wiring.','Check manufacturer instructions and local rules with a qualified installer before work.'],
['smart-switch','Check smart-switch compatibility','make','wifi dimmer switch neutral home automation','Confirm the proposed control suits the lighting system.','Collect device and lamp models and the known switching arrangement.','Have wiring requirements and load compatibility verified; wire color alone does not identify its function.'],
['outdoor-lighting','Plan outdoor lighting','make','garden landscape lights low voltage','Choose a complete system for the environment.','Record wet exposure, cable routes and whether the system is plug-in, low voltage or hardwired.','Use an outdoor-rated system and have supply, protection and buried-cable requirements checked.']
],
drywall:[
['basement-finishing','Plan finishing a basement','make','basement frame framing stud partition finishing remodel renovation','Work out the room layout and scope before choosing materials.','What would you like to do: frame walls, finish the whole basement, or create a particular room?','Record the intended rooms, approximate dimensions and existing conditions. Confirm moisture, permits and service requirements before producing a construction plan.'],
['small-wall-hole','Patch a small drywall hole','make','plasterboard nail screw hole spackle filler','Match the patch method to the hole and wall.','Identify wall material, hole dimensions and signs of moisture.','Select a repair system rated for the hole size and follow its preparation, drying and finishing instructions.'],
['large-drywall-patch','Plan a larger drywall patch','make','plasterboard sheetrock hole damage panel','Plan support and finishing before cutting the wall.','Measure damage and identify hidden services and the wall’s fire or acoustic requirements.','Choose a suitable backing and panel system; confirm what is behind the wall before any cutting.'],
['drywall-seam','Repair a cracked drywall seam','fix','joint tape compound seam crack','Check whether a failed joint is stable before retaping.','Record crack location, repeat movement and any moisture.','Identify the cause and compatible tape/compound system before planning a cosmetic repair.'],
['drywall-anchor','Fix a pulled-out wall anchor','fix','plug screw drywall anchor loose mounting','Reassess the support rather than filling and reusing a failed hole.','Record the load, wall type, bracket and hole damage.','Choose a rated fixing design for sound material or verified framing; check concealed services before drilling.'],
['drywall-sheet','Plan hanging drywall sheets','make','sheetrock plasterboard ceiling sheets panels','Choose panels and handling methods for the room.','Record framing, moisture exposure, fire rating and sheet dimensions.','Use the panel manufacturer’s fixing and joint guidance; arrange safe lifting and verify services first.'],
['wall-crack','Understand a wall crack','fix','plaster structural movement crack','Document movement before hiding a symptom.','Photograph the crack with a scale and note sticking doors, displacement or dampness.','Keep dated observations and get an appropriate building assessment if the cause is uncertain.'],
['wall-texture','Match a textured wall repair','make','texture orange peel knockdown skim','Test the finish before committing to a visible patch.','Identify existing texture, coating and repair dimensions.','Practice the chosen compatible system on a sample; match lighting and finish before applying to the wall.']
],
finishes:[
['paint-room','Plan painting a room','make','wall ceiling primer roller decorating','Create a surface-specific preparation and coating plan.','Measure paintable area and identify existing coating, dampness and damage.','Check coverage and compatibility and follow label instructions for preparation, ventilation and curing.'],
['peeling-paint','Investigate peeling paint','fix','flaking bubbling blister damp paint','Find moisture or adhesion problems before recoating.','Record the pattern, location and whether the surface is damp.','Identify the coating and underlying cause; test a compatible preparation system before repainting.'],
['caulk-bath','Renew a bath or shower seal','maintain','silicone caulking bathtub mildew','Check the substrate before replacing a failed seal.','Inspect for loose surfaces, soft material and recurring leakage.','Use a sealant approved for the joint and materials; follow removal, cleaning and cure instructions.'],
['loose-tile','Assess a loose or cracked tile','fix','ceramic grout floor bathroom tile','Check whether movement or water is causing the failure.','Record neighboring cracks, soft areas and whether waterproofing is involved.','Identify the underlying system before removal; get damaged waterproofing or substrate assessed.'],
['floor-scratch','Treat a scratched floor','maintain','wood laminate vinyl scuff flooring','Match the repair to the actual floor finish.','Identify the product, scratch depth and whether the surface is veneer, laminate or solid timber.','Use the manufacturer’s care or repair method and test in an inconspicuous area.'],
['backsplash','Plan a kitchen backsplash','make','splashback kitchen wall tile','Plan layout, substrate and appliance clearances.','Measure the area and record sockets, heat sources and wet exposure.','Choose an approved system and plan cuts and movement joints; arrange electrical alterations separately.']
],
doors:[
['sticking-door','A door that sticks','fix','rubbing binding hinge jamb','Locate the contact before trimming anything.','Note where the door rubs, when it started and whether the frame has moved.','Check hardware adjustment guidance and seasonal effects before irreversible material removal.'],
['squeaky-hinge','Quiet a squeaky hinge','maintain','squeak creak lubricant door','Use maintenance suited to the hinge and finish.','Identify the hinge type and any loose or damaged components.','Follow the hardware maker’s cleaning and lubrication method; do not dismantle unfamiliar spring hinges.'],
['weatherstrip','Replace door weatherstripping','maintain','draft draught gap seal door','Match the seal without preventing closure.','Measure the existing profile and identify threshold and latch arrangement.','Fit a compatible profile and check closure; fire-door seals need approved replacements.'],
['door-handle','Replace a door handle','make','knob latch lock hardware','Match replacement hardware to the door.','Record thickness, backset, bore, handing and lock function.','Use the hardware template and test the latch with the door open; preserve fire and exit requirements.'],
['window-draft','Trace a window draft','fix','draught air leak window gasket','Find the failing seal or joint.','Inspect visible seals and gaps without removing glazing.','Match replacement seals to the window system; get rot, loose glass or water entry assessed.'],
['curtain-rail','Install a curtain rail','make','rod blind curtain bracket','Choose supports for the wall and load.','Record span, curtain weight, substrate and intended fixing points.','Use a rated bracket and fixing system and establish concealed-service locations before drilling.']
],
maintenance:[
['hvac-filter','Replace an HVAC filter','maintain','furnace air conditioner ac filter','Match the replacement to the equipment.','Record model, filter dimensions and airflow direction.','Follow the manual for safe access and approved specification; avoid service compartments.'],
['dryer-vent','Check dryer airflow','maintain','lint tumble dryer duct vent','Recognize restriction and plan accessible maintenance.','Record slow drying, visible lint and vent routing.','Clean user-accessible components as directed by the manual; arrange service for inaccessible ducts.'],
['washer-hoses','Inspect washing-machine hoses','maintain','washer laundry hose washing leak','Spot wear before a hose fails.','Look at accessible hoses for bulging, abrasion and corrosion.','Identify compatible replacements and safe shutoff access; avoid moving heavy equipment without help.'],
['dishwasher-drain','A dishwasher will not drain','fix','dishwasher water standing filter blocked','Collect model-specific clues before maintenance.','Record model, error codes and whether the sink is also affected.','Use the manual’s user-accessible filter checks; leave pump and electrical disassembly to service.'],
['fridge-seal','Check a refrigerator door seal','maintain','fridge gasket condensation refrigerator','Check closure and gasket condition.','Look for debris, tears, gaps and obstructions from stored items.','Follow the manual’s cleaning method and confirm the exact replacement gasket if needed.'],
['bath-fan','Maintain a bathroom extractor fan','maintain','exhaust ventilation humidity fan','Separate cover cleaning from motor or wiring work.','Record model, noise, condensation and visible dust.','Follow user-maintenance instructions for safe access; arrange service for motor or electrical issues.'],
['seasonal-check','Make a seasonal home checklist','maintain','annual spring winter autumn fall checklist','Build a routine around your climate and equipment.','List filters, detectors, drainage, seals, shutoffs and service dates.','Schedule manufacturer-recommended checks and keep manuals and service records together.']
],
yard:[
['fence-panel','Plan a fence-panel repair','make','fence loose timber boundary yard','Check supports before replacing a panel.','Record damaged rails, posts and the boundary arrangement.','Match the panel system and verify support; locate services before any post excavation.'],
['deck-inspection','Inspect a deck before refinishing','maintain','deck decking rot railing stain','Check condition before coating the surface.','From a safe position, note softness, movement, loose rails and corrosion.','Get structural concerns assessed before cleaning or finishing sound surfaces.'],
['gutter-check','Inspect gutter drainage','maintain','gutter downspout overflow rain','Find visible problems from ground level.','Observe overflow, sagging and discharge direction during safe conditions.','Document the problem and arrange safe cleaning or repair without roof access.'],
['yard-drainage','Understand a soggy yard','fix','yard drainage standing water puddle grading lawn','Identify the pattern before changing drainage.','Record where water collects, rainfall timing and proximity to foundations.','Discuss grading and drainage options with a local professional; do not divert water onto neighboring property.'],
['hose-leak','A leaking garden hose connection','fix','hose bib spigot washer tap','Separate a hose seal from a fixed-plumbing leak.','Note whether water starts at the hose coupling, hose body, tap or wall.','Match accessible hose replacement parts; get a moving or leaking wall fitting checked by a plumber.'],
['garden-storage','Plan a garden storage box','make','outdoor storage box weatherproof','Design around weather and the items stored.','Record dimensions, exposure, ventilation and contents.','Use an exterior design with suitable lid support; follow storage requirements for any hazardous contents.'],
['lawn-bare-patch','Repair bare patches in a lawn','maintain','grass lawn seed turf bare patch','Identify the cause before adding seed or turf.','Record sunlight, soil moisture, traffic and the existing grass type.','Use locally suitable grass and seasonal guidance; correct the underlying conditions before reseeding.']
],
pavers:[
['paver-patio','Plan a paver patio','make','pavers paving stone patio backyard','Scope the layout and site before buying materials.','Measure the area and identify slope, soil, drainage, intended loads and buried services.','Use a paver manufacturer’s base and edge-restraint design suited to the site; verify drainage and local requirements.'],
['paver-path','Plan a garden paver path','make','pavers walkway path stepping stone','Lay out an accessible route with stable support.','Record width, transitions, drainage and intended foot traffic.','Plan the base, edges and surface levels as a complete system; check utilities before digging.'],
['sunken-pavers','Assess sunken or uneven pavers','fix','sinking uneven paver trip settling','Find settlement or drainage causes before resetting.','Map low spots, movement, nearby roots and recurring water.','Identify base failure and drainage needs before planning removal and reinstatement.'],
['paver-joints','Refresh paver joints','maintain','joint sand polymeric paving weeds','Match joint maintenance to the paving system.','Identify paver type, joint width, existing fill and drainage.','Use compatible joint material and follow its weather, application and cleanup instructions.'],
['patio-clean','Plan patio cleaning','maintain','paving concrete stone pressure washing moss','Choose a method that protects the surface and joints.','Identify material, coating, joint condition and runoff route.','Test the manufacturer-approved cleaning method in a small area and protect nearby surfaces and plants.'],
['paver-edging','Plan edging for a paver area','make','edge restraint border patio paving','Keep the paving system restrained at its edges.','Record the paver system, base, surrounding ground and expected loads.','Choose a compatible edge-restraint design and manufacturer-specified fixings; check services before ground work.']
],
garden:[
['raised-bed','Build a raised planting bed','make','raised garden planting beds vegetable soil','Plan a bed for drainage, access and filled weight.','Measure the space, sunlight, irrigation access and intended plants.','Choose a suitable design and materials, calculate soil volume and verify the supporting surface.'],
['in-ground-bed','Create an in-ground planting bed','make','planting garden flower bed soil ground','Prepare a planting area around site conditions.','Record sunlight, drainage, existing vegetation and soil condition.','Locate buried services, test soil where useful, and choose a locally appropriate preparation and planting plan.'],
['bed-edging','Add garden-bed edging','make','planting bed border edge landscape','Define the bed without interfering with drainage.','Measure the perimeter, slopes, mower access and nearby roots.','Select suitable edging, plan curves and transitions, and check buried services before installation.'],
['mulch-bed','Mulch a planting bed','maintain','mulch bark compost planting weeds','Select mulch suited to the plants and site.','Identify the plants, existing mulch, drainage and irrigation.','Use locally appropriate horticultural guidance for material and depth; avoid piling material against trunks or stems.'],
['drip-irrigation','Plan drip irrigation','make','drip watering irrigation garden beds hose','Match a watering layout to plant and supply needs.','Map beds, plants, supply source and pressure requirements.','Choose a compatible system and verify backflow protection and local requirements before connecting to a water supply.'],
['plant-selection','Choose plants for a garden bed','make','flowers shrubs planting sun shade plants','Match plants to your actual growing conditions.','Record location, sun hours, soil moisture, mature-space limits and pets or children.','Check local growing guidance, mature size, toxicity and invasive status before choosing plants.'],
['garden-trellis','Plan a garden trellis','make','climbing plant trellis support garden','Design support for the mature plant and exposure.','Record plant weight, wind exposure, attachment location and dimensions.','Use a suitable design and support system; verify wall fixings or buried services before installation.']
],
safety:[
['basement-flood','A flooded basement','urgent','flood flooding standing water sewage sump basement','Safety comes before cleanup or buying equipment.','Observe only from a dry, safe location; consider electricity, contamination and structural damage.','Stay out of water that may contact electrical equipment. Get emergency or utility help when needed and qualified assessment before cleanup.'],
['ceiling-leak','Water coming through a ceiling','urgent','ceiling dripping upstairs roof leak bulging','Keep people clear of overhead water damage.','From a safe position, note sagging, falling material and nearby lights or wiring.','Keep away from the affected area and arrange urgent assessment. Do not puncture or stand under a sagging ceiling.'],
['sewage-backup','A sewage backup','urgent','sewer toilet overflow wastewater contaminated','Treat wastewater as a contamination problem.','Observe affected fixtures from outside the contaminated area.','Keep people and pets away and contact plumbing or restoration help; avoid using affected fixtures.'],
['burning-outlet','Burning smell or heat at an outlet','urgent','hot socket burning scorch spark smoke electrical','Treat heat, smoke or burning as an electrical hazard.','Keep clear; record symptoms only if safe.','Stop using affected equipment. For smoke, fire or immediate danger, leave and contact emergency services; otherwise seek urgent electrical help.'],
['frozen-pipe','A suspected frozen pipe','fix','freezing winter pipe no water frozen','Consider the possibility of a split before thawing.','Record affected fixtures, cold exposed areas and visible leaks.','Get a plumber if the location, shutoff or condition is uncertain. Never use a flame to thaw a pipe.'],
['water-damage-record','Document water damage safely','maintain','insurance damage photos flood leak','Create a record only after access is confirmed safe.','Note dates, affected rooms and visible damage from safe locations.','Photograph accessible damage and keep service records; contact your insurer about documentation requirements.']
]};
const cautions={plumbing:'Stop for uncontrolled water, corroded or inaccessible connections, sewage, or water near electricity. Use qualified plumbing help when the cause or repair is uncertain.',electrical:'Do not open electrical fittings or work on wiring using this brief. Water, heat, burning, sparks or repeated tripping needs qualified help; immediate danger needs emergency assistance.',drywall:'Resolve dampness or movement first. Check hidden services and potentially hazardous old materials before cutting, drilling or sanding.',finishes:'Identify old coatings and materials before disturbance. Follow product ventilation and protection instructions; resolve moisture and substrate damage first.',doors:'Do not compromise fire doors, emergency exits, glazing or security requirements. Structural movement needs assessment.',maintenance:'Stay within the manufacturer’s user-maintenance instructions. Electrical, gas, sealed-system or inaccessible work requires qualified service.',yard:'Check buried utilities before digging. Avoid unsafe ladder or roof work. Unstable structures or work near power lines needs professional help.',pavers:'Check buried utilities before excavation. Drainage, retaining structures and vehicle loads require a suitable site-specific design.',garden:'Locate buried utilities before digging. Verify structural support for heavy beds on decks or balconies, and suitability of planting materials.',safety:'Immediate danger takes priority over troubleshooting. Use local emergency services when needed. Do not enter unsafe, flooded or contaminated areas to gather information.'};
const sources={
'gfci-trip':['CPSC: GFCI fact sheet','https://www.cpsc.gov/safety-education/safety-guides/electronics-and-electrical-home/gfci-fact-sheet'],
'pex-line':['Uponor: Design and installation manuals','https://www.uponor.com/en-ca/customer-support/order-manuals'],
'basement-flood':['CDC: Reentering a flooded home','https://www.cdc.gov/floods/safety/reentering-your-flooded-home-safety.html']};
const briefs=Object.entries(batches).flatMap(([category,rows])=>rows.map(([id,title,mode,keywords,summary,observe,next])=>({id,title,mode,keywords,summary,observe,next,category,kind:'brief',stop:cautions[category],source:sources[id]})));
export const library=[...projects.map(p=>({id:p.id,title:p.name,category:p.id==='planter'?'garden':p.id==='paint-cabinets'?'finishes':p.id==='trim'?'doors':'woodworking',mode:p.id==='refinish'?'maintain':'make',kind:'plan',summary:p.subtitle,keywords:[p.id,p.name,p.note].join(' '),projectId:p.id})),...briefs];
// Normalize vocabulary before scoring; title matches carry more weight than context.
const filler=new Set('i a an the my our is are has have there it its to for of in on under with and want would like need help me can how do what should get please some new build make plan fix properly at not wont t s'.split(' '));
const forms={sticking:'stick',sticks:'stick',stuck:'stick',rubs:'stick',rubbing:'stick',rub:'stick',jammed:'stick',jamming:'stick',binding:'stick',leaking:'leak',leaks:'leak',dripping:'leak',drips:'leak',flooded:'flood',flooding:'flood',tripped:'trip',tripping:'trip',paving:'paver',pavers:'paver',beds:'bed',doors:'door',windows:'window',shelves:'shelf',planting:'plant',plants:'plant',broken:'break'};
export function searchTerms(text){return [...new Set(text.toLowerCase().replace(/won[’']?t close|will not close|doesn[’']?t close/g,' stick ').replace(/[^a-z0-9]+/g,' ').split(' ').filter(t=>t&&!filler.has(t)).map(t=>forms[t]||(t.length>4&&t.endsWith('s')?t.slice(0,-1):t)))];}
function score(p,terms){const title=searchTerms(p.title),body=searchTerms(p.summary+' '+p.keywords),cat=searchTerms(categories.find(c=>c.id===p.category)?.name||'');return terms.reduce((n,t)=>n+(title.includes(t)?8:body.includes(t)?3:cat.includes(t)?1:0),0);}
export function searchLibrary({query='',category='all',mode='all',kind='all'}={}){const terms=searchTerms(query);return library.filter(p=>(category==='all'||p.category===category)&&(mode==='all'||p.mode===mode)&&(kind==='all'||(['plan','brief'].includes(kind)?p.kind===kind:guideType(p)===kind))&&(!terms.length||score(p,terms)>0)).sort((a,b)=>score(b,terms)-score(a,terms)||contentRank(b)-contentRank(a)||a.title.localeCompare(b.title));}
// Suggest near spellings only in the fallback; never silently call them exact matches.
function near(a,b){if(a.length<4||b.length<4||Math.abs(a.length-b.length)>1)return false;const d=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++){d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));if(i>1&&j>1&&a[i-1]===b[j-2]&&a[i-2]===b[j-1])d[i][j]=Math.min(d[i][j],d[i-2][j-2]+1);}return d[a.length][b.length]<=1;}
export function closestGuides(query){const terms=searchTerms(query);const similarity=p=>score(p,terms)+terms.reduce((n,t)=>n+(searchTerms(p.title+' '+p.keywords).some(w=>near(t,w))?2:0),0);const ranked=[...library].sort((a,b)=>similarity(b)-similarity(a)||(b.kind==='plan')-(a.kind==='plan'));return {guides:ranked.slice(0,3),category:similarity(ranked[0])>0?ranked[0].category:null};}
