// Planning workbooks: no claim of a reviewed construction design.
const rows=[
['cabinet-doors','Woodworking & storage','Replace cabinet fronts while keeping the existing boxes.','What are each opening’s dimensions and required overlay?','Which hinge model, cup pattern and door thickness are required?','Door blanks|Compatible hinges and handles','Measure each opening independently and label it on a sketch.|Confirm hinge geometry, clearances and door weight before ordering fronts.|Make or order one sample front and check its fit before repeating the set.','Hinge and door specifications verified','Keep sound cabinet boxes and compare custom-cut fronts with making every door.'],
['drawers','Woodworking & storage','Plan drawer boxes around the chosen slide hardware.','What is the clear opening width, height and usable depth?','Which slide system and load rating will you use?','Drawer-box material|Matched slides and fixings','Select the slide model before setting drawer dimensions.|Subtract clearances from the exact hardware instructions; account for the drawer front.|Review bottom support, squareness and load requirements before producing a cut list.','Slide clearances and bottom support reviewed','Standardize drawer sizes where possible to reduce offcuts and hardware variety.'],
['workbench','Woodworking & storage','Set up a stable workspace for the jobs you actually do.','What work, vice loads and equipment must the bench support?','What footprint, working height and access space are available?','Reviewed bench frame and top|Compatible hardware','Map your working area and check access around the proposed bench.|Choose a bench design rated for the intended loads and clamping operations.|Confirm top thickness, bracing and fixing details before ordering material.','Stability and load requirements reviewed','Compare a rated ready-made base with building a frame; use replaceable top surfaces.'],
['planter','Garden & yard','Plan a freestanding outdoor planter and its soil load.','What outside footprint and growing depth do you need?','Where will the filled planter stand and drain?','Outdoor-suitable timber|Compatible hardware and growing medium','Record the support surface and intended plants.|Select an exterior design that accounts for wet-soil loads and drainage.|Confirm material suitability for the growing use, then calculate internal soil volume.','Wet-soil load and support surface reviewed','Use standard stock lengths and compare delivered soil volumes.'],
['garden-storage','Garden & yard','Plan dry, accessible storage for garden equipment.','What equipment dimensions and clearance are needed?','How will the lid, ventilation and drainage work?','Exterior-rated enclosure materials|Suitable hinges and lid supports','Measure the largest items and sketch access around the enclosure.|Choose an outdoor storage design with a safe lid-support arrangement.|Plan a stable base and water shedding before sizing panels.','Lid safety and weather detailing reviewed','Match the box to the equipment you own rather than building unused capacity.'],
['garden-trellis','Garden & yard','Choose a trellis layout for the plant and exposure.','What mature plant size and weight are expected?','Will it be freestanding or fixed to a wall?','Outdoor-suitable trellis system|Site-appropriate supports','Record plant needs, wind exposure and access for maintenance.|Select a support system suited to the mature plant and installation location.|Resolve fixing or ground-support details before ordering the trellis.','Supports checked for wind and mature plant loads','Buy modular panels that can expand as the plant grows.'],
['in-ground-bed','Garden & yard','Turn a planting area into a measured garden plan.','What area, sunlight and existing plants are present?','What soil and drainage conditions do you have?','Site-appropriate soil amendments|Selected plants','Map the bed and observe sunlight and drainage.|Arrange service locating before ground disturbance and assess soil before choosing amendments.|Lay out plants at their mature spacing before purchasing quantities.','Site services and plant suitability checked','Test soil before buying amendments you may not need.'],
['bed-edging','Garden & yard','Choose edging that fits the bed shape and maintenance routine.','How long is the boundary and what curves are needed?','Will the edge meet lawn, soil or a paved surface?','Compatible edging system|System fixings','Measure the full route including corners and joins.|Choose an edging system suited to the adjoining surfaces and climate.|Check underground services and follow the selected system’s ground preparation details.','Services and ground-preparation requirements checked','Compare cost per installed length including connectors and stakes.'],
['drip-irrigation','Garden & yard','Prepare a zone plan before buying irrigation fittings.','Which plants and bed lengths need water?','What water source and available supply information do you have?','Compatible tubing and emitters|Specified filtration and backflow protection','Map beds, water needs and the proposed supply route.|Choose a complete system and confirm local backflow requirements with a qualified installer.|Use the system’s design method to size zones, then count fittings from the layout.','Supply compatibility and backflow requirements resolved','Separate plants with different water needs to avoid wasting water.'],
['plant-selection','Garden & yard','Build a plant list that suits the actual site.','What sunlight, climate and soil conditions apply?','What mature height, maintenance and pet constraints matter?','Site-suitable plants|Appropriate soil amendments if indicated','Record sun exposure and existing site conditions.|Shortlist plants for the local climate and check mature size and toxicity where relevant.|Lay out mature spacing and compare nursery sizes and total quantities.','Mature spacing and site suitability checked','Smaller plants often cost less; allow time and space for their growth.'],
['paver-patio','Pavers & patios','Plan a pedestrian patio with drainage and delivery in mind.','What footprint, thresholds and furniture clearances are needed?','What soil, drainage and climate conditions apply?','Chosen paver system|Specified base, bedding and edging','Draw the footprint with nearby structures and level constraints.|Arrange utility locating and review drainage and base design for the site.|Calculate system quantities from the chosen pattern and schedule deliveries and equipment.','Excavation, drainage and base specification reviewed','Compare full delivered installation materials, not only the paver unit price.'],
['paver-edging','Pavers & patios','Plan restraint repairs around an existing paved area.','Where is the edge moving and why?','What paver, base and restraint system is present?','Compatible restraint|System fixings and replacement bedding','Map loose edges and inspect visible settlement without excavating services.|Identify the original system and determine whether base movement needs correction first.|Specify compatible replacement restraints and installation details.','Underlying movement assessed','Repair the cause before replacing the same edging repeatedly.'],
['patio-clean','Pavers & patios','Select a cleaning method that protects the surface and joints.','What surface, sealer and jointing material are present?','What stains and drainage restrictions apply?','Surface-compatible cleaner|Runoff protection','Identify the paving and any existing sealer.|Use the surface and cleaner manufacturers’ compatibility guidance and test an inconspicuous area.|Plan runoff control and follow the approved cleaning method without washing out joints.','Cleaner compatibility and runoff considered','Try the approved mild method before renting aggressive equipment.'],
['paint-cabinets','Paint & finish','Plan a cabinet repaint with preparation and curing time built in.','Are the faces wood, MDF, laminate or previously coated?','Will you brush, roll or spray, and where can parts dry?','Compatible cleaning, primer and coating system|Masking and labelling supplies','Label doors and hardware and identify the existing surface.|Test the complete preparation and coating system on a hidden area.|Schedule coating and full cure time before handling, refitting and service.','Coating compatibility and ventilation confirmed','Retain sound hinges and handles unless the design needs a change.'],
['refinish','Paint & finish','Assess a furniture finish before choosing a restoration approach.','What material and existing finish are present?','Are you preserving grain or switching to an opaque colour?','Compatible preparation system|Chosen finish','Check veneer thickness, damage and old-coating hazards before disturbance.|Test the proposed cleaning and finishing system on a hidden area.|Plan hardware removal, dust control and drying space before starting.','Material and existing finish assessed','A clean and compatible refresh may avoid stripping the entire piece.'],
['trim','Walls & repairs','Measure trim runs and plan joints and finishes.','What wall lengths, corners and profiles need covering?','What substrate and concealed services affect fixing?','Matched trim profile|Compatible fixings and finish','Record each run, corner type and profile on a labelled sketch.|Plan joints and cut allowances using actual stock lengths.|Resolve fixing locations and finish preparation before cutting.','Profiles, joints and fixing locations confirmed','Optimize cuts across the whole room instead of buying for each wall separately.'],
['curtain-rail','Home maintenance','Plan a rail installation around the window and wall.','What curtain weight, width and projection are required?','What wall substrate and fixing locations are available?','Rated rail and brackets|Substrate-appropriate fixings','Measure the opening and desired curtain coverage.|Select a rail system for the curtain weight and bracket spacing.|Locate services and confirm suitable wall support before drilling.','Rail rating and wall fixings checked','Choose a complete compatible rail kit to avoid mismatched brackets.'],
['door-handle','Home maintenance','Match replacement door hardware before removing anything.','What backset, door thickness and existing hole pattern do you have?','Is the door fire-rated, exterior or part of an escape route?','Compatible handle and latch set|Manufacturer-specified fixings','Identify the door type and record current hardware dimensions.|Choose compatible replacement hardware; specialist doors need their approved specification.|Follow the hardware maker’s replacement and function-check process.','Door suitability and hardware dimensions confirmed','Match the existing hole pattern to avoid unnecessary door repairs.'],
['hvac-filter','Home maintenance','Record the correct filter and maintenance schedule.','What equipment model and filter size are specified?','What filter type and access procedure does the manual require?','Equipment-approved filter|Date label','Locate the equipment manual and identify the filter specification.|Follow its shutdown and access procedure; do not open electrical compartments.|Fit the specified filter in its marked airflow direction and record the date.','Filter specification and access instructions checked','Compare multipack prices for the exact approved filter, not an unsuitable higher rating.'],
['seasonal-check','Home maintenance','Create a repeatable home-maintenance checklist.','What climate, season and property features matter?','Which equipment manuals and service dates do you already have?','Labels and maintenance records|Replacement consumables identified during review','List visible inspection tasks by room and exterior area.|Separate safe ground-level checks from work needing a trade or access equipment.|Record findings, service dates and priorities rather than ordering everything at once.','Urgent defects separated from routine maintenance','Schedule related service visits together where practical.']
];
export const morePacks=rows.map(([id,category,summary,q1,q2,materials,sequence,check,savings])=>({id,category,summary,questions:[q1,q2,'What tools, materials and budget do you already have?'],materials:materials.split('|'),tools:['Measuring and recording tools','Task-specific equipment confirmed after assessment'],sequence:sequence.split('|'),checks:[check,'Materials and quantities reviewed before purchase'],savings}));
