import {contentSources} from './content-sources.mjs';
const step=(title,action,check)=>({title,action,check});
const guide=(level,scope,stop,sources,steps)=>({version:'2026-09-24.1',level,scope,stop,sources,steps});
// Original task instructions. System-dependent packs deliberately stop short of inventing hardware or structural specifications.
export const projectContent={
 'bookcase':guide('design','A freestanding indoor plywood bookcase within the drawing controls. Fixed shelves and an applied 6 mm back.','Do not cut or load from this draft until material grade, joints, back fastening, loads and wall restraint have been specified.',['bookcase','screws','anchor'],[
 step('Measure the actual space','Measure the narrowest available width, height and depth. Include skirting boards, wall lean and the route into the room. Record the heaviest intended contents and where they will sit.','The cabinet fits the room and can be moved into position.'),
 step('Match the sheet material','Measure the plywood thickness; identify the product and grade. Check the back is actually 6 mm. Choose a face and grain direction for every part before asking a supplier to cut it.','Thickness matches the drawing and there are no unreviewed substitutions.'),
 step('Resolve the construction details','Open the drawing checks. Obtain a joint and fastener schedule, back fixing pattern, shelf-load assessment and anti-tip fixing specification for this exact size. A separate Kreg plan can be followed unchanged instead of treating it as approval of this model.','A competent reviewer has addressed the unresolved construction details.'),
 step('Use the measured assembly sequence','Once the construction details are resolved, label the parts and follow the illustrated sequence. Dry-fit before fastening. Use the common bottom datum shown in the shelf schedule, not a chain of rounded gaps.','Cut list, datum marks and selected joint details all refer to the same revision.'),
 step('Finish, restrain and hand over','Follow the selected finish system through its full cure. Install the specified furniture restraint into the identified wall structure. Record permitted use and the reviewer’s load limits with the pack.','No load is placed until restraint and construction checks are complete.')]),
 'small-wall-hole':guide('procedure','A small, dry hole in sound ordinary gypsum wallboard using a patch product explicitly rated for that opening. No cavity enlargement.','Stop for dampness, recurring cracks, suspected hazardous coatings, ceiling damage or a fire/sound-rated assembly requiring its approved repair.',['drywall','lead','wall'],[
 step('Size the damage','Measure the widest opening and inspect the surrounding paper without cutting into the wall. Photograph it next to a ruler. Use the patch manufacturer’s maximum opening size to choose the repair.','The complete damaged area falls inside the selected patch’s limit.'),
 step('Prepare the surface','Protect the floor and keep dust contained. Once coating hazards are resolved, remove only loose surface fragments and dust. Do not push tools into the cavity.','The patch perimeter will adhere to clean, dry, sound board.'),
 step('Apply the patch system','Position the manufacturer-specified backing or self-adhesive patch. Apply its compatible filler or compound with a putty knife, spreading beyond the patch edge in a thin layer.','The repair is supported as specified and the patch is covered.'),
 step('Let it dry and refine','Wait for the product’s drying interval. Add thin coats where it has shrunk; feather the edges wider instead of building a hump. When dry, smooth only as needed with dust controls.','A light held across the wall shows a flat transition.'),
 step('Prime and blend','Remove dust, prime the repaired area with a compatible primer, then test the finish colour and sheen. Recoat a larger wall area if the touch-up remains visible.','The patch is dry, firm and visually blended; the cause has not returned.')]),
 'paint-room':guide('procedure','Brush or roller repainting of sound interior walls with a compatible water-based coating system.','Resolve dampness and old-coating hazards first. Spraying and specialist coatings require their own setup and product instructions.',['wall','room','lead'],[
 step('Measure and protect','Record wall lengths and height, subtract openings and separate ceiling/trim areas. Use the quantity calculator with the actual label coverage. Move furniture and protect floors; leave stable access.','Surface area and the coating product are recorded.'),
 step('Clean and repair','Clean grease and dirt using a surface-compatible cleaner, remove residue and let dry. Repair minor sound-wall defects. Do not paint over active moisture, loose coating or unassessed old paint.','The surface is dry, clean and sound.'),
 step('Test the coating system','Prepare a small area using the chosen primer and paint. Let it dry and inspect adhesion, coverage and sheen before buying the full quantity or painting the room.','The sample adheres and the colour is accepted in room lighting.'),
 step('Work one surface at a time','Prime where the coating system requires it. Cut in a manageable section with a brush, then roll while that edge remains workable. Apply even coats at the label spread rate.','No missed strips, heavy runs or dry lap marks.'),
 step('Recoat and return the room','Follow recoat and cure times for the actual temperature and humidity. Inspect in daylight, touch up as appropriate and keep furniture away until the coating tolerates contact.','The required coats and return-to-service interval are complete.')]),
 'mulch-bed':guide('procedure','Top-up mulch around established shrubs or trees at ground level. Choose material and depth for the plants and local conditions.','Do not cover exposed trunk flares, bury plant crowns or treat drainage/plant decline as a mulch shortage.',['mulch'],[
 step('Measure the area and existing depth','Break the bed into rectangles and measure several existing mulch depths. Exclude paths, stems and structures. The quantity calculator uses the additional depth, not the final total.','Existing mulch is counted before ordering.'),
 step('Choose the right top-up','For woody plants, the cited extension guidance uses a shallow 1–3 inch layer, with mulch clear of trunks. Confirm whether that recommendation fits the plants, climate and fire-risk rules at your site.','The target depth and material are suitable for this bed.'),
 step('Clear the surface','Remove litter and accessible weeds. Pull old mulch away from bark and crowns. Keep soil and roots undisturbed and preserve drainage paths.','No mulch is touching bark and no drain is covered.'),
 step('Spread an even layer','Place small piles between plants and rake them level. Check depth in several places; taper to bare clearance at stems rather than building a mound against them.','Depth is even, shallow and includes the old material.'),
 step('Check after watering','Look for shifted piles, buried stems or blocked water flow. Correct them and record the installed depth so the next top-up is based on what remains.','Water reaches the soil and trunk clearances remain open.')]),
 'weatherstrip':guide('procedure','Replacing a compatible self-adhesive weatherseal on an ordinary, correctly aligned door.','Use approved service parts for fire/security/specialist doors. Fix alignment first; never obstruct intentional ventilation.',['weather'],[
 step('Identify the seal and gap','Close the door gently and find the leaking edge. Record the old profile, attachment method and gap. Select a seal that compresses without preventing the latch from engaging.','The door closes normally before adding the new seal.'),
 step('Measure each run','Measure the top and side runs separately. Check the product’s placement diagram; hinge and latch edges may use different locations. Dry-fit a short sample before cutting every length.','The sample fits the gap and does not bind.'),
 step('Clean the bonding area','Remove failed adhesive carefully without damaging the finish. Clean using a compatible method, then allow the frame to dry. Check the chosen seal’s application-temperature range.','The bonding surface is dry and free of grease or dust.'),
 step('Apply without stretching','Cut each run to length. Peel the backing gradually and press into the manufacturer’s stated position without pulling the strip longer. Close corner gaps without stacking layers.','The seal is continuous and stays attached.'),
 step('Test the door','Open and close it several times. Confirm latch engagement and a consistent seal. If extra force is needed, correct the profile or placement instead of forcing the door.','Normal opening, closing and latching are preserved.')]),
 'hvac-filter':guide('procedure','Replacing a disposable filter in the equipment’s documented user-accessible filter slot.','Stop if access requires an electrical compartment, the equipment is wet/damaged, the filter type is unclear or the manual calls for a technician.',['filter'],[
 step('Confirm the replacement','Read the equipment manual and old filter markings. Match actual size, filter type and the permitted resistance/MERV specification. A higher rating is not automatically compatible.','The replacement matches the equipment specification.'),
 step('Stop the system safely','Follow the manual’s shutdown procedure and wait for moving parts to stop. Open only the documented filter access; photograph the old airflow arrow before removal.','The unit is stopped and the filter is safely accessible.'),
 step('Remove the old filter','Slide it out carefully and bag disposable media. Inspect the accessible slot for damage or moisture without reaching into the equipment. Do not wash a disposable filter.','The slot is sound and the new filter will seat correctly.'),
 step('Fit in the airflow direction','Align the new filter’s arrow with the documented airflow direction, slide it fully into its guides and close the access cover as instructed.','The filter has no edge gaps and the cover is secure.'),
 step('Restart and record','Restore operation per the manual. Listen for abnormal operation and stop if it occurs. Record the replacement date and the manual’s inspection interval.','Normal operation resumes and the next check is recorded.')]),
 'patio-clean':guide('procedure','Routine cleaning of identified concrete pavers with a compatible mild cleaning product.','Stop for unstable paving, unknown coatings, persistent hazardous spills or a cleaner that is not approved for the surface.',['clean'],[
 step('Identify the surface','Confirm the paver product, any sealer and the jointing material. Photograph stains and loose joints. Choose a cleaner approved for all three.','Surface and cleaner compatibility are known.'),
 step('Clear and protect','Move furniture, sweep loose dirt and protect adjacent plants. Plan where rinse water can lawfully go; keep contaminated runoff out of storm drains.','The area is clear and runoff can be controlled.'),
 step('Test a hidden spot','Dilute only as the label directs and test a small inconspicuous patch. Let it dry before judging colour or surface damage. Never mix cleaning chemicals.','The dry test patch shows no damage or unwanted colour change.'),
 step('Clean gently in sections','Use the approved brush-and-cleaner method and label dwell time. Rinse as directed, keeping the joint material in place. Do not default to an aggressive pressure-washer setting.','Dirt is removed without etching the surface or washing out joints.'),
 step('Inspect when dry','Check for residual cleaner, slickness and damaged joints. Restore joints only with the compatible system and its instructions. Return furniture once the area is ready for use.','The surface is clean, stable and not slippery.')]),
 'paint-cabinets':guide('procedure','Repainting sound cabinet fronts using a coating system approved for the identified substrate.','Stop for peeling laminate, swollen MDF, unknown hazardous coatings or an unsuitable spray space. Spraying requires the coating/equipment ventilation and PPE specifications.',['cabinets','laminate','lead'],[
 step('Label and identify','Label each door, drawer front and hinge location before removing parts. Bag hardware by opening. Identify solid wood, veneer, MDF or laminate; inspect damaged edges.','Every front can return to its original opening.'),
 step('Clean before abrasion','Remove cooking grease with a compatible cleaner and remove residue. Let dry. Resolve coating hazards before scuffing; do not sand through veneer or laminate.','Surfaces are clean and the substrate is intact.'),
 step('Prove adhesion on a sample','Use the selected bonding/priming system on a hidden area or spare front. Include the topcoat and the product’s adhesion-check interval. Do not assume wall primer suits laminate.','The complete coating system adheres to this substrate.'),
 step('Apply controlled coats','Set parts on stable supports and protect hinge cups and moving hardware. Apply thin, even coats by the approved method, observing temperature, recoat and ventilation requirements.','Edges are covered without runs or paint in hardware interfaces.'),
 step('Cure before reassembly','Wait for handling and service-cure times, not just touch-dry time. Refit labeled fronts, adjust clearances and add compatible bumpers where required.','Doors close without sticking and the coating resists normal handling.')]),
 'refinish':guide('procedure','A compatible cosmetic refresh of sound furniture; no structural repair or unidentified chemical stripping.','Pause for valuable antiques, thin/damaged veneer, hazardous coatings or unknown finish compatibility.',['laminate','lead'],[
 step('Inspect the piece','Photograph loose joints, veneer edges and finish damage. Identify the surface before choosing an opaque paint or clear-finish route. Repair structural defects separately.','The piece is stable and the surface type is known.'),
 step('Clean a test area','Try a finish-compatible cleaner in an inconspicuous place. Check after drying; a gentle clean may solve the appearance problem without stripping.','The test does not soften or discolour the original surface.'),
 step('Choose one complete system','Record cleaner, preparation method, primer if needed, topcoat and application method. Ask the coating supplier to resolve unknown compatibility before sanding.','The products are compatible with each other and the substrate.'),
 step('Prepare and coat a sample','After hazardous-coating concerns are resolved, use minimal approved abrasion without breaking through veneer. Remove dust and test the selected coating through its specified cure.','The sample adheres and produces the intended finish.'),
 step('Finish the piece','Repeat the tested method in manageable sections. Keep oily cloths and waste according to the product’s fire/disposal instructions. Allow full service cure before replacing objects.','The finish is cured and the piece remains stable.')]),
 'raised-bed':guide('system','A ground-level raised growing bed. Soil quantities use INTERNAL length, width and filled depth.','Balconies, roofs, retaining walls, slopes and elevated beds need a load/drainage assessment. Unknown treated or reclaimed timber needs identification.',['beds','bedMaterials'],[
 step('Check the growing site','Record sun, access and drainage. Confirm utility locations before digging or staking. Check soil suitability for food crops where contamination is possible.','The location suits the plants and ground disturbance is cleared.'),
 step('Choose the bed system','Select a complete bed design or kit that specifies wall height, corner joints and bracing for wet soil. Match materials and corrosion-resistant hardware to that system.','The sidewalls and joints have a specified wet-soil application.'),
 step('Mark the footprint','Mark OUTSIDE dimensions and access paths. Verify you can reach the growing area. Prepare the base and assemble the sides according to the chosen system without blocking drainage.','The bed is square, stable and drains as specified.'),
 step('Measure inside and order fill','Measure the actual INTERNAL dimensions. Calculate growing-medium volume, subtract existing fill and compare bagged versus delivered bulk supply. Select the soil blend for the plants; volume is not a soil recipe.','The order uses internal volume and the delivery route is usable.'),
 step('Fill and establish','Fill as the bed-system instructions permit, checking sides for movement. Water and assess settlement before planting at the crop’s spacing. Record the soil blend and planting plan.','No bowing or pooling; plants have appropriate spacing and water.')]),
 'in-ground-bed':guide('procedure','Creating a small ground-level planting area in suitable, uncontaminated soil.','Resolve utility locations before ground disturbance. Stop for suspect contamination, major drainage problems or significant tree-root disturbance.',['beds','planting'],[
 step('Observe before digging','Record sunlight at different times, water after rain and existing vegetation. Mark the bed and walking space. Obtain the required utility clearance.','Sun, drainage and below-ground constraints are recorded.'),
 step('Test the soil','Use a local soil-test service where appropriate and select amendments from its recommendation. Check site history before growing food; do not buy a generic fertilizer bundle first.','Amendments address an identified need.'),
 step('Prepare the footprint','Remove unwanted vegetation by a site-appropriate method. Work only when soil conditions permit; avoid kneading wet soil into compacted clods. Keep the soil surface able to drain.','The area is weed-managed without compacting or damaging roots.'),
 step('Lay out before planting','Place labeled plants or mark seed rows using mature spacing and local season guidance. Keep paths reachable and taller plants from shading those needing sun.','The actual plant count fits the layout.'),
 step('Plant and monitor','Use the plant or seed instructions for depth. Water to establish, label varieties and inspect moisture regularly. Adjust watering to actual conditions rather than a fixed universal schedule.','Plants are correctly placed and an establishment check is planned.')]),
 'plant-selection':guide('procedure','Choosing and laying out plants for a measured ground-level bed; not a universal climate recommendation.','Check local invasiveness and toxicity for children/pets; uncertain identifications need a local nursery or extension adviser.',['plants','planting'],[
 step('Record the site','Note sunlight hours, soil moisture, available depth and mature-height limits. Record your location and local planting season before making a shortlist.','Every candidate can be compared with actual site conditions.'),
 step('Shortlist by mature size','Use local horticultural guidance and the plant’s label for spacing, climate and water needs. Check scientific names to avoid choosing a different plant with the same common name.','Names, mature sizes and site needs are recorded.'),
 step('Check household constraints','Check toxicity, thorns, invasiveness and required maintenance. Remove plants that do not fit how children, pets or household members use the space.','The shortlist fits the household as well as the garden.'),
 step('Map and count','Draw the bed to scale. Place mature plant spreads, then count each variety. Leave access for maintenance instead of filling every gap with nursery-size pots.','The layout has no unintended mature-size conflicts.'),
 step('Buy and establish','Compare the same species/cultivar and healthy root condition at each supplier. Use its planting instructions and set an establishment watering/check schedule.','Labels and care details are saved with the project.')]),
 'shelves':guide('system','Installing a complete shelf-and-support system to the manufacturer’s defined substrate and load requirements.','No generic wall anchor, shelf span or load is assumed. Unknown wall structure/services or an unsupported load needs assessment.',['shelves'],[
 step('Define the load and space','Measure the shelf envelope and weigh or estimate all contents plus the shelf. Record wall type and likely fixing locations without drilling.','Size, total load and wall construction are identified.'),
 step('Select the exact system','Obtain instructions for the actual brackets, shelf material and wall fixings. Record support spacing, edge distances and the rating for that arrangement; a bracket rating alone is not a shelf rating.','A matching system specification covers the full installation.'),
 step('Mark and check','Locate concealed services with suitable methods and verify structural support. Mark the first support, transfer level marks, then dry-position the shelf to check doors and access.','All fixing positions are suitable and unobstructed.'),
 step('Install to the model instructions','Use the specified drill bit, hole depth, fixing method and tightening guidance. Fit supports, secure the shelf as required and check level. Stop if a fixing spins or the wall crumbles.','All supports and shelf-retention details match the selected system.'),
 step('Record use limits','Record the permitted total load and layout. Place heavy items as the system instructs and inspect for movement. Do not hang or climb on the shelf to test it.','No movement is visible and the use limit is retained.')]),
 'pegboard':guide('system','Installing a named metal pegboard panel and compatible hooks using that panel’s instructions.','Do not transfer the Wall Control screw pattern to other panels or unknown wall substrates. Resolve concealed services first.',['pegboard'],[
 step('Lay out the tools','Arrange your tools on the floor within the proposed panel area. Keep sharp/heavy tools low and record total weight including accessories.','The panel size fits the tools and safe reach.'),
 step('Match the panel and wall','Read the exact panel instructions. For Wall Control, use its specified framing or approved alternative anchorage; its folded panel does not need the same spacers as ordinary wooden pegboard.','Panel, hooks, wall and fastening details are compatible.'),
 step('Mark mounting holes','Locate services and suitable supports. Hold the panel level with its slots in the instructed orientation and mark every required mounting point.','Required mounting holes align with appropriate supports.'),
 step('Secure and fit accessories','Install to the panel instructions, starting all fixings before final alignment. Engage each compatible hook fully; check its retention before placing a tool.','The panel is level and hooks are correctly engaged.'),
 step('Load deliberately','Use the published panel and accessory limits. Place heavy tools low and keep handles easy to grasp. Reposition accessories rather than forcing incompatible hooks.','Nothing can fall into the working area during normal use.')]),
 'cabinet-doors':guide('system','Replacing ordinary cabinet fronts using a selected hinge system; no automatic door-size or boring assumptions.','Stop for loose cabinets, damaged hinge support, unverified heavy/glass doors or unknown hinge geometry.',['hinge'],[
 step('Label the openings','Measure each opening at several points and label a sketch. Record neighboring fronts, desired reveal, overlay and swing restrictions. Do not assume two openings are identical.','Each opening has its own dimensions and label.'),
 step('Choose hinge geometry first','Record the exact hinge and mounting plate, door thickness/weight, cup drilling and overlay tables. Obtain door-size and hinge-count guidance for this combination.','Door sizes follow the selected hardware, not a generic deduction.'),
 step('Prove one front','Order or prepare one sample front to the reviewed dimensions. Use the hardware maker’s template and specified boring depth; test on matching scrap before drilling the front.','Hinge cups fit without breaking through the face.'),
 step('Hang and adjust the sample','Support the door while attaching it. Use the hinge adjustment sequence to set gaps and check full opening, adjacent fronts and closing.','The sample fits and operates before repeating the set.'),
 step('Repeat and record','Apply the proven dimensions only to the matching labeled openings. Finish/cure fronts, refit handles and save the hinge model and settings.','Every front operates freely and fixing support is sound.')]),
 'drawers':guide('system','Sizing a drawer for a selected slide system and cabinet opening.','No default half-inch deduction, bottom thickness or load rating is assumed; undermount and side-mount systems differ.',['hinge','anchor'],[
 step('Measure the opening','Measure clear width at front and back, usable depth, height and any face-frame projection. Record how the drawer front must overlap or sit inside the opening.','The narrowest clear dimensions and obstructions are known.'),
 step('Select the slide model','Obtain exact slide installation instructions. Record side/bottom clearances, drawer length, notches, drilling pattern and rated use. Include the box weight in the load.','The chosen model supports the intended arrangement.'),
 step('Prepare the box specification','Derive the box dimensions from the hardware’s equations. Specify joints, bottom support and material thickness before generating a cut list. Have uncertain spans or loads reviewed.','Box dimensions and joints are resolved on one drawing.'),
 step('Dry-fit one drawer','Build or order one sample to the approved specification. Check box diagonals and slide alignment before fitting the front; use the manufacturer’s release and adjustment procedure.','Travel is smooth and latches/stops engage normally.'),
 step('Fit the front and record limits','Set the front gaps using temporary spacers. Secure it using the reviewed fixing method, retest travel and record the load limit. Restrain the cabinet where required.','Front clearances, stops and cabinet stability are confirmed.')]),
 'workbench':guide('system','Selecting and assembling a documented freestanding workbench design for stated workshop tasks.','A bench is not a scaffold or seat. Vises, heavy machines, mobility and concentrated loads need explicit support details.',['bench'],[
 step('List the working loads','Record the machines, workpieces and clamp/vice forces you expect. Measure floor space, working height and access around the bench.','Intended work and equipment are specified.'),
 step('Choose a complete plan','Use a published plan or rated kit with its full parts, joints and bracing schedule. The linked one-sheet plan is a separate fixed design; do not substitute this worksheet for its instructions.','One coherent plan has been selected and saved.'),
 step('Check before cutting','Match material grade, actual thickness and hardware to the plan. Resolve any proposed size change with a competent maker; changes can affect bracing and span.','Cutting dimensions refer to the unchanged or reviewed design.'),
 step('Assemble in the stated order','Prepare and label parts, dry-fit the base and assemble to the chosen plan. Check square and level at each stage before fitting the top or equipment.','Joints and bracing are complete without rocking.'),
 step('Set up for use','Install equipment only with the required support/fixing details. Confirm wheel locks if fitted and clear walking routes. Record the intended-use limits with the plan.','The bench is stable for its specified tasks.')]),
 'planter':guide('system','A freestanding outdoor planter from a design that specifies its base, supports and drainage.','Wet growing medium is heavy. Elevated supports, decks, balconies and roofs need a suitable load assessment.',['bedMaterials','beds'],[
 step('Identify the support surface','Measure the location and establish whether it is soil, paving, decking or an elevated structure. Record where overflow can drain without damaging the building.','The support and drainage route are suitable.'),
 step('Select a load-aware design','Choose a complete planter plan or kit with specified base support, corner joints and drainage. Identify the timber/material and hardware suitability for the growing use.','The design covers saturated contents, not just empty-box weight.'),
 step('Assemble the empty planter','Follow the selected cut list and assembly details. Before lining or filling, check joints, supports and all drain openings. Do not create a sealed water-holding box accidentally.','The empty structure is stable and drainage is open.'),
 step('Measure growing volume','Measure internal growing length, width and depth, excluding false bases and reservoirs. Choose a container-growing medium appropriate to the plants and system.','The quantity is based on actual internal volume.'),
 step('Fill and inspect','Fill as the design allows. Water and check drainage, base deflection and joint movement before planting. Stop and unload safely if the structure changes shape.','Water exits correctly and supports remain stable.')]),
 'garden-storage':guide('system','An outdoor equipment-storage enclosure built to a complete selected plan; no seating or child-access claim.','Lids can trap or strike people. Child-accessible boxes need an appropriate tested safety design; do not improvise lid stays.',['storage'],[
 step('Measure what must fit','Measure the largest tool and its removal path. Record ventilation needs and items unsuitable for enclosed storage, including fuels and chemicals needing dedicated storage.','The contents and access opening are defined.'),
 step('Choose the enclosure design','Select a documented exterior plan or kit. Confirm base, joints, weather shedding, ventilation, hinges and lid supports as a single system.','The plan specifies safe opening and holding of the lid.'),
 step('Prepare the location','Use the plan’s stable base and clearances. Keep drainage open and timber away from persistent standing water as specified.','The enclosure will stand level without blocking drainage.'),
 step('Build and test empty','Follow the exact parts and fastener schedule. Check square, then fit hinges/stays with the lid supported. Keep hands out of pinch points during testing.','The lid behaves as specified throughout its travel.'),
 step('Finish and label use','Apply the compatible exterior finish and let cure. Confirm weather shedding and ventilation, then load only the intended equipment. Do not treat the lid as a seat without a rated design.','Storage use and maintenance needs are recorded.')]),
 'garden-trellis':guide('system','Selecting a trellis for a known plant and exposure; installation depends on the chosen support system.','Do not improvise wall anchors, post foundations or supports for heavy mature vines. Locate services before digging.',['plants','planting'],[
 step('Identify the mature plant','Record mature spread, climbing habit and whether it needs tying or twines naturally. Include seasonal foliage/fruit weight when selecting the trellis.','The support suits the plant at maturity.'),
 step('Map exposure and access','Record wind exposure, wall condition or ground position. Keep access for pruning and avoid placing supports where they obstruct routes or drainage.','The position works for maintenance and exposure.'),
 step('Select complete supports','Choose a manufacturer-supported trellis/post/fixing system for this use. Obtain wall-attachment or ground-installation details and resolve any unknown load conditions.','Support details are documented before drilling or digging.'),
 step('Install before training','Locate services and install to the system instructions. Check alignment and connections before moving plant growth onto it.','The unloaded trellis is firmly supported.'),
 step('Train and inspect','Use plant-appropriate loose ties and leave growth room. Inspect for constricting ties, loose connections and overload after growth or storms.','Plant growth is supported without restricting stems.')]),
 'bed-edging':guide('system','Installing a selected low garden-edging system; not a retaining wall or vehicle restraint.','Locate services before stakes/trenches. Height differences and soil retention require a suitable engineered/product system.',['beds'],[
 step('Lay out the route','Use a hose or string to try the curves and mowing clearances. Measure the final route including returns and corner joins.','The route fits maintenance access and the selected edging’s bend radius.'),
 step('Specify the components','Record the exact edging, connectors, stakes, permitted height and installation depth from its instructions. Count joins from real stock lengths rather than total length alone.','The order includes the system’s connectors and restraints.'),
 step('Check the ground','Confirm service clearance before driving stakes or digging. Address roots, drains and soft patches without damaging them.','The installation route is safe to disturb.'),
 step('Install progressively','Follow the product’s preparation and staking sequence, keeping the intended reveal consistent. Check curves and levels before backfilling each section.','Sections join cleanly without sharp exposed ends.'),
 step('Finish the interfaces','Backfill and compact only as specified. Check mowing clearance, trip points and drainage at both sides; recheck after rain.','The edge remains stable and does not act as an unintended dam.')]),
 'drip-irrigation':guide('system','A complete hose-end garden drip kit with a compatible supply; no household plumbing alteration.','A kit pressure regulator is not automatically backflow protection. Confirm local supply/backflow requirements before connecting.',['drip'],[
 step('Draw the watering zones','Map beds and containers, then group plants with similar needs. Measure tubing routes and height changes and count watering points.','Each zone has a measured route and plant list.'),
 step('Confirm the supply system','Use the exact kit requirements for pressure, flow, filtration and backflow protection. Have uncertain supply protection resolved locally; do not connect a generic parts bundle first.','Supply and kit requirements match.'),
 step('Lay out above ground','Place tubing and emitters before cutting. Use only compatible sizes/fittings and respect the kit’s run and emitter limits. Keep lines clear of walking and cutting routes.','The layout remains inside the kit’s design limits.'),
 step('Assemble and flush','Follow the kit’s connection order, flushing instructions and end closures. Open the supply as directed and check each joint and outlet for leaks or missed flow.','Every intended outlet delivers and no fitting leaks.'),
 step('Tune to actual soil moisture','Start with local plant guidance and the kit’s output, then inspect wetting at the roots. Adjust timing and grouping to avoid runoff or saturated soil.','Roots receive water without persistent pooling; the schedule is recorded.')]),
 'paver-path':guide('system','A pedestrian garden path using a locally specified paver/base system.','No universal excavation depth, fall or base thickness is supplied. Utilities, drainage, soils and climate must be resolved before excavation.',['pavers','joints'],[
 step('Measure the route','Sketch width, lengths, curves and every threshold. Mark the route on site and walk it. Include edge restraints and working room outside the paved surface.','The path is usable and measured.'),
 step('Obtain the site specification','Identify services and local excavation requirements. Obtain base, bedding, level/fall, drainage and edge details for the chosen paver system and actual ground.','A site-appropriate installation section is recorded.'),
 step('Order the complete system','Calculate surface area and paver quantities using the selected unit/pattern and waste allowance. Calculate base layers from compacted design volumes; ask the supplier for loose delivery conversion.','Pavers, bedding, base, joints and edging are all included.'),
 step('Prepare and lay to specification','Excavate only after clearances. Build/compact layers to the selected system, check levels, screed bedding and lay from the reference line. Use specified dust controls for any cuts.','Levels and layer thicknesses are checked before they are covered.'),
 step('Restrain, joint and inspect','Fit edge restraint and jointing using the compatible system’s sequence and weather window. After required curing, check uneven edges and water movement.','The path is restrained, joints are filled and drainage works.')]),
 'paver-patio':guide('system','A pedestrian patio using a selected site-specific pavement system.','Do not extend this to vehicles, retaining structures or drainage beside foundations without the appropriate design.',['pavers','joints'],[
 step('Mock up the footprint','Mark the patio with furniture and walking clearances included. Record thresholds, doors, drains and nearby foundations on the plan.','Furniture use and circulation fit the footprint.'),
 step('Resolve ground and levels','Obtain utility clearance and a base/drainage specification for the actual soils, climate and pavers. Set finished levels and water routes before ordering aggregate.','Levels protect thresholds and do not redirect water toward structures.'),
 step('Calculate and schedule','Measure area by splitting irregular shapes. Use supplier pattern coverage and waste. Plan aggregate deliveries, spoil removal and compactor access in build order.','Quantities and access cover the complete system.'),
 step('Build the specified layers','Follow the installation section, checking compaction and levels as layers are built. Lay pavers from control lines without disturbing the prepared bedding.','No unverified layer or level is buried by the next stage.'),
 step('Complete the edges and joints','Use compatible restraint and joint material, following its application and cure instructions. Inspect surface transitions and drainage before regular use.','The complete surface is stable, restrained and ready for its intended use.')]),
 'paver-edging':guide('system','Repairing restraint on an identified pedestrian paver system after the cause of movement is understood.','Recurring settlement, failed drainage or undermining needs assessment beyond replacing the edging.',['pavers','joints'],[
 step('Map the movement','Photograph shifted units, gaps and low spots. Compare the edge with undisturbed paving and note where water runs.','The repair boundary and likely cause are recorded.'),
 step('Identify matching parts','Confirm pavers, bedding, base and restraint type. Obtain the repair instructions and compatible restraint fixings for this installation.','Replacement components match the existing system.'),
 step('Open only the reviewed area','Locate services and preserve reusable pavers with position labels. Remove the affected area following the chosen repair method without undercutting adjoining pavement.','The exposed base can be assessed before rebuilding.'),
 step('Restore support and restraint','Correct the identified base defect to the site specification, re-establish levels and fit the compatible restraint. Do not stake into unverified ground.','The rebuilt support and edge meet the repair specification.'),
 step('Relay and recheck','Relay units and replace joint material as specified. Check levels and drainage after the cure period and again after rain.','The repaired edge stays aligned and water drains correctly.')]),
 'trim':guide('system','Fitting ordinary nonstructural baseboard trim to verified fixing locations.','Resolve old-coating hazards and concealed services before removal or fastening. Do not pin a floating floor through its expansion gap.',['trim','lead'],[
 step('Record runs and corners','Label each wall run, profile and corner. Measure twice and note the flooring expansion requirements and uneven surfaces.','The cutting sketch matches the room.'),
 step('Plan joints on scraps','Use offcuts to establish inside/outside corner fits rather than assuming walls are square. Distribute stock lengths to reduce waste and avoid awkward short pieces.','Trial joints close without excessive filler.'),
 step('Confirm fastening','Identify suitable fixing support and concealed services. Specify fastener length and positions for the trim/substrate so they cannot reach known services or restrict flooring movement.','Fastening details are resolved before using a nailer.'),
 step('Cut and dry-fit','Prepare one labeled piece at a time. Scribe where needed using a controlled setup and dry-fit the complete run before fastening.','Profiles line up and joints fit the actual walls.'),
 step('Fix and finish','Fasten using the selected method, fill permitted small gaps and spot-prime repairs. Apply the compatible finish without sealing required movement or ventilation gaps.','Trim is secure and the floor can still move as designed.')]),
 'curtain-rail':guide('system','Installing a complete rail and bracket system suited to the curtain weight and wall/ceiling.','No universal anchor or bracket spacing is assumed. Identify services and load-bearing substrate before drilling.',['rail'],[
 step('Measure curtain coverage','Record the opening, desired overlap, drop and curtain stack-back space. Check handles, radiators and door swings. Weigh or specify the curtains and rail.','Coverage and total hanging weight are known.'),
 step('Select compatible components','Obtain instructions for the exact rail, brackets, gliders and ends. Confirm support spacing and wall/ceiling fixings for the substrate.','The full assembly and fixing method are specified.'),
 step('Mark a level reference','Locate concealed services and suitable supports. Transfer bracket marks from one level line and check rail joints and end clearances.','All fixing positions are suitable and aligned.'),
 step('Install and engage the rail','Follow the selected bracket and connector sequence. Use suitable access equipment and help to hold long rails. Fit all end stops and retention pieces.','Every connector and retaining feature is engaged.'),
 step('Hang and function-check','Distribute the curtains within the system’s limits. Draw them slowly along the full track, watching for binding or bracket movement.','Curtains move freely and the supports remain firm.')]),
 'door-handle':guide('procedure','Like-for-like replacement of a compatible handle/latch on an ordinary interior door using existing holes.','Fire, security, exterior and escape-route doors need approved hardware/processes. Stop for damaged fixing support or incompatible dimensions.',['hardware'],[
 step('Measure before buying','Record door thickness, backset, bore sizes, latch faceplate and handing. Compare with the exact new handle model rather than relying on a “universal” label.','The replacement fits the existing preparation.'),
 step('Keep the door open','Support the door so it cannot close during work. Photograph the hardware and remove it following its release/screw arrangement, keeping parts together.','Access remains available from both sides.'),
 step('Fit the matched latch','Set the adjustable latch only as its instructions allow. Place the latch in the existing preparation with its bevel oriented correctly for closing.','Latch orientation and backset match the opening.'),
 step('Install and test open','Fit the spindle/handles and tighten as the manufacturer specifies. Operate the latch and any privacy release repeatedly with the door open.','Both handles and the release work without binding.'),
 step('Check gentle closing','Only after open-door tests, close gently and confirm strike engagement and reopening. Stop for misalignment rather than forcing the door or grinding hardware.','The door latches and opens normally from the intended sides.')]),
 'seasonal-check':guide('procedure','A record-based, ground-level home maintenance walkthrough; not a building inspection or trade service.','Gas smells, smoke, sparking or flooding go to urgent guidance. Roofs, live electrical equipment and inaccessible areas are outside this walkthrough.',['seasonal','filter','anchor'],[
 step('Make a property checklist','List rooms, visible exterior areas and equipment manuals. Add the last service date and manufacturer interval where known.','The checklist is specific to this property.'),
 step('Look from safe access','Inspect accessible areas for new staining, loose hardware, leaks and blocked ventilation without dismantling services. Photograph findings with dates.','Each finding has a location and clear description.'),
 step('Separate urgent from routine','Move immediate hazards out of the maintenance list and use urgent help. Assign uncertain defects to the appropriate trade rather than covering them cosmetically.','Hazards are not waiting behind cosmetic tasks.'),
 step('Do documented owner tasks','Complete only tasks described as owner maintenance in the equipment manuals, such as a user-accessible filter change. Gather exact part numbers before shopping.','Each task has the correct instructions and parts.'),
 step('Record and schedule','Save what was done, what remains and who is responsible. Set future reminders in your calendar from the equipment’s interval and local season, not a generic date.','Open tasks and next service dates are recorded.')])
};
export const contentFor=id=>projectContent[id]||null;
export const contentLabel=id=>contentFor(id)?.level==='procedure'?'Step-by-step guide':contentFor(id)?.level==='design'?'Drawing + review':'System-specific guide';
export function contentProgressKey(record){const answers=Object.fromEntries(Object.entries(record.answers||{}).sort(([a],[b])=>a.localeCompare(b)));const input=record.pack?.input?['width','height','depth','thickness','shelves'].map(k=>Number(record.pack.input[k])):null;return JSON.stringify([record.guideId,contentFor(record.guideId)?.version,answers,input]);}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function contentHTML(id){const c=contentFor(id);if(!c)return '';return `<section><h2>${esc(contentLabel(id))}</h2><p>${esc(c.scope)}</p><p><strong>Pause if:</strong> ${esc(c.stop)}</p>${c.steps.map((s,i)=>`<section><h3>${i+1}. ${esc(s.title)}</h3><p>${esc(s.action)}</p><p><strong>Check:</strong> ${esc(s.check)}</p></section>`).join('')}<h3>References and scope</h3><p>Original Kitsley guidance, version ${esc(c.version)}. References inform specific topics; they do not certify this project. Exact product instructions and local conditions take precedence.</p><ul>${c.sources.map(id=>{const r=contentSources[id];return `<li><a href="${esc(r.url)}">${esc(r.title)}</a> — ${esc(r.scope)} (checked ${r.checkedOn})</li>`;}).join('')}</ul></section>`;}
