import fs from 'node:fs';
import {contractorBenchmarks,benchmarkEvidenceLimits} from '../lib/contractor-benchmark.mjs';
import {knowledgeCoverage} from '../lib/knowledge-coverage.mjs';
import {foundationAnswer,findFoundation} from '../lib/diy-knowledge.mjs';
const now=Date.now(),report=knowledgeCoverage([],now),cases=JSON.parse(fs.readFileSync(new URL('../knowledge/six-area-scenarios.json',import.meta.url)));
const results=cases.map(s=>({id:s.id,domain:s.domain,passed:findFoundation(s.question,{limit:5,now}).some(e=>e.id===s.referenceId)&&foundationAnswer(s.educationalQuestion,{now})?.foundationIds[0]===s.referenceId&&foundationAnswer(s.question,{now})===null}));
let md=`# Kitsley: experienced-contractor capability benchmark\n\nGenerated ${new Date(now).toISOString()} · Knowledge ${report.version} · Benchmark ${report.benchmarkVersion}\n\n## What “good” means\n\nThe comparison is the work expected of a contractor with 10 years of relevant experience, separately for each trade. Time served is context, not a numerical accuracy score. Kitsley has not demonstrated equivalent experience or qualifications.\n\n**Current position:** useful, scoped technical reference assistance, plus a bounded illustrated bookcase workflow. General independent contractor-level judgement is not established.\n\nThe old “7 records / Partial” report measured inventory. This report measures the gap to doing a complete real job. There is no defensible percentage or number of training weeks to close it yet.\n\n## Six areas\n\n| Area | Demonstrated scope / current position | Main gap to the contractor standard |\n|---|---|---|\n`;
for(const b of contractorBenchmarks){const d=report.domains.find(d=>d.id===b.id);md+=`| ${d.name} | ${b.level} | ${b.gap} |\n`;}
for(const b of contractorBenchmarks){const d=report.domains.find(d=>d.id===b.id),checks=results.filter(r=>r.domain===b.id);md+=`\n## ${d.name}\n\n**A 10-year contractor should be able to:** ${b.standard}\n\n**Useful in Kitsley today:** ${b.useful}\n\n**Real-world cases to pass:**\n\n${b.tasks.map(t=>'- '+t).join('\n')}\n\n**Unproven / missing:** ${b.gap}\n\n**Next evidence needed:** ${b.next}\n\nSupporting reference checks: ${checks.filter(r=>r.passed).length}/${checks.length} retrieval/exact-answer boundary checks passed. This is not a score for solving the cases above. ${d.references} current relevant reference records (secondary inventory; records overlap between areas).\n`;}
md+=`\n## How each complete case must be assessed\n\nEach capability stays **not demonstrated** until a complete answer has been examined, including follow-ups. A keyword match cannot promote it.\n\n1. Understand the request and reuse known facts; ask only missing questions that affect the answer.\n2. Select the right material, product, hardware and method for the actual use and conditions.\n3. Produce consistent, executable measurements, drawings, quantities and instructions where the engine supports them.\n4. Diagnose competing causes and revise the plan when new facts arrive.\n5. Identify dependencies and stop or hand off when site facts, evidence or a supported design operation are missing.\n\nA critical dimensional, compatibility or safety error fails the case regardless of other scores. Passing a small fixed set does not establish general competence. Use unseen variations and independent qualified reviewers before advancing a trade to a higher level.\n\n## Evidence and limits\n\n- ${results.filter(r=>r.passed).length}/${results.length} new scenario reference checks passed at report generation. These confirm relevant retrieval, exact educational-answer routing and refusal to treat personal questions as exact cached answers.\n- ${benchmarkEvidenceLimits.referenceChecks}\n- ${benchmarkEvidenceLimits.liveReasoning}\n- ${benchmarkEvidenceLimits.independentReview}\n- The plywood intake regression is covered by automated tests: recognize the material/task, give relevant initial help and avoid repeating known facts. Browser verification is reported separately in the release notes.\n- This work expands a reviewed reference engine and application logic. It is not model-weight training or autonomous expert certification.\n\n## Example that exposed a gap\n\n“Explain how to finish plywood” previously opened generic project discovery. A knowledgeable assistant should recognize the material and task, explain the finishing choices, and ask about the intended appearance and existing surface/exposure only when missing. This is an interaction/decision-routing failure, even if the knowledge database already contains finishing facts.\n`;
const dest=process.argv[2]||'CONTRACTOR-CAPABILITY-REPORT.md';fs.writeFileSync(dest,md);console.log(JSON.stringify({report:dest,referenceChecksPassed:results.filter(r=>r.passed).length,total:results.length,unverified:['unseen live model answers','independent trade review','field outcomes']}));
if(results.some(r=>!r.passed))process.exitCode=1;
